### ISSUE TITLE
Wesentliche Funktionalität: Zählung vs. Inventar

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#1]
Ein Inventar ist die Gesamtheit aller Zählungen einer Kultur. So wie es jetzt aufgebaut ist, ist ein Inventar quasi eine erweiterte Zählung mit zusätzlichen Attributen. Es ist wünschenswert, dass ein Inventar in übersichtlicher Weise eine Zusammenfassung aller Zählungen für alle Kulturen eines Gartens aufzeigt (am Besten in Tabellenform, welche auch ausgedruckt werden kann - siehe separates Issue).

**Comment by barbalex** [comment]
Ich versuche das nochmals zu formulieren:

Eine Zählung stellt die Gesamtzahlen für eine Kultur zum Zeitpunkt der Zählung dar.

In Gross-Anlagen gibt es aber viele Kasten, Beete und Reihen zu zählen. Daher sollen diese einzeln erfasst werden können.

Also wäre es vermutlich praktisch, wenn der Benutzer wählen könnte, ob er die Zählung direkt erfasst. Oder lieber alle Kasten / Beete / Reihen einzeln (nachfolgend Teilzählungen genannt). Und deren Zahlen werden dann von der App zur Zählung summiert.

Diese Teilzählungen würden dann wohl alle unter dem Datum der Zählung laufen.

Einige der Felder würden wohl nicht pro Teilzählung, sondern pro Zählung erfasst. Ich könnte mir diese vorstellen: Instruktion, Bemerkungen, ev. Blüh-Datum.

Zusätzlich braucht es eine Darstellung, die Inventar heissen sollte, welche die aktuellsten Zählungen aller Kulturen in einem Garten auflistet.

Habe ich das nun richtig verstanden? (offensichtlich ist es jetzt nicht so umgesetzt)

**Comment by barbalex** [comment]
Zählungen wurden angepasst. Bezüglich der Übersicht gibt es einen anderen issue (https://github.com/barbalex/vermehrung/issues/3)
