### ISSUE TITLE
Neue Art kann nicht erfasst werden

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#112]
Meldung von Seraina:

Heute ist mir aufgefallen, dass ich in der Datenbank keine neue Art erfassen kann. Wenn ich den Namen eingegeben habe und das Feld dann verlasse, verschwindet der Name wieder.

 
<img width="1059" alt="image001" src="https://user-images.githubusercontent.com/669783/211584290-5b17394c-203d-4d7d-82bd-1ea74ffd3e92.png">

**Comment by barbalex** [comment]
Ich kann es nicht nachvollziehen, d.h. bei mir funktioniert es

**Comment by Seraina1** [comment]
Ich auch mit der neuen Version 1.3.58 und bei anderen Mitarbeitenden nicht möglich. Als Browser wurde wie bisher Google Chrome verwendet. Der Verlauf wurde auch als Versuch wieder einmal gelöscht.

**Comment by barbalex** [comment]
Scheint gelöst
