### ISSUE TITLE
Dropdown-Liste verdeckt

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#113]
Zudem zeigt es die Dropdown-Menüs verzerrt hinter den weiteren Feldern an:

 
<img width="1062" alt="image002" src="https://user-images.githubusercontent.com/669783/211584327-b60c9150-041b-462b-ae62-74284fc2aa1f.png">

Meinen PC neu gestartet habe ich bereits, weil ich dachte, es könnte auch an der Darstellung vom PC liegen. Allerdings hat der Neustart das Problem nicht behoben. Kann es daher an der Datenbank liegen?

**Comment by Seraina1** [comment]
Das Problem ist immernoch vorhanden, auch in der neuen Version 1.3.58. Als Versuch wurde auch der Verlauf des Browsers (google Chrome) einmal gelöscht, was auch nicht weiter half.
