### ISSUE TITLE
Inaktive Einträge beim Einblenden optisch abheben

### ISSUE THREAD

**Issue by Seraina1** [barbalex/vermehrung#114]
Sobald man inaktive Einträge einblenden lässt, ist die Unterschiedung zwischen den inaktiven und aktiven Einträgen sehr schwierig. Es muss bei jedem Eintrag nachgeschaut werden, welcher nun der inaktive oder der aktive ist. 
Zur Vereinfachung der Übersicht wäre es daher gut, wenn man die inaktiven optisch von den aktiven Einträgen unterscheiden könnte (kursiv oder farblich).

**Comment by barbalex** [comment]
In Version 1.6.0 implementiert. 

Und zwar nicht nur im Navigationsbaum, sondern auch in Listen-Formularen.

Noch nicht in Auswahllisten, das kommt in https://github.com/barbalex/vermehrung/issues/118.

v1.6.0 noch nicht live, weil Google gerade Probleme mit seinen Servern hat 😢

**Comment by Seraina1** [comment]
Funktioniert 👍
