### ISSUE TITLE
Arten: Umgang mit mehreren Taxonomien ermöglichen

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#116]
Artnamen sind dynamischer als man möchte.

Sie hängen von der verwendeten Taxonomie ab. Und die kann ändern.

So wurde z.B. kürlich die von Info Flora verwendete Taxonomie aktualisiert. Neu gilt als Basis die Checklist 2017 bzw. wie sie in arteigenschaften.ch heisst: `DB-Taxref (2017)`.

Aktuell können in vermehrung.ch nur Arten aus der Taxonomie "SISF (2005)" gewählt werden. Und es kann nicht explizit gesagt werden, welche Taxa aus derselben oder anderen Taxonomien mitgemeint sind. In apflora wurde diese Funktionalität ergänzt: dort gibt es bei der Art im Navigationsbaum den Knoten "Taxa".

Das für die Art gewähle Taxon gibt den Namen. Die unter "Taxa" gelisteten Taxa sagen, welche Taxa aus welchen Taxonomien mitgemeint sind.

Die Anpassung wird recht aufwändig, weil sie strukturelle Anpassungen mit sich bringt. Und jedes Feld, bei dem eine Art gewählt wird, muss neu mit Taxonomien umgehen können.

Aber ich befürchte, es wird eher früher als später der Fall eintreffen, dass ein aktueller Name (aus DB-Taxref (2017)) gewählt werden soll. Und das ist aktuell nicht möglich.

@Seraina1 : Damit du über Updates an diesem Issue informiert wirst, kanns du:
- diesen Issue mit der Schaltfläche rechts abonnieren
- einen Beitrag schreiben, womit du automatisch abonniert hast

**Comment by barbalex** [comment]
Wenn es so bleibt, wie es aktuell ist:
- heissen alle Taxa weiterhin so, wie sie vor 2017 offiziell hiessen
- Taxa, die es in der Taxonomie zuvor nicht gab, können nicht erfasst werden
- Wird nicht geklärt, welche Synonyme/Unterarten im Namensgebenden Taxon mit gemeint sind

Letzteres ist bei vermehrung.ch weniger wichtig als bei apflora.ch. Bei apflora.ch können nur so Beobachtungen dieser anderen Synonyme/Unterarten auch beim namensgebenden Taxon zugeordnet werden. Ähnliche Funktionalitäten gibt es bei vermehrung nicht.

Daher wäre es bei vermehrung.ch auch möglich, direkt auf die neue Taxonomie (DB-Taxref = Checklist) zu wechseln. 

FALLS alle bisher erfassten Taxa eindeutig einem Taxon dieser neueren Taxonomie zugeordnet werden können.

**Comment by barbalex** [comment]
Auch der reine Wechsel zur neueren Taxonomie bringt einige Stunden Aufwand und müsste daher finanziert werden.

**Comment by Seraina1** [comment]
Ok, danke für die Ausführung und den Hinweis! Mir war das so gar nicht bewusst.
Dann denke ich ist es sicher sinnvoll auch die neue Taxonomie zu wechseln. Je nachdem, welche neuen Aktionsplanart zukünftig kommen, ist es sicher gut, wenn wir hier auf dem aktuellen Stand sind.

**Comment by barbalex** [comment]
Vorgehen:
1. Verbindung (foreign table) zu arteigenschaften.ch bauen
2. Neues Feld in Tabelle `ae_art`: taxonomie
3. Dieses Feld mit `SISF (2005)` aktualisieren
4. Daten von `DB-TAXREF (2017)` aus arteigenschaften in `ae_art` ergänzen
5. Abfrage entwickeln, welche dem alten Taxon das neue zuordnet
6. Manueller Zwischenschritt, wenn hier einige der ca. 190 Taxa nicht eindeutig zuordbar sein sollten
7. In Tabelle `art` die ae_id mit der neuen ersetzen
8. Tabelle `ae_art`: Datensätze von `SISF (2005)` entfernen

**Comment by barbalex** [comment]
Habe soeben gemerkt: Wir können nicht "nur" auf die neue Version wechseln. 

Grund: Die FNS hat nie auf meine Fragen und Vorschläge reagiert, wie beim Übergang von der alten auf die neue Taxonomie mit von der FNS selber geschaffenen Taxa umgegangen werden soll.

Darum gab es kein Budget für eine durchdachte Variante.

Die behelfsmässige ist, zusätzliche Taxa weiterhin in der alten Taxonomie zu ergänzen.

Das ist ein weiterer Grund, wieso apflora multi-Taxonomie-fähig gebaut wurde (der Hauptgrund ist dort, dass Beobachtungen aus allen Taxonomien verarbeitet werden sollen).

Ich muss also vermehrung.ch so ändern, dass es mit mehreren Taxonomien umgehen kann.

Das bedingt unter anderem, dass dem eigentlichen Taxon-Namen der Name der Taxonomie vorangestellt wird, wie in apflora.ch.

Das gibt mehr Arbeit für die Implementation - schliesslich wäre der Ersatz die einfachere und daher schnellere und günstigere Variante gewesen.

Ich denke das mal durch und prüfe, ob die Anpassung mehr Budget benötigt.

**Comment by barbalex** [comment]
Ergänzung zum oben gesagten: Es gibt sogar Aktionsplan-Taxa, die von der FNS selbst ergänzt werden, z.B. Characeen.

**Comment by barbalex** [comment]
Ist in Version 1.10.0 implementiert.

Falls die Taxonomie nicht angezeigt wird, musst du ev. ab- und wieder anmelden.

8 von 157 Arten haben noch Taxa, deren Taxonomie SISF (2005) ist. Das sind diejenigen, die gemäss DB-Taxref (2017) kein Synonym eines DB-Taxref-Taxons sind.

Die Nitella's gibt es in der DB-Taxref nicht (doch, eigentlich schon, aber Info Flora hat sie uns nicht geliefert...). Die übrigen kannst du anschauen. Ev. findest du in der DB-Taxref Taxa, die übereinstimmen und kannst sie damit ersetzen. Bei Armeria alpina habe ich den Eindruck, dass es das gibt. Die übrigen habe ich nicht selber geprüft.

Du musst sie nicht durch das entsprechende Taxon in der aktuellen Taxonomie ersetzen. Aber es wäre wohl langfristig schon besser.

Hier die Liste mit den 157 Arten und aus welcher Taxonomie ihr Taxon stammt: [art_taxonomie.xlsx](https://github.com/barbalex/vermehrung/files/11470277/art_taxonomie.xlsx)
