### ISSUE TITLE
Dauerhaftes Laden neuer Formulare

### ISSUE THREAD

**Issue by Seraina1** [barbalex/vermehrung#120]
<img width="1874" alt="Bildschirmfoto 2023-04-11 um 13 52 20" src="https://user-images.githubusercontent.com/81672429/231154902-54957400-da6a-4c28-b9c8-c0d1e9e6de9e.png">

Seit letzter Woche ist es nicht mehr möglich neue Einträge zu erstellen, da das Formular immer am laden ist. 
Die ist auch nicht nur bei mir, sondern auch bei anderen Artverantwortlichen beobachtet worden.

Könnte dies damit zusammenhängen, dass du gerade im Hintergrund Anpassungen an der Datenbank am vornehmen bist?

**Comment by barbalex** [comment]
Wann hat es für dich das letzte Mal funktioniert?

**Comment by barbalex** [comment]
Wenn du einen neuen Datensatz schaffst, legt vermehrung ihn an und navigiert dann zu diesem Datensatz. Offenbar ist der noch nicht verfügbar oder falsch referenziert, das muss ich korrigieren.

Vorläufig musst du: 
- Wenn die Sanduhr kommt, zum nächsthöheren Ordner navigieren
- F5 bzw. neu laden
- zum neuen Datensatz navigieren und arbeiten

**Comment by barbalex** [comment]
Habe den Fehler gefunden. Bin am reparieren

**Comment by barbalex** [comment]
Ist in Version 1.3.73 repariert.

Grund war Unterhalt, der überraschende Nebenwirkung hatte. Danke für die Meldung und bitte entschuldige das Problem.

**Comment by Seraina1** [comment]
Vielen Dank für das rasche Beheben!

Lieber Gruss

----------------------------------------------------------------
Seraina Nuotclà

topos Marti & Müller AG
Ökologische Beratung
Idastrasse 24, 8003 Zürich
Anwesend: Mo-Do
Tel.: 044 451 52 55
Natel: 079 558 30 51
E-Mail ***@***.******@***.***>




Von: Alexander Gabriel ***@***.***>
Antworten an: barbalex/vermehrung ***@***.***>
Datum: Dienstag, 11. April 2023 um 15:05
An: barbalex/vermehrung ***@***.***>
Cc: Seraina Nuotclà ***@***.***>, Author ***@***.***>
Betreff: Re: [barbalex/vermehrung] Dauerhaftes Laden neuer Formulare (Issue #120)


Ist in Version 1.3.73 repariert.

Grund war Unterhalt, der überraschende Nebenwirkung hatte. Danke für die Meldung und bitte entschuldige das Problem.

**Comment by Seraina1** [comment]
Wie es gerade erscheint, scheint es immer noch nicht zu funktionieren. Auch nicht mit deiner Anleitung weiter oben. 

> Wenn du einen neuen Datensatz schaffst, legt vermehrung ihn an und navigiert dann zu diesem Datensatz. Offenbar ist der noch nicht verfügbar oder falsch referenziert, das muss ich korrigieren.
> 
> Vorläufig musst du:
> 
> * Wenn die Sanduhr kommt, zum nächsthöheren Ordner navigieren
> * F5 bzw. neu laden
> * zum neuen Datensatz navigieren und arbeiten

Kannst du es dir nochmals ansehen?

**Comment by barbalex** [comment]
Hast du Version 1.3.73 und es funktioniert nicht? Bei mir funktioniert es auch bei ziemlich vielen Tests.

**Comment by Seraina1** [comment]
Ja, auch mit der neuen Version. Habe gerade aber bemerkt, dass es nur das eine Formular ist. Scheinbar ist das irgendwie "hängen" geblieben... Nun funktioniert aber alles :)
