### ISSUE TITLE
Attributtabelle einer Zählung

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#2]
Die Attributtabelle einer Zählung muss nochmals überarbeitet werden und kann allenfalls so ergänzt werden, dass die Informationen für die Gartenanlage in Wangen (kasten, beet, nr, instruktion) auch in der Zählung (statt im Inventar - siehe auch Issue 1) enthalten sind. Da diese Attribute nur für die Gartenanlage nötig sind, stellt sich die Frage ob es grundsätzlich möglich ist, diese bei anderen Gärten auszublenden. Falls nicht (oder nur mit grossem Aufwand) kann man auch in Textform ergänzen, dass diese Felder nur für die Gartenanlage in Wangen ausgefüllt werden müssen. 

Allgemein ist bei der Zählung zudem ein Attributfeld nötig, welches bei der Einheit eine grössere Flexiblität zulässt. So muss eine nummerische Zahl eingegeben werden können und gleichzeitig mit einer Dropdownliste eine Einheit dafür ausgewählt werden können (z.B. 9erTöpfe, 8erTöpfe, Rosentöpfe, Pflanzen, Saatschalen ect.). Spezialfall Saatschalen: Die Angaben zur Anzahl der Saatschalen alleine sind nicht so sehr aussagekräftig. Hier bräuchte es eine zusätzliche Spezifikation: z.B. gekeimt, dicht, locker. Wir sind uns nicht sicher, wie dies am Besten eingebaut werden könnte. Allenfalls müsste diese Einheit nochmals separat (ähnlich wie Mutterpflanzen) aufgeführt werden.

**Comment by barbalex** [comment]
Flexibilität bei der Einheit heisst: Es können keine Summen gebildet werden. Das kennen wir schon von apflora. Wenn Summen gerechnet werden sollen, müsst ihr euch ein einfaches System ausdenken.

Es ist VIEL einfacher, flexibler und günstiger, eine Anleitung zu schreiben und nachzuführen, als eine Anwendung zu programmieren, welche so viele Begriffe verwendet, dass ihr dann wieder eine Anleitung schreiben müsst, welche diese Begriffe (Einheiten) erklärt.

Wenn ihr Zählungen summieren und vergleichen können wollt, müsst ihr dafür ein klares Konzept haben. Ansonsten erfasst die Anwendung einfach viele Zeilen mit Text, der nur von Menschen angeschaut werden kann.

Ich würde grundsätzlich nur so viele Zahlenfelder erfassen, wie es Kategorien gibt, die ihr summieren und auswerten können wollt.

Für alles andere macht man besser eine Liste aus Textfeldern.

**Comment by barbalex** [comment]
Was heisst Flexibilität genau?

- Es gibt eine abschliessende Liste von Einheiten (tiefe Komplexität)
- Es können jederzeit neue Einheiten gebildet werden (sehr hohe Komplexität)
- Es können jederzeit neue Kombinationen von Menge, Einheit und Methode (z.B. gekeimt/dicht/locker oder gezählt/geschätzt) gebildet werden (extrem hohe Komplexität)

Die viel höhere Komplexität hat folgen:
- Auswertungen, welche Zahlen summieren sind viel aufwändiger und inhaltlich unzuverlässig (funktioniert nur, wenn die Zählungen mit den korrekten Einheiten und Methoden erfasst wurden)
- Die Benutzeroberfläche wird viel komplexer: Man kann nicht mehr einfach eine Zahl in einem Feld in einer Tabelle einfügen. Es braucht multiple zwei- oder drei-Felder-Kombinationen
- Entwicklungs- und Unterhaltsaufwand steigen stark
- Für Auswertung und Darstellung wird viel mehr Leistung beansprucht

Ich glaube wir sollten unbedingt eine Lösung suchen, welche es ermöglicht, eine abschliessende Liste von Einheiten zu definieren. Bei der man allenfalls auswählen kann, welche dieser Einheiten angezeigt werden.

**Comment by barbalex** [comment]
Grundsätzlich ist die Funktion des Zählens ja gedacht, um planen zu können. 

Was genau wird aufgrund der Inventare geplant?

Das muss auf einigen Grundwerten basieren. Bisher waren das nach meinem Verständnis:
- anz_pflanzen
- anz_mutter_pflanzen
- anz_nicht_auspflanzbereit
- anz_auspflanzbereit
- anz_bluehende

Wir sollten definieren, wofür jeder dieser Werte gebraucht wird. Und davon ableiten, wie er erfasst wird.

Wenn ich mal ganz frech bin (weil ich davon zuwenig verstehe) und um die Diskussion zu lancieren platziere ich einfach mal diese Liste:
- anz_pflanzen: Interessant als Übersicht
- anz_mutter_pflanzen: Wichtig, um zu wissen, ob die genetische Grundlage ausreicht bzw. um Sammlungen zu planen
- anz_nicht_auspflanzbereit: Vermutlich nicht so wichtig und ev. = anz_pflanzen - anz_auspflanzbereit
- anz_auspflanzbereit: Wichtigste Zahl: Planen, wie viele Pflanzen ausgesetzt werden können. Kern-Kompetenz dieser Anwendung
- anz_bluehende: Interessant. Wozu wichtig? Abschätzen, wie sich die Pflanzen vermehren?

Bei den wichtigen Begriffen (anz_pflanzen, anz_mutter_pflanzen, anz_auspflanzbereit, ev. weitere) wäre es auch wichtig, sie genau zu definieren. 

Das mag jetzt etwas trocken und mühsam erscheinen. Aber wir bauen darauf einen grossen und zentralen Teil der App auf, der bestimmt, wie nützlich die App für die Planung von Sammlungen und Aussetzungen ist.

**Comment by barbalex** [comment]
9erTöpfe, 8erTöpfe, Rosentöpfe, und Saatschalen beschreiben doch, in welcher Art die Pflanzen, Mutterpflanzen, auspflanzungsbereiten Pflanzen momentan vorkommen.

Das hat eigentlich nichts damit zu tun, zu wissen, wie viele Pflanzen, Mutterpflanzen, auspflanzungsbereite Pflanzen momentan vorkommen und wie Auspflanzung bzw. Sammlung geplant werden kann, oder?

Es gleicht viel mehr den Kästen, Beeten und Nummern, mit denen grosse Kulturen organisiert werden.

Anders gesagt: Man würde doch kaum Pflanzen, Mutterpflanzen, auspflanzungsbereite Pflanzen in diesen Kategorien erfassen.

Vermutlich würde man eher mitteilen, dass jetzt diese Kategorien zum Abholen bereit stehen. Damit wäre wir bei der Lieferung, nicht mehr bei der Zählung.

**Comment by barbalex** [comment]
Bei der Lieferung ist eine Angabe von Mengen auch vorgesehen. Ist es vorgesehen, Lieferungen auszuwerten?

Würde man das Jahr Planen, indem man Lieferungen berücksichtigt, müsste man wohl für Lieferung dieselben Einheiten verwenden wie für die Zählung. Damit könnte man theoretisch für jeden Zeitpunkt die Anzahlen pro Garten unter Berücksichtigung von geplanten Lieferungen kennen.

Man könnte dann in einem separaten Textfeld beschreiben, in welcher Form diese Anzahlen geliefert wurden (9erTöpfe, 8erTöpfe, Rosentöpfe, Saatschalen...). Denn das ist vermutlich reine Info und wird nicht ausgewertet.

Ich würde daher 9erTöpfe, 8erTöpfe, Rosentöpfe, Saatschalen etc. als Liefereinheiten bzw. Verpackungseinheiten bezeichnen. Und vermutlich muss die Anwendung sie gar nicht kennen, weil sie nie ausgewertet werden.

Im Gegensatz dazu wären anz_pflanzen, anz_mutter_pflanzen, anz_auspflanzbereit Zähleinheiten, die für die Planung verwendet werden.

**Comment by barbalex** [comment]
Zu anz_mutter_pflanzen: Diese Zahl dient doch dazu, die genetische Vielfalt einer Kultur darzustellen?

Falls das so ist, ist das nicht eine Zahl, die im Rahmen einer Zählung gezählt wird. Sondern im Rahmen einer Sammlung ("von_anzahl_individuen"). Und in der Lieferung dokumentiert werden sollte. Und auf Ebene Kultur nachgeführt werden sollte.

Oder hat diese Zahl eine andere Funktion, die ich nicht verstanden habe?

**Comment by barbalex** [comment]
Zählungen wurden gemäss der letzten Besprechung umgesetzt
