### ISSUE TITLE
Sammel-Lieferungen, Konzept

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#21]
### 1	Ziel
- Lieferscheine mit mehreren Einzelpositionen ermöglichen
- Mehrfache Lieferungen effizienter erfassen

### 2	Benutzer-Erlebnis
- :heavy_check_mark: Benutzer wählt "Neue Sammel-Lieferung" (im Ast im Baum)
- :heavy_check_mark: Vorlage öffnet sich (rechts vom Baum). Vorlage ist genau das Lieferungs-Formular. Sammel-Lieferungs-Label im Baum zeigt erst ID an.
- :heavy_check_mark: Benutzer füllt in der Vorlage alles aus, was in allen (Teil-)Lieferungen gleich ist
- :heavy_check_mark: Sammel-Lieferungs-Label im Baum zeigt nun Daten aus der Vorlage (Datum, von, Person)
- :heavy_check_mark: Benutzer fügt Lieferungen hinzu. Dabei werden die Daten aus der Vorlage übernommen
- :heavy_check_mark: Vorlage bleibt sichtbar, rechts der Lieferung. :heavy_check_mark: Benutzer kann das abwählen
- :heavy_check_mark: Lieferungen zeigen nur Felder, die in der Vorlage noch nicht ausgefüllt sind
- :heavy_check_mark: Benutzer kann wählen, alle Felder anzuzeigen
- :heavy_check_mark: Bei allen (Teil-)Lieferungen von Sammel-Lieferungen wird die Sammel-Lieferung angezeigt. :heavy_check_mark: Der Benutzer kann dieses Verhalten steuern
- :heavy_check_mark: Benutzer kann Daten der Vorlage nachträglich in einzelne Lieferung übernehmen
- :heavy_check_mark: Benutzer kann Daten der Vorlage nachträglich in alle Lieferungen übernehmen
- Eventuell: Benutzer kann wählen, bei Änderungen der Sammel-Lieferung immer automatisch alle Lieferungen zu aktualisieren
- Benutzer kann Sammel-Lieferung drucken
- Eventuell: Benutzer kann auch Einzel-Positionen drucken (in allen Lieferungs-Formularen)

### 3 Strukturelle Umsetzung
- :heavy_check_mark: Neue Tabelle "sammel_lieferung". Mit Feldern "id" und allen wesentlichen Feldern aus der Tabelle "lieferung"
- :heavy_check_mark: Neues Feld in Tabelle "lieferung": "sammel_lieferung_id"

**Comment by barbalex** [comment]
siehe https://vermehrung.apflora.ch/Dokumentation/Benutzer/Sammel-Lieferungen

**Comment by jmenzi** [comment]
Müssen wir nochmals grundlegend besprechen - bringt in der jetzigen Form keinen Mehrnutzen. Das Problem liegt in der starren Definition der Lieferungen. Eine Lieferung kann nur von einer Sammlung in eine Kultur gemacht werden oder von einer Kultur in eine andere. Dies wäre grundsätzlich kein Problem, nur macht es die Erfassung von Sammellieferungen eigentlich unmöglich. 

Eine Sammellieferung hat zum Zweck Informationen zur Lieferung: Datum, Von wo nach wo, liefernde Person nur einmal bei der Sammellieferung zu erstellen. Basierend auf diesen Informationen kann ich dann Arten zu der Sammellieferung hinzufügen und für diese artspezifische Angaben ergänzen (Menge, von Anzahl Individuen, Topfgrösse ect.). 

So wie die Sammellieferung sich jetzt präsentiert ist sie eher darauf ausgerichtet eine Art in mehrere Kulturen zu liefern. Ich bin mir nicht sicher, ob die oben gewünschte Sammellieferung in der ZV-DB überhaupt umsetzbar ist, da ich ja für jede Art einzeln eine artspezifische Kultur im Zielgarten definieren muss! Dieser Schritt müsste wegfallen. 

Im Moment ist der einzige Nutzen der Sammellieferung, dass ich die Lieferungen an einem Ort erfassen kann. Ohne Sammellieferung müsste bei jeder Art einzeln die Lieferung erfassen, oder?
