### ISSUE TITLE
offline Daten-Erfassung

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#29]
@kmarti @rebeccakurz @wunderli @jmenzi 

Ich habe in den letzten Tagen viel überlegt und recherchiert.
Und werde noch mehr Zeit an den Grundlagen überlegen, bevor ich mit der Umsetzung beginne.

Ausser, dass ich in vermehrung.ch einige Voraussetzungen schaffen werde, bevor die Daten importiert werden. 

Aber ich glaube, es hat langsam Hand und Fuss: https://vermehrung.ch/Dokumentation/offline

Ihr könnt es gerne durchlesen, um eine Ahnung zu bekommen, worum es geht. Und warum es ziemlich aufwändig ist. Es wird aber auch richtig gut 🚀

**Comment by kmarti** [comment]
Mir ist nicht ganz klar, wozu und weshalb offline gearbeitet werden soll.

**Comment by barbalex** [comment]
Damit man zuverlässig auch im Feld bzw. Garten arbeiten kann. Weil das offline sein kann

**Comment by kmarti** [comment]
Ah, ja, alles klar!

**Comment by barbalex** [comment]
> Kann es sein, dass die Offline-Situation die Datenbank so verlangsamt?

Je nach Umständen und Vorgängen kann die Offline-Fähigkeit beschleunigen oder verlangsamen.

Grob gesagt:
- Beschleunigt werden Speicher-Vorgänge, weil die App nicht darauf warten muss, bis der Server die Verarbeitung einer Operation bestätigt hat
- Beschleunigt werden Vorgänge, bei denen Daten geladen werden müssten - weil sie schon vorhanden sind
- Verlangsamt wird die App beim Öffnen - weil sie alle Daten lädt. Das trifft v.a. Manager
- Verlangsamt wird die App, weil sie alles lokal verarbeiten muss. Und dabei nicht wie die Datenbank auf dem Server Indizes nutzen kann. Wenn es sehr viele Daten gibt, führt das zu hohem Rechenaufwand. Was bei Gärtnern somit nicht vorkommen sollte. Aber bei Managern schon
- Wie stark die App durch lokales Verarbeiten gebremst wird, hängt unter anderem davon ab:
  - wie stark der PC ist
  - wieviel dieser Leistung dem Browser verbleibt (was wird durch andere Apps beansprucht?)
  - wieviel dieser Leistung der Browser der App genehmigt (was wird durch andere Tabs beansprucht?)

**Comment by jmenzi** [comment]
Ja, ich denke die Verlangsamung beim Öffnen ist sehr sicher spürbar und erfordert geduldige User. Auch die lokale Verarbeitung verlangsamt meiner Meinung nach das Arbeiten als Manager stark - was viel Geduld erfordert. Dies ist insbesondere spürbar, wenn man neue Daten eingibt und erfasst (oder eben auch Herkünfte auswählen möchte). Ich bin nicht glücklich damit.
