### ISSUE TITLE
Wesentliche Funktionalität: Kulturübersicht

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#3]
Um einen Überblick über die einzelne Kultur zu erhalten wäre es nötig, dass die Informationen zu einer Kultur in einer Kulturübersicht dargestellt werden können (auch eine Art Tabelle?). Z.B. Zählungen verschiedener Daten, Kultur Events, (allenfalls auch Lieferungen, Sammlungen). Nur so kann auf einen Blick eine Übersicht über die Kultur erhalten. In der jetzigen Form muss man sehr viel Klicken um an die Informationen zu gelangen.

**Comment by barbalex** [comment]
Das tönt nach einer Darstellung, welche Daten für einen bestimmten Zweck möglichst übersichtlich darstellt. Die sollte jemand skizzieren, der weiss, wozu diese Auswertung benutzt werden wird.

Grundsätzlich eignet sich eine Tabelle eher schlechter dafür, als der realisierte Strukturbaum: Denn nicht jede Ebene enthält dieselben Felder. Ein Befehl "alle Knoten öffnen" wäre ev. ebenso gut.

Andere Darstellungen müssen pro Bereich Platz reservieren, damit es übersichtlich bleibt. Man kann aber nicht garantieren, dass in jedem Fall der für einen Bereich reservierte Platz auch ausreicht. Es braucht auch eine Strategie, was passiert, wenn der reservierte Platz nicht reicht.

Kannst du eine geeignete Darstellung skizzieren?

**Comment by barbalex** [comment]
Informationen gemäss Sitzung vom 26.6.2019:

- Garten
- Person
- Art
- herkünfte
- von anz ind
- datum erste anlieferung
- Datum letzte Lieferung
- aktuelle anzahlen mit Datum der Zählung
- Liste der Kulturevents, neueste oben
- Liste aller Zählungen mit Summen

**Comment by barbalex** [comment]
zurückgestellt um auf aktuell Prioritäres zu fokussieren
