### ISSUE TITLE
Auspflanzungen via GAW

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#35]
Der normale Ablauf einer Auspflanzung ist:

@jmenzi

- Garten liefert an GAW
- AV holt in GAW
- Für die GAW ist das normalerweise keine normale Kultur, sondern ein **Zwischenlager**
- Es kann vorkommen, dass die GAW mit einem Teil des Zwischenlagers eine neue Kultur gründet. Das wird in der App abgebildet, indem eine Lieferung vom Zwischenlager an diese Kultur erfasst wird

Damit das möglich ist, muss geändert werden:

- Dieselbe "Art aus Herkunft" muss nun in einem Garten zwei mal vorkommen können: Ein mal als normale Kultur. Und ein mal als Zwischenlager (darüber hinaus kann es beliebig viele inaktive Kulturen geben)
- Es gibt einen neuen Trigger: Wenn neue Sammlung entsteht: Gibt es diese Kombination von Art und Herkunft schon als Zwischenlager im GAW? Wenn nicht: anlegen
- Eine Abfrage legt für die existierenden Daten für alle Kombinationen von Art und Herkunft im GAW Zwischenlager an

**Comment by barbalex** [comment]
@jmenzi Ist umgesetzt. Aber es gibt ein paar Folge-Issues, an denen ich noch arbeite

**Comment by barbalex** [comment]
In v0.44.4:

- Kulturen sind in Listen als "Zwischenlager" beschrieben, wenn sie das sind
- In Filtern wird die Checkbox (Ja/Nein-Feld) als 3-Zustands-Box angezeigt: Ja, Nein, Unbestimmt. Sonnst kann nicht gezielt nach "Nein" (z.B. kein Zwischenlager) gefiltert werden

**Comment by barbalex** [comment]
Im Formular "Kultur" muss ich neu programmieren, welche Elemente zur Auswahl stehen, in den Feldern:

- Art
- Herkunft
- Garten

Das ist jetzt deutlich komplizierter, weil nun in einem Garten zwei statt einer Kulturen mit derselben Herkunft existieren können.

**Comment by barbalex** [comment]
@jmenzi

Es gab einen Fehler in der Sortierung von Kulturen. Das wurde u.a. im Navigationsbaum und in der Kultur-Liste sichtbar. Hat ev. zum Teil dazu geführt, dass Kulturen vermisst wurden - dabei waren sie einfach falsch sortiert.

Derselbe Fehler existierte auch bei anderern Listen. Wird mit v0.44.6 korrigiert.

**Comment by barbalex** [comment]
O.k., für mich jetzt i.O.

**Comment by jmenzi** [comment]
Bei Gelegenheit, kannst du auch für die Kultur "topos Kühlschrank" simultan zur GAW die Zwischenlager erstellen?

**Comment by barbalex** [comment]
Meinst du das hier?
- Es gibt einen neuen Trigger: Wenn neue Sammlung entsteht: Gibt es diese Kombination von Art und Herkunft schon als Zwischenlager im topos Kühlschrank? Wenn nicht: anlegen
- Eine Abfrage legt für die existierenden Daten für alle Kombinationen von Art und Herkunft im topos Kühlschrank an
