### ISSUE TITLE
Herkunft kann nicht gewählt werden

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#36]
@jmenzi

Beispiel:

- bei Barbara Zollinger
- Campanula cervicaria
- Herkunft ZHHK1051.750 N. Wolau

**Comment by barbalex** [comment]
Das Beispiel kann jetzt gewählt werden

**Comment by jmenzi** [comment]
Es sind noch weitere solche Beispiele aufgetreten. Z.B. unter der Art Liparis, wenn ich hier eine Sammlung erstellen will, kann man keine Herkunft auswählen.

**Comment by barbalex** [comment]
Wenn ich ein Sammlung von Liparis öffne kann ich eine Herkunft wählen. Wie kann ich dieses Beispiel nachvollziehen?

**Comment by jmenzi** [comment]
Jetzt funktioniert es bei mir auch wieder. Scheint ein sporadisch an unterschiedlichen Orten aufzutauchendes Problem zu sein. Ist für mich damit aber noch nicht gelöst oder abgeschlossen, da der Fehler weiterhin plötzlich auftauchen kann und dann wieder verschwindet.

**Comment by jmenzi** [comment]
Leider auch hier noch nicht ganz geregelt. Folgende Beispiele funktionieren bei uns weder bei Evelyn noch bei mir:

![Bildschirmfoto 2020-10-20 um 09 53 53](https://user-images.githubusercontent.com/6448181/96569210-2695a580-12c9-11eb-8a37-5cd5c9988197.png)
![Bildschirmfoto 2020-10-20 um 09 53 10](https://user-images.githubusercontent.com/6448181/96569219-29909600-12c9-11eb-99d3-1489a3b0e06f.png)

Auch können wir bei diesem Beispiel die Art nicht auswählen:
![Problem_ZV_Eingabe_Daten_2](https://user-images.githubusercontent.com/6448181/96569314-462cce00-12c9-11eb-9a74-854e93baa1a8.png)

**Comment by barbalex** [comment]
Zum Fall von Ballota nigra: Gemäss dem printscreen gibt es keine Sammlungen. Also kann man logischerweise auch keine Herkunft wählen. Denn die Art wurde in keiner Herkunft gesammelt.

Zum Fall von Orchis:

- ich nehme an, du wolltest Orichs coriophora wählen, weil das die einzige Art ist, die erfasst wurde
- Für Orchis coriophora gibt es keine Sammlungen
- Im Kulturen können nur Arten gewählt werden, für die es gesammelte Herkünfte gibt. Es macht keinen Sinn, hier Arten zu wählen, die nie gesammelt wurden. Das ist dokumentiert, wenn du im Kultur-Formular auf das i-Symbol klickst: https://vermehrung.ch/Dokumentation/Kulturen#formular

**Comment by jmenzi** [comment]
Klar... Sorry wir waren verwirrt, da es bereits Datensätze drin hatte, welche offenbar importiert wurden. Aber macht Sinn.

**Comment by jmenzi** [comment]
<img width="1671" alt="Bildschirmfoto 2020-12-07 um 10 41 12" src="https://user-images.githubusercontent.com/6448181/101334889-be9b1e80-3878-11eb-8966-b5cb7371460b.png">

Leider tritt der Fehler hier nochmals auf. Im Botanischen Garten (BoGa) kann ich die Herkunft Hirzel für Typha shuttleworthii nicht auswählen.

**Comment by barbalex** [comment]
Wieso willst du das in einer nicht aktiven Kultur machen?

**Comment by jmenzi** [comment]
Bei mir ist sie aktiv. Aber ja, sie sollte anschliessend wieder inaktiv gesetzt werden. Die Lieferung, welche ich erfassen möchte, war die letzte. Danach wurde die Kultur beendet. Trotzdem muss ich dies erfassen. Bei mir habe ich die Kultur aber bereits für die Eingabe auf aktiv gesetzt.

**Comment by barbalex** [comment]
Na ja, ist ziemlich einfach: es gibt keine Sammlungen dieser Art im Hirzel

**Comment by jmenzi** [comment]
Aber in der Gartenanlage ist diese Kultur vorhanden - auch ohne Sammlung. Die Herkunft ist ja erfasst?

**Comment by jmenzi** [comment]
Aber ja, ich muss eine Sammlung erfassen - alles klar. Vermutlich war das möglich wegen dem Import am Anfang.

**Comment by barbalex** [comment]
Genau 👍
