### ISSUE TITLE
Strukturbaum stellt falsche Daten dar

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#37]
@jmenzi

Es kommt vor, dass der Strukturbaum falsche Daten anzeigt. Zum Beispiel Mehrfache.

Bitte meldet mir hier Beispiele, die ich nachvollziehen bzw. provozieren kann. Damit ich hoffentlich den Fehler beheben kann.

Provisorische Umgehung, wenn der Fehler auftritt: App neu laden. Wenn das nicht reichen sollte: Daten und Einstellungen zurücksetzen (Menü beim Klick auf das Personen-Symbol oben rechts).

**Comment by jmenzi** [comment]
Zum Teil werden keine Daten angezeigt, wenn ich Elemente des Strukurbaumes versuche aufzuklappen. Der Pfeil sieht dann so aus, als wäre es aufgeklappt, es wird aber nichts angezeigt. Neuladen hilft aber immer und dann geht es wieder.

**Comment by jmenzi** [comment]
Auch Evelyn hat diesen Fehler mehrmals gehabt. Es tritt vor allem auf, wenn man längere Zeit an der DB arbeitet - wirklich provozieren kann man den Fehler nicht, da es eher zufällig passiert. 

Sie hat aber herausgefunden, dass die Daten dann innerhalb der gleichen Hierarchiestufe an einem anderen Ort angezeigt werden. Es wirkt dann am eigentlichen Ort so, als wäre nichts mehr vorhanden - die Daten werden aber einfach an einem falschen Ort innerhalb des Strukturbaumes angezeigt.

**Comment by jmenzi** [comment]
Der Fehler tritt sehr häufig auf.

**Comment by barbalex** [comment]
Ich frage mich, ob das mit euren Leistungs-Problemen zusammenhängt. Was hier passiert, ist dass die Knoten im Strukturbaum nicht richtig sortiert werden. Wenn die App vom System zuwenig Leistung erhält, wird einfach nicht sortiert. Bzw. die bestehende Sortierung nicht aktualisiert.

Oder es ist einfach ein Fehler in der Sortierung der Knoten, der nur unter bestimmten Umständen auftritt.

**Comment by jmenzi** [comment]
![Bildschirmfoto 2020-09-29 um 11 05 50](https://user-images.githubusercontent.com/6448181/94538127-e734e580-0243-11eb-8a51-5c496080e627.png)
Die heutige Lieferung von Trifolium ochroleucon wird bei Viola angezeigt. Ein Beispiel für diesen doch häufig auftretenden Fehler.

**Comment by jmenzi** [comment]
Nach Neuladen wird es wieder korrekt dargestellt: 
![Bildschirmfoto 2020-09-29 um 11 08 28](https://user-images.githubusercontent.com/6448181/94538298-24997300-0244-11eb-80d2-54aa584129a2.png)

**Comment by barbalex** [comment]
Hm. Der Garten von Heinz Sommer wird bei mir verborgen, wenn ich einstelle, inaktive Gärten, Kulturen und Personen zu verbergen.

Das sollte nicht sein, weil:
- Heinz Sommer ist als Person aktiv gesetzt
- Der Garten, der nach ihm benannt ist, ist aktiv gesetzt
- die zwei Kulturen sind auch aktiv gesetzt

Aus Angst, dass ich etwas völlig Blödes übersehen habe: Siehst du die drei Punkte oben auch so?

Der Fehler in der Sortierung im Navigationsbaum könnte einen Zusammenhang mit der Einstellung, inaktive zu verbergen, haben.

**Comment by jmenzi** [comment]
Ja, alles ist aktiv geschaltet. Der Fehler tritt eigentlich nach Eingaben auf. Ich vermute deshalb einen Zusammenhang mit einer Eingabe und dem allfälligen Upload von Offline nach Online?

**Comment by barbalex** [comment]
Übrigens: Danke für das Bild beider Zustände. Das macht die Sache viel klarer. Jetzt müsste ich es nur noch provozieren können.

**Comment by barbalex** [comment]
In Version 0.47.16 ist https://github.com/barbalex/vermehrung/issues/52 korrigiert. Bitte halte ein Auge offen, ob sich die Situation verbessert. Ich kann mir vorstellen, dass das Einfluss hatte.

**Comment by barbalex** [comment]
Du musst in der neuen Version den Filter, um inaktive auszublenden, neu setzen. Sonst bleibt die alte Einstellung. Korrigiert ist der Wert, der gesetzt wird, wenn man den Filter wählt:
<img width="351" alt="2020-09-29_12h15_09" src="https://user-images.githubusercontent.com/669783/94546156-cb364180-024d-11eb-8ef7-50df53174b95.png">

**Comment by barbalex** [comment]
Jetzt, wo sich bezüglich verknüpfter Daten und auch der Leistungsfähigkeit einiges geändert hat, interessiert es mich, ob das immer noch passiert. Bitte meldet wieder.

**Comment by jmenzi** [comment]
Leider kommt der Fehler immer noch vor. Ein aktuelles Beispiel: 
![ZV-DB_Problem_mit_Aufklappen](https://user-images.githubusercontent.com/6448181/96568930-cd2d7680-12c8-11eb-8a77-b21cc3d80dae.JPG)

**Comment by barbalex** [comment]
Version 1.0.0 ist live. Mit anders aufgebautem Navigationsbaum. Bitte Fehler in neuem issue melden.
