### ISSUE TITLE
Export für die jährliche Bedarfsplanung

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#38]
@jmenzi

- Liste von Art/Herkunft-Kombinationen
- Letzte Zählung entweder aus den Diagrammen bei der Art oder im Export
- AV erfassen dort pro Herkunft ihren Bedarf
- Jasmin generiert daraus Anpflanzungen (Lieferung an Auspflanzung)

Wir vor Weihnachten benötigt. Soll davor nochmals spezifiziert werden.

**Comment by jmenzi** [comment]
Lieber Alex

Vielen Dank für die schnelle Umsetzung des Exportes Lieferungen. Bei der Durchsicht des Exportes sind mir folgende Dinge aufgefallen: Bei Lieferungen aus einer Kultur, fehlen die Angaben zur Herkunftskultur. Bei Lieferungen aus einer Sammlung sind diese Felder aber per Definition leer.

Wo finde ich den Export für die Bedarfsplanung? Ist dieser schon implementiert?

**Comment by barbalex** [comment]
> Bei Lieferungen aus einer Kultur, fehlen die Angaben zur Herkunftskultur

Da gab es einen Fehler. Ist in Version 0.52.1 korrigiert

> Wo finde ich den Export für die Bedarfsplanung

Ist jetzt umgesetzt, siehe email

>
