### ISSUE TITLE
Wesentliche Funktionalität: Export- und Druckfunktion

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#4]
Es ist sehr wichtig, dass die Datenbank auch eine Möglichkeit erhält z.B. ein Inventar oder eine Kulturübersicht (siehe Issue 3) zu exportieren oder gar direkt zu drucken. Zudem wäre es auch wünschenswert, dass eine Art Formular (leeres Inventar pro Garten) aus der Datenbank generiert werden kann, in welches die Vermehrer ihre Kulturdaten (Zählungen) eintragen können (falls sie nicht online eintragen wollen/können).

**Comment by barbalex** [comment]
O.k., müssen wir noch definieren

**Comment by barbalex** [comment]
Wäre das leere Inventar für die meisten Gärten gleich? Dann wären das Vorlage(n), die in der Anwendung hoch- und runter geladen werden können.

Und/oder muss die interen Organisation von Kästen/Beeten dargestellt werden? Dann brauche ich eine Vorlage dafür und muss das programmieren.
