### ISSUE TITLE
Bei Einloggen - keine Daten

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#40]
Wenn sich unsere Praktikantin anmeldet, werden zuerst keine Daten angezeigt. Erst nach "Daten neu laden" erscheinen die Daten. Damit hatte ich mit dem Account Jasmin Menzi aber keine Probleme.

**Comment by barbalex** [comment]
Wenn das systematisch passiert: kannst du mir bitte Benutzer und Passwort via einen sicheren Weg (z.B. Whatsapp) übermitteln? Damit ich versuchen kann, das nachzuvollziehen?

**Comment by jmenzi** [comment]
Ich habe nun für Edith Eugster (Gärtnerin) ein Log-in erstellt. Leider kann sie ihre Pflanzen nicht sehen. Frage sie nach einem Screenshot.

**Comment by barbalex** [comment]
Wie gesagt: Nützlich wäre Benutzer und Passwort. Damit ich versuchen kann, es nachzuvollziehen

**Comment by jmenzi** [comment]
Evelyn wird dir das Morgen zuschicken.

[signature_683649233]

Von: Alexander Gabriel <notifications@github.com>
Antworten an: barbalex/vermehrung <reply@reply.github.com>
Datum: Dienstag, 22. September 2020 um 15:21
An: barbalex/vermehrung <vermehrung@noreply.github.com>
Cc: Jasmin Menzi <menzi@toposmm.ch>, Author <author@noreply.github.com>
Betreff: Re: [barbalex/vermehrung] Bei Einloggen - keine Daten (#40)


Wie gesagt: Nützlich wäre Benutzer und Passwort. Damit ich versuchen kann, es nachzuvollziehen

**Comment by barbalex** [comment]
> Leider kann sie ihre Pflanzen nicht sehen

Die Fehlermeldung sagt, dass eine Operation nicht in die Datenbank geschrieben werden kann. Der Name der Operation weist darauf hin, dass Edith Eugster eine Art schaffen wollte. Das Cloud-Symbol oben rechts zeigt an, dass es drei Operationen gibt, welche scheitern.

Das Problem ist: Sie ist weder Managerin noch bei einer Art mitarbeitend. Sondern bei einem Garten. **Daher fehlen ihr die Rechte, um eine Art zu ändern oder gar zu schaffen**. Die Situation ist hier dokumentiert: https://vermehrung.ch/Dokumentation/Konten (diese Doku liesse sich bestimmt noch verbessern).

Die Fehlermeldung ist etwas unglücklich. Ich muss schauen, ob ich das verbessern kann. Sie sollte auf fehlende Benutzerrechte hinweisen.

Ebenso unglücklich ist, dass die von ihr ausgelöste Operation von jetzt an bei jedem Programmstart versuchen wird, sich auszuführen. Und jedes Mal wird die Datenbank sie verweigern, wegen fehlender Rechte. Das Problem dabei ist: Die Datenbank weiss genau, was welcher Benutzer darf. Die App aber nicht. Ich muss daher dafür sorgen, dass bei Fehlern, die aufgrund fehlender Rechte entstehen, die Operation direkt durch die App gelöscht wird.

Edith Eugster muss jetzt die Operationen löschen, die nicht ausgeführt werden können, weil sie nicht die nötigen Rechte hat. Am besten ist, sie klickt oben rechts auf das Wolken-Symbol und widerruft dann alle ausstehenden Operationen. Siehe hier: https://vermehrung.ch/Dokumentation/offline, beim Abschnitt "Sie können sich durch Klick auf das Online-Symbol auch die Schlange auflisten lassen".

**Comment by barbalex** [comment]
O.k., ich bin dem Fehler auf die Schliche gekommen: Bei eingeschränkten Rechten gab es in der Datenschnittstellen-Abfrage Fehler, weil gewisse Tabellen und Felder "nicht sichtbar" waren.

Ich habe die Rechte neu sorgfältig so formuliert, dass grundsätzlich alle Tabellen und Felder erreicht werden können, **wenn** gewisse Kriterien erfüllt sind.

Das tönt jetzt etwas komisch und so ist es mir auch vorgekommen. Wie es scheint, hat die Datenschnittstelle ihr Verhalten verändert, seit ich vor mehreren Monaten diese Funktionalität implementiert und getestet hatte.

Bitte probiert nun mit der neuen Version 0.47.15. Wenn noch etwas nicht ganz klappen sollte, probiert bitte:
1. einfach neu laden (F5-Taste oder app schliessen und öffnen)
2. den Befehl "Daten, Einstellungen und Anmeldung zurücksetzen" ein mal ausführen (er erscheint nach Klick auf das Personen-Symbol oben rechts, zweites Symbol von rechts)

**Comment by barbalex** [comment]
Korrektur: Edith soll doch bitte ein mal abmelden und dann wieder anmelden. vermehrung sollte dann die richtigen Daten anzeigen. Was beim ersten Mal noch nicht klappt: Werte aus Beziehungen werden z.T. noch nicht angezeigt. Dass stimmt dann ab dem nächsten mal neu Laden bzw. die App öffnen. Muss noch herausfinden, wie ich das hinkriege.

**Comment by jmenzi** [comment]
Lieber Alex, es sieht etwas besser aus, jedoch werden immer noch nicht alle Daten angezeigt. Teilweise handelt es sich wohl um eine Darstellungsfrage (Die Daten sind zwar erfasst und werden im Reiter auch angezeigt, jedoch im Strukturbaum nicht), teilweise sind die Daten aber auch einfach nicht drin (z.B. die Art fehlt). 
![Bildschirmfoto 2020-09-28 um 13 32 33](https://user-images.githubusercontent.com/6448181/94427452-61576280-018f-11eb-8333-3df1708b33fd.png)
![Bildschirmfoto 2020-09-28 um 13 32 43](https://user-images.githubusercontent.com/6448181/94427456-63212600-018f-11eb-9b2e-9c2415632032.png)
![Bildschirmfoto 2020-09-28 um 13 32 51](https://user-images.githubusercontent.com/6448181/94427457-64525300-018f-11eb-8f8c-7f671b33ed44.png)

**Comment by barbalex** [comment]
Das ist das von mir erwähnte Problem, dass Daten aus verknüpften Tabellen erst nach dem zweiten oder dritten Mal Laden/Öffnen der App angezeigt werden. Habt ihr probiert, zwei mal neu zu laden?

**Comment by jmenzi** [comment]
Einmal mit F5 und einmal mit dem Befehl. Nach zweimal neuladen, kommt zwar Edith, aber auch bei mehr neu laden, werden die Infos zur Art nicht angezeigt.

![Bildschirmfoto 2020-09-28 um 13 40 27](https://user-images.githubusercontent.com/6448181/94427947-2f92cb80-0190-11eb-8ba8-09988284e00c.png)

**Comment by barbalex** [comment]
O.k, werde mich dem nochmals widmen. Bin heute Nachmittag aber nicht mehr erreichbar

**Comment by jmenzi** [comment]
Aktuell werden bei mir auch  nach mehrmaligem Laden keine Kulturen im Strukturbaum unter Gärten angezeigt. 
![Bildschirmfoto 2020-09-29 um 10 23 17](https://user-images.githubusercontent.com/6448181/94532437-28c29200-023e-11eb-9087-010eb1d418ef.png)

**Comment by barbalex** [comment]
Bin leider an den Steuern. Die müssen bis Ende Monat gemacht werden. Mal schauen, was daneben noch geht...

**Comment by barbalex** [comment]
> Aktuell werden bei mir auch nach mehrmaligem Laden keine Kulturen im Strukturbaum unter Gärten angezeigt.

Das hat wohl einen anderen Grund: Denn die nächsten paar Gärten zeigen wirklich Kulturen an.

Beispiel Albert Blarer: `select * from kultur where garten_id = 'cc031650-b555-11ea-b3de-0242ac130004'` ergibt kein Resultat.
Beispiel Andreas Gigon: Dieser Garten ist inaktiv. Und darum in der Standardeinstellung nicht sichtbar.

**Comment by jmenzi** [comment]
Bei mir sind gar keine Kulturen sichtbar.

**Comment by barbalex** [comment]
Also z.B. auch nicht bei Andreas Keel?

**Comment by barbalex** [comment]
Wenn das so ist: Setz bitte mal alle Daten, Einstellungen und die Anmeldung zurück:
<img width="491" alt="2020-09-29_10h48_41" src="https://user-images.githubusercontent.com/669783/94535330-c1a6dc80-0241-11eb-8513-373ba88fb72b.png">

**Comment by jmenzi** [comment]
Andreas Keel wird bei mir gar nicht angezeigt.

Jetzt verstehe ich was los ist. Offenbar hat es den Filter nicht gelöscht beim Neuladen der Daten. Ich hatte bei den Kulturen den Filter von heute Morgen noch drin. Dieser ist geblieben auch nach dem Neuladen der Daten sowie dem An- und Abmelden. Allenfalls wäre es gut den Filter auch zu resetten, wenn man die Daten neu läd oder sich ausloggt?

**Comment by barbalex** [comment]
Es gibt zwei ganz bewusst verschieden genannte Varianten, die Daten neu zu laden:

- "Daten neu laden": setzt die lokalen Einstellungen und die Anmeldung _nicht_ zurück
- "Daten, Einstellungen und Anmeldung zurücksetzen": setzt auch die lokalen Einstellungen und die Anmeldung zurück

Offenbar ist das zu wenig klar formuliert, wenn man nicht wie ich eh schon weiss, was der Unterschied ist?

**Comment by jmenzi** [comment]
Ok, nein. Das sollte klar sein. Aber beim Neu-Einloggen den Filter auf 0 stellen, wäre schon gut, oder? Man kann sich allenfalls nicht mehr erinnern, dass man bei der letzten Anmeldung einen Filter gesetzt hatte (Offenbar sogar am gleichen Morgen nicht mehr...).

**Comment by barbalex** [comment]
Ich habe jetzt das Zweite angepasst auf: "Daten neu laden plus: Einstellungen und Anmeldung zurücksetzen", damit es besser verständlich ist.

Neu-Einloggen ist so eine Sache. Sie passiert normalerweise gar nicht. Damit man nicht dauern neu einloggen muss, bleibt die Anmeldung normalerweise erhalten - wenn man nicht bewusst ausgeloggt hat. Aber sie bleibt nicht unendlich lange erhalten (kann mich nicht erinnern, wie lange ich genau eingestellt habe).

Wenn nun also beim Ausloggen der Filter zurückgesetzt würde, dann wüssten die Benutzerinnen gar nicht, wann es genau passiert.

**Comment by barbalex** [comment]
Was ich machen könnte und auch systematisch funktionieren würde, ist, den gesetzten Filter gar nie zu merken.

Aber dann gäbe es bestimmt Fälle, in denen genau das vermisst würde.

**Comment by jmenzi** [comment]
Müssten wir besprechen. Lass es doch momentan mal so, wie es ist. Danke für die Anpassung der Bezeichnung.
