### ISSUE TITLE
Lieferung in Teilkultur

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#41]
Anlieferung in Teilkultur ist technisch noch nicht richtig möglich, da ich bei einer Anlieferung nicht erkenne, in welche Teilkultur die Lieferung gehen soll. Müssten in diesem spezifischen Fall die Lieferungen hierarchisch unter den Teilkulturen aufgeführt werden? Das ist vermutlich nicht ganz einfach mit der fixen Datenstruktur... Owe.

**Comment by barbalex** [comment]
Das ist nicht möglich und war bisher auch keine Anforderung.

Meine Fragen:
- Wieso wäre das nützlich?
- Wie würde diese Information genutzt und von wem?
- Würde eine Lieferung immer in eine Teilkultur erfolgen? Grundsätzlich natürlich nicht, weil nicht alle Gärten/Kulturen Teilkulturen verwenden. Aber würde das immer gemacht, wenn mit Teilkulturen gearbeitet wird?

**Comment by jmenzi** [comment]
Das Problem liegt bei der Lieferungserfassung. Ich sehe bei der Lieferung in eine Kultur nur den Namen des Gartens. Falls es in diesem Garten nur eine Kultur hat, ist es klar. Falls der Garten, wie die GAW, mehrere Kulturen mit verschiedenen Herkünften hat, kann ich nicht entscheiden, in welche Kultur oder eben auch Teilkultur (da diese angezeigt werden), ich liefern soll. Siehe Screenshot. Es geht nicht um die Verfügbarkeit dieser Informationen. 

<img width="336" alt="Bildschirmfoto 2020-09-09 um 15 53 25" src="https://user-images.githubusercontent.com/6448181/92607812-ecda8380-f2b4-11ea-8632-b43033f37824.png">

**Comment by barbalex** [comment]
Das Datenmodell dreht sich um die Kultur. Und darum, dass es pro Herkunft und Art in einem Garten genau eine aktive Kultur gibt (ausser einem möglichen Zwischenlager).

Auf dieser Ebene wird ausgewertet. Auf dieser Ebene kann man daher auch planen. Und viele, wenn nicht die meisten Gärten bzw. Kulturen arbeiten nur auf dieser Ebene und nicht mit Teilkulturen.

Meine Fragen drehen sich darum um den Grundsatz: Was ist der Mehrnutzen für das Projekt, wenn Lieferungen an Teilkulturen erfolgen statt an Kulturen?

Teilkulturen sind, etwas böse gesagt, nur ein "Pflästerli", das ermöglicht, in bestimmten Gärten oder Kulturen eine Ebene tiefer zu arbeiten. Weil sich aber die Datenstruktur um die Kultur dreht, liegt der Mehrnutzen hier auf Ebene Garten, nicht höher. Und er liegt darin, dass sich ein komplexer Garten besser organisieren kann.

Weil nun einige oder gar die meisten Gärten nicht mit Teilkulturen arbeiten, können wir allgemeine Vorgänge nicht nach ihnen ausrichten. Und wenn Vorgänge beides sollen können, werden sie kompliziert.

Ich kann nicht "einfach" im Kultur-Feld im nach-Bereich der Lieferung Teilkulturen anzeigen. Weil es sie oft nicht gibt. Und ich will mich erst auf solch komplexe Sachen einlassen, wenn der Zweck klar ist.

Sorry, wenn ich etwas pedantisch bin 😏

**Comment by jmenzi** [comment]
Dazu muss ich mir nochmals Gedanken machen und melde mich nächste Woche. Vorerst wäre einfach wichtig, dass man bei der Lieferung die Herkunft sieht? Das würde allenfalls schon helfen?

**Comment by barbalex** [comment]
Sieht man doch:
<img width="364" alt="2020-09-09_17h13_30" src="https://user-images.githubusercontent.com/669783/92617851-092fed80-f2c0-11ea-97ba-4672fe63ddb6.png">

**Comment by jmenzi** [comment]
Ok. Ich versuche es nochmals anders zu erklären. Wir wollen nicht unbedingt eine Lieferung in eine Teilkultur machen. Folgendes Beispiel. Ich möchte 9 Potentilla leucopolitana vom Botanischen Garten in die GAW liefern als Ergänzung zur Kultur in der GAW. Nun kann ich bei der Lieferung aber zweimal GAW aussuchen, da hier diese Herkunft einmal auch als Zwischenlager erfasst ist. Ich sehe bei der Lieferung also nicht, ob ich die Lieferung in die GAW-Kultur mache oder in das Zwischenlager. Das Problem tritt auf, sobald mehrere Kutluren mit der gleichen Herkunft in einem Garten vorhanden sind.
<img width="336" alt="Bildschirmfoto 2020-09-09 um 15 53 25" src="https://user-images.githubusercontent.com/6448181/93882329-61171d00-fce0-11ea-8570-f60106a6ad0f.png">
<img width="1666" alt="Bildschirmfoto 2020-09-22 um 14 27 50" src="https://user-images.githubusercontent.com/6448181/93882347-670cfe00-fce0-11ea-9524-0235a452354a.png">
<img width="734" alt="Bildschirmfoto 2020-09-22 um 14 29 12" src="https://user-images.githubusercontent.com/6448181/93882370-6d02df00-fce0-11ea-9e15-5bfdbe2a6bb7.png">

**Comment by jmenzi** [comment]
Trotzdem bleibt das Problem, wohin soll eine Lieferung gehen, wenn eine Kultur mit Teilkulturen arbeitet. In diesem Spezialfall kann ich nach einer LIeferung in eine Kultur nicht wissen zu welcher Teilkultur die Lieferung gehört... Man müsste sie nur für diesen Fall einer Teilkultur zuordnen können...

**Comment by jmenzi** [comment]
Dachte gerade man kann dies auch mit dem Filter lösen, geht aber leider nicht, da trotz Filter bei der Lieferung noch alle angezeigt werden.

**Comment by barbalex** [comment]
> Ok. Ich versuche es nochmals anders zu erklären. Wir wollen nicht unbedingt eine Lieferung in eine Teilkultur machen. Folgendes Beispiel. Ich möchte 9 Potentilla leucopolitana vom Botanischen Garten in die GAW liefern als Ergänzung zur Kultur in der GAW. Nun kann ich bei der Lieferung aber zweimal GAW aussuchen, da hier diese Herkunft einmal auch als Zwischenlager erfasst ist. Ich sehe bei der Lieferung also nicht, ob ich die Lieferung in die GAW-Kultur mache oder in das Zwischenlager. Das Problem tritt auf, sobald mehrere Kutluren mit der gleichen Herkunft in einem Garten vorhanden sind.

Das ist ein anderes Problem und es hat nichts mit Teilkulturen zu tun, sondern damit dass es verschiedene Arten von Kulturen gibt. Habe dafür ein eigenes Issue gemacht und gelöst: https://github.com/barbalex/vermehrung/issues/44

Bitte sag mir, ob immer noch ein Anliegen offen ist. Ich sehe ehrlich gesagt immer noch nicht ganz durch.

**Comment by jmenzi** [comment]
Ich habe mir die Teilkulturen nochmals angesehen und ich denke da müssen wir nochmals über die Bücher. So wie die Teilkulturen sich momentan präsentieren ist es nicht übersichtlich und führt zu Fehlern. Am Besten wir besprechen dies einmal telefonisch, da aufgrund der Komplexität sehr viele Missverständnisse auftreten können.

**Comment by barbalex** [comment]
Schliesse das mal. Falls wieder aktuell: bitte neuen Issue öffnen, damit wir klar definieren können, worum es geht
