### ISSUE TITLE
Zwischenlager in GAW ausblenden können

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#42]
Da die Zwischenlager nur selten gebraucht werden, wäre es toll, wenn es eine Funktion gibt, wo diese ausgeblendet werden können. Sonst ist es nicht sehr übersichtlich.

**Comment by barbalex** [comment]
Dann müsste wohl die Option standardmässig so eingestellt sein, dass Zwischenlager ausgeblendet sind.

Bisher wurden Optionen auf zwei Ebenen implementiert:
- Kultur
- Person (= Benutzerin)

So wie ich es bisher verstanden habe, würden Zwischenlager fast ausschliesslich in der GAW erstellt. Dort wäre es aber unpraktisch, die Option in allen Kulturen einschalten zu müssen. Also müsste diese Option vermutlich auf Ebene Person implementiert werden.

Bei den Kulturen gibt es noch ein zweites Feld, das vermutlich nicht so oft benutzt wird: Erhaltungskultur.

Ich würde diese Option auch gleich ergänzen.

Was meinst du?

**Comment by jmenzi** [comment]
Das wäre genau, was wir brauchen. Auch mit den Erhaltungskulturen.

**Comment by barbalex** [comment]
Ist ab v0.47.0 implementiert (dauert noch ein paar Minuten).

Diese Felder werden nun nur noch angezeigt, wenn eine dieser Bedingungen gegeben sind:
- Die Benutzerin hat in den Optionen das Feld eingeschaltet
- Das Feld enthält den Wert "true". D.h. es ist ein Zwischenlager bzw. eine Erhaltungskultur

**Comment by jmenzi** [comment]
Wo kann ich dies einstellen? Sehe es bei mir irgendwie nicht.

**Comment by barbalex** [comment]
Das Feld beschreibt die Kultur. Du findest es in den Optionen für Kulturen

**Comment by jmenzi** [comment]
Ok, habe es gefunden. Vielen Dank. Gleichzeitig möchten wir aber, dass wir die Zwischenlager für einen Garten komplett ausblenden können. Aber dieses Problem kann man elegant mit dem Filter lösen. Wenn ich nicht möchte, dass in einem Garten die Zwischenkulturen angezeigt werden, dann kann ich einen Filter setzen. :-)
