### ISSUE TITLE
Lieferung - Person

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#43]
Ein Detail und somit nicht prioritär. Bei den Lieferunge steht "wer" und man kann die Person auswählen. Einem Laien könnte hier nicht klar sein, was gemeint ist. Die Person die ausliefert oder die Person an die geliefert wird?

**Comment by barbalex** [comment]
Soll ich die Feldbezeichnung ergänzen:
- von "Person"
- zu: "liefernde Person"?

Hast du eine bessere Idee?

**Comment by barbalex** [comment]
Ist gemacht und wird mit der nächsten Version live geschaltet
