### ISSUE TITLE
In Lieferungs-Auswahlen Zwischenlieferungen von anderen unterscheiden

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#44]
Siehe https://github.com/barbalex/vermehrung/issues/41#issuecomment-696690784

**Comment by barbalex** [comment]
Ist in Version 0.47.6 umgesetzt

**Comment by barbalex** [comment]
@jmenzi bitte sag mir, wenn es irgendwo noch eine Liste gibt, in der Zwischenlager nicht von anderen Kulturen unterschieden werden. Möglich, dass ich eine übersehen habe...

**Comment by jmenzi** [comment]
Ich sehe es jetzt. Sollte so vorerst für gewisse Lieferungen ok sein. Grundsätzlich müssen wir aber nochmals das Teilkulturenkonzept besprechen.
