### ISSUE TITLE
Fehler aufgrund mangelnder Benutzerrechte: Besser kommunizieren und Operationen löschen

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#45]
https://github.com/barbalex/vermehrung/issues/40#issuecomment-696917927

**Comment by jmenzi** [comment]
Kannst du dies für Edith regeln? Ich möchte sie nicht mit Datenbankproblemen belästigen. Passwort habe ich dir im Mail geschickt.

**Comment by barbalex** [comment]
Um ihr unmittelbares Problem zu beheben, ist folgendes nötig:

- eine Managerin oder Artverantwortliche mit den dafür nötigen Rechten muss die von ihr benötigten Arten erstellen und beschreiben
- sie selber muss ihre ausstehenden Operationen löschen. Siehe hier: https://vermehrung.ch/Dokumentation/offline, beim Abschnitt "Sie können sich durch Klick auf das Online-Symbol auch die Schlange auflisten lassen". Oder gleich den ganzen cache leeren ("Daten, Einstellungen und Anmeldung zurücksetzen" im Menu mit dem Personen-Symbol oben zweites von rechts)

Zusätzlich werde ich versuchen, die Fehlermeldungen besser zu formulieren und die App so anzupassen, dass künftig die scheiternden Operationen nicht von den Benutzern gelöscht werden müssen. Dafür ist dieser Issue gedacht.

Ich kann also momentan zumindest nicht alles für sie machen:
- Ich weiss nicht, welche Arten sie braucht und welche Daten dafür erfasst sein müssen. Das musst vermutlich du machen
- Fragt sich, wer ihr sagt, dass sie ihre Operationen löschen muss. Was meinst du?

**Comment by jmenzi** [comment]
Die Arten sind aber drin. Sie hat nur eine Art. 
![Bildschirmfoto 2020-09-23 um 11 02 08](https://user-images.githubusercontent.com/6448181/93991169-44382380-fd8c-11ea-9c0e-72b927c78478.png)

**Comment by barbalex** [comment]
Fragt sich, ob das bei ihr immer noch so ist. vermehrung lädt alle Daten beim Neu-Start.

Als sie die Art kreierte oder verändern wollte scheiterte die Operation wegen der fehlenden Benutzerrechte. Worauf diese Art bei ihr lokal leer angezeigt wurde.

Dieser Wert sollte beim Neu-Start aktualisiert werden. Falls nicht: wie oben beschrieben alle Daten neu laden.

**Comment by jmenzi** [comment]
Nein, sie sagt es wurde von Anfang an keine Art angezeigt.
cid:4D9225C2-97B9-4B34-A635-E3E75E1E6183@lan

**Comment by jmenzi** [comment]
![Unknown](https://user-images.githubusercontent.com/6448181/93992033-5797be80-fd8d-11ea-9515-fe9bb46bc4d2.png)

**Comment by barbalex** [comment]
Dann war also das ursprüngliche Problem nicht, dass sie versucht hat, eine Art zu erstellen. Sondern dass nach der erstmaligen Anmeldung keinerlei Daten angezeigt wurden?

Ich habe jetzt versucht, als sie anzumelden. Und tatsächlich: Die Daten erschienen erst beim zweiten Mal.

Sag ihr bitte, sie soll es nochmals probieren. Und ich muss dafür sorgen, dass es jeweils beim ersten Mal schon klappt.

**Comment by barbalex** [comment]
Moment: Sie ist mitarbeitend bei einem Garten. Aber der Garten wurde nie gewählt. Also hat sie gar keine Daten verfügbar!

Versuch mal, ihr wirklich einen Garten zuzuweisen.

**Comment by barbalex** [comment]
Hab ich das falsch geschaut oder hast du das soeben gemacht?

**Comment by jmenzi** [comment]
Wollte es machen, aber es war schon gemacht.

**Comment by barbalex** [comment]
Ich hab mich wohl verwirren lassen, weil der Garten genau so heisst wie sie

**Comment by jmenzi** [comment]
Muss ich sie auf Artniveau auch als Mitarbeitende Person erfassen? Das wäre wohl das Problem. Dann muss ich für alle AV hier auch auswählen, welche Person, welche Arten sehen kann. Ich glaube das ist der Grund.

**Comment by jmenzi** [comment]
Klappt leider immer noch nicht, auch nach mehrmaligem Einloggen, Daten neu laden wird nichts angezeigt. Auch bei dem Account von Rebecca werden keine Arten angezeigt.

**Comment by barbalex** [comment]
> Muss ich sie auf Artniveau auch als Mitarbeitende Person erfassen?

Nein. Sonst bekommt sie die gleichen Rechte wie Art-Mitarbeiterinnen

**Comment by barbalex** [comment]
Bezüglich Edith: bitte https://github.com/barbalex/vermehrung/issues/40#issuecomment-698561895 beachten. Ansonsten möchte ich eigentlich die sie betreffenden Kommentare hier entfernen, weil sie vom Issue ablenken und ich somit die Übersicht verliere.

**Comment by barbalex** [comment]
Scheint ja jetzt behoben zu sein
