### ISSUE TITLE
Lieferungen: Darstellung der Anzahl im Strukturbaum nicht korrekt

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#46]
Bei den Lieferungen wird im Strukturbaum keine richtige Zahl angezeigt. Bei Zählungen wird es ja nur angezeigt, wenn alles ausgefüllt wird. Bei den Lieferungen verstehe ich noch nicht ganz, wann die Infos in der Übersicht im Strukturbaum angezeigt werden. 

<img width="233" alt="Bildschirmfoto 2020-09-23 um 09 32 41" src="https://user-images.githubusercontent.com/6448181/93981233-fd443100-fd7f-11ea-866b-d489a0308d99.png">

**Comment by jmenzi** [comment]
Es werden nur die Anzahl Pflanzen angezeigt... Samenmengen nicht? Gibt es einen Grund dafür?

**Comment by barbalex** [comment]
> Bei den Lieferungen wird im Strukturbaum keine richtige Zahl angezeigt

> Darstellung der Anzahl im Strukturbaum nicht korrekt

Ist das so? Werden **falsche** Anzahlen angezeigt?

> Es werden nur die Anzahl Pflanzen angezeigt... Samenmengen nicht? Gibt es einen Grund dafür?

"Anzahl Pflanzen" und "Anzahl auspflanzbereit" sind die wichtigsten Kennwerte (gemäss unseren Zielen: https://vermehrung.ch/Dokumentation/Ziele/#priorit%C3%A4t-1-haupt-ziele). Dies sind auch die Zahlen, welche geplant werden. Und daher ausgewertet und in den Zeitachsen dargestellt werden.

Der Strukturbaum kann nicht ALLE Daten anzeigen, welche in einem Formular erfasst werden. Ich habe versucht, genau diejenigen Daten anzuzeigen, welche am wichtigsten bzw. nützlichsten sind.

Im Strukturbaum können die Zählungen auch nicht angeschrieben werden. Daher sind die Zahlen, wo sie im Strukturbaum dargestellt werden, immer genau gleich dargestellt. Es wäre verwirrend, wenn das nicht immer gleich wäre - weil die Felder nicht angeschrieben sind.

**Comment by jmenzi** [comment]
Ok, dann lassen wir das. Es wird nichts falsch angezeigt, dachte nur es macht Sinn die Gramm Samen auch aufzuführen. Aber lassen wir das lieber momentan.

**Comment by barbalex** [comment]
Dann schliesse ich den Issue um die Übersicht zu behalten. Wir können jederzeit diesen wieder öffnen oder einen neuen erzeugen
