### ISSUE TITLE
Anzeigefehler bei Teilzählungen

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#48]
Teilzählungen können nicht ausgefüllt werden, da die beiden Reiter übereinander angezeigt werden. 
![Teilzählung_Fehler](https://user-images.githubusercontent.com/6448181/94016910-0993b280-fdaf-11ea-8157-10e6ee3dd582.png)

**Comment by barbalex** [comment]
Ist in Version 0.47.7 korrigiert
