### ISSUE TITLE
Passwortdauer muss verlängert werden

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#49]
Eine Passwortdauer von 2 h ist zu kurz. Es erlaubt eigentlich nur eine Erstellung des Accounts, wenn man in direktem Kontakt steht. Dies ist nicht für alle privaten ZV möglich und auch bei den AV schwierig. Das Passwort müsste eher 2 Tage gültig sein.

**Comment by barbalex** [comment]
Das funktioniert nicht so. Sondern so, wie hier beschrieben: https://vermehrung.ch/Dokumentation/Konten/

## Konto erstellen

1. Person erfassen
2. Rolle und email nicht vergessen
3. Auf "Neues Konto" klicken
4. Die Person bei den betreffenden Arten und Gärten als Mitarbeiter erfassen
5. Die Person informieren

## Erstmalige Anmeldung

1. vermehrung.ch besuchen
1. Auf "Daten bearbeiten" klicken
1. Login-Formular erscheint
1. Email eingeben
1. Auf "neues Passwort setzen" klicken
1. Sobald email ankommt, dem Link folgen und ein Passwort setzen
1. In vermehrung.ch damit anmelden

Mit der verwendeten Technologie ist es gar nicht möglich, die "Passwortdauer" zu verlängern. Denn es ist viel zu gefährlich, wenn ein Passwort über längere Zeit verändert werden kann. Grund: Mails sind unsicher. Der Link kann abgefangen werden.
