### ISSUE TITLE
Wesentliche Funktionalität: Kulturstatus, Personenstatus

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#5]
Bei der Kultur (allenfalls auch bei den Personen) braucht es einen Status (ähnlich dem Status einer Population in der FloraDB). 

Der Status der Kultur kann folgende Werte haben:
- Kultur aktuell
- Kultur beendet
- Erhaltungskultur

Der Status einer Person kann folgende Werte haben:
- Aktuelles Mitglied 
- Ehemaliges Mitglied
sowie gleichzeitig
- Freiwilliges Mitglied
- Kommerzielles Mitglied

Die Gartenanlage in Wangen ist ein Spezialfall. Hier denke ich, dass es sinnvoll ist für die Gartenanlage einen Spezialstatus zu erstellen? Die Gartenanlage ist ein aktuelles Mitglied, jedoch weder freiwillig noch kommerziell.

**Comment by barbalex** [comment]
Endet eine Erhaltungskultur nie? Ich denke, die müsste auch aktuell oder beendet sein.

Aktuell/ehemalig: kennzeichnet einfach, ob eine Person im Projekt noch aktiv ist, oder? Genau so wie die Kultur.

Die entscheidende Frage, wenn man Felder hinzufügt ist eigentlich immer: Wie wird das Feld genutzt? Was hat der Inhalt dieses Feldes für Konsequenzen? Wird das Feld ausgewertet?

Freiwillig/Kommerziell: ist das immer eindeutig? Oder gibt es gewisse Sachen, welche die Person freiwillig macht und andere hingegen kommerziell?

**Comment by barbalex** [comment]
Bezüglich aktiv/ehemalig würde ich einfach ein Feld "historisch" oder "inaktiv" ergänzen. 

In den Tabellen kultur, garten, herkunft, person und art.

In der Anwendung kann man wählen, historische Daten nicht anzuzeigen.

**Comment by barbalex** [comment]
Wie ist eine Erhaltungskultur definiert? Was ist eine Kultur, wenn sie keine Erhaltungskultur ist?

**Comment by barbalex** [comment]
Personenstatus: Wozu benutzt ihr ihn dann?

Je nachdem wozu er gedacht ist, beeinflusst das wie er zu handhaben wäre.

Z.B. könnte der Zweck sein, alle rein freiwilligen aktiven Personen abfragen zu können. Dann wäre die Definition "arbeitet nur auf freiwilliger Basis". Und Wangen wäre nicht freiwillig.

Oder ihr müsst unterscheiden können, wer arbeitet manchmal auch freiwillig. Dann bräuchte es einen dritten Status: "freiwillig und kommerziell".

**Comment by jmenzi** [comment]
Endet eine Erhaltungskultur nie? Wird eine Erhaltungskultur beendet ist die gesamte Kultur beendet. Hier brauch es keinen zusätzlichen Status. Eine Erhaltungskultur ist eine normale Kultur, welche gestoppt wurde, jedoch noch en Reserve ist. Sie ist quasi fast beendet, jedoch noch nicht ganz.

**Comment by barbalex** [comment]
Eine Erhaltungskultur heisst also:
- die Art kommt in diesem Garten noch vor
- sie wird hier aber nicht mehr für das Projekt vermehrt

habe ich das richtig verstanden?

**Comment by jmenzi** [comment]
Genau

**Comment by jmenzi** [comment]
Personenstatus - Aktuell/ehemalig/Info: Ja, dies soll zeigen, ob eine Person noch aktiv ist. Historisch finde ich sehr unpassend als Ausdruck (einige Vermehrer sind auch verstorben). Aktiv/inaktiv finde ich passender, falls du ehemaliges Mitglied nicht so toll findest (?). Das Feld ist notwendig, da man wissen muss, wer noch aktiv ist - respektive wen man anfragen könnte, weitere Kulturen zu übernehmen. 

Zusätzlich ist mir eingefallen, dass es auch noch einen Status "Info" braucht. Diese Personen sind zwar nicht mehr aktiv, wollen jedoch noch über das Projekt informiert werden. 

Kommerziell/Freiwillig: Sehr eindeutige Unterscheidung, da für kommerzielle Vermehrung eine Vereinbarung unterschrieben werden muss. Ist also kein Problem. GAW kann als Kommerziell bezeichnet werden. Oder eben separat als GAW aufführen. Dies ist der einzige Fall wo bezahlte mit unbezahlten Kräften zusammen arbeiten.

**Comment by barbalex** [comment]
Ist umgesetzt
