### ISSUE TITLE
Zwei Personen zu einer Person zusammen fassen

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#51]
Ist als Gärtnerin und als Artverantwortliche erfasst. Kann man diese zusammenführen? Allgemein, wie führe ich zwei Personen zusammen zu einer Person?

**Comment by barbalex** [comment]
Wenn du zwei Personen A und B in A zusammenfasst, musst du:
- überall wo B erfasst ist, A setzen
- überall, wo Gärten von B erfasst sind, Garten von A setzen
- allfällige Gärten von B löschen
- B löschen

Wo werden Personen erfasst?
- Gärten (Person, mitarbeitende Personen)
- Lieferungen
- Sammellieferungen
- Sammlungen
- Arten (mitarbeitende Personen)
- Events

Wenn du die Mehrfach-Erfassung nicht sehr schnell bemerkst, wird das etwas schwierig.

Dann bräuchtest du eine Liste aller Datensätze, die angepasst werden müssen. Bzw. wo diese Person erfasst ist.

Dazu müsste man in den Formularen für Person und Garten verlinkt auflisten können, wo diese Person/Garten vorkommt.

Das gibt ziemlich viel Arbeit.

**Comment by jmenzi** [comment]
Danke, ja dann muss ich mal manuell dahinter. Generell eher keine Lösung. Schauen wir, dass dies nicht wieder vorkommt.

**Comment by jmenzi** [comment]
Dieses Issue kannst du schliessen. Wir machen dies manuell, falls es vorkommt. Danke.
