### ISSUE TITLE
Label für Sammlungen: Datum vor Nummer?

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#58]
Aktuell sind Sammlungen im Navigationsbaum so beschriftet: `NR, DATUM: von HERKUNFTNR, PERSON, ART, GEPLANT`

Weil das Nr. Feld ein Textfeld ist, führt das dazu, dass die Sortierung unlogisch ist. So wird z.B. 105 unter 1000 sortiert.

Mir schiene die folgende Beschriftung übersichtlicher:
`DATUM: NR, von HERKUNFTNR, PERSON, ART, GEPLANT`

Vorteile:
- Die Sortierung ist klar und kohärent
- Das Datum ist immer gleich breit. Wenn es ganz links liegt macht das die Liste übersichtlicher: das Auge kann direkt zum gesuchten Datum springen
- Auch Zählungen, Lieferungen und Events sind nach Datum sortiert. Die Benutzerin ist sich das gewohnt
- Nur Herkünfte sind auch nach Nr sortiert. Mit demselben Problem wie bei den Sammlungen. Aber hier hat die Nr. ev. eine grössere Bedeutung?

@jmenzi: was meinst du?

**Comment by jmenzi** [comment]
Finde ich gut. Aber die Nr könnte eigentlich aus der Sortierung entfernt werden, da sie ja neu nicht mehr verwendet wird und ein Relikt aus der alten Datenbank ist. In der Sammlung selbst muss sie aber noch erhalten bleiben, damit eine Rückverfolgung gewährleistet ist.

**Comment by jmenzi** [comment]
Wenn wir gerade bei der Sortierung sind. Die Herkünfte wären besser sortiert, wenn sie nach Herkunft als Text und danach als Nummer sortiert werden. Dies ist aber ein Wunsch und hat keine Priorität.

**Comment by barbalex** [comment]
Ab der nächsten Version werden Sammlungen so angeschrieben: `DATUM: von HERKUNFTNR; ART; PERSON (GEPLANT)`.
Wobei die Person nur genannt wird, wenn sie vorkommt (viele Sammlungen wurden ohne Person erfasst).
