### ISSUE TITLE
funktioniert auf IPhone und iPad nicht

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#59]
Auf dem IPhone 6.1 kann die Datenbank nicht laden (Wir haben folgendes ausprobiert: WLan, Mobiles Netz, Daten neu laden, Daten neu laden plus, auf Chrome). Bei mir auf Android klappt es aber reibungslos. Nach einer Zeit kommt: Diese Seite konnte nicht geladen werden (siehe Screenshots). cid:dca4f84b-b6c8-436a-ba61-e3c78ed7c0accid:cfab25a4-79a7-40f8-b51e-0a6f51b10074

**Comment by jmenzi** [comment]
![Iphone1](https://user-images.githubusercontent.com/6448181/96567629-4cba4600-12c7-11eb-9afd-6eefb9d1aad6.jpg)
![Iphone2](https://user-images.githubusercontent.com/6448181/96567632-4deb7300-12c7-11eb-9ab3-f4c700b254ac.jpg)

**Comment by barbalex** [comment]
Hm. Wird etwas schwierig zu testen sein - ich habe selber keine Apple Mobilgeräte.

Der Grund, wieso ich keine Apple-Mobilgeräte habe, scheint aber genau die Ursache für dieses Problem sein:
- Apple verdient jährlich Milliarden mit dem App-Store: Indem sie 30% jeder Überweisung absahnen
- Apple will die Milchkuh App-Store erhalten, koste es was es wolle
- Web-App's umgehen den App-Store. Man kann sie direkt installieren. Das passt Apple nicht
- Web-App's funktionieren aber nur (gut), wenn der Browser die dafür nötigen Fähigkeiten anbietet
- Apple verbietet auf Mobilgeräten (iOS-Betriebssystem) die Installation anderer Browser und setzt dies im App-Store durch
- Chrome und Firefox (zum Beispiel) haben trotzdem entsprechend genannte Browser im App Store. Damit Benutzer ihre Einstellungen etc. synchronisieren können
- Aber: Weil Apple die Installation anderer Browser verbietet, basieren alle anderen Browser auf iOS auf Safari
- Weil auf Apple-Mobilgeräten nur Safari zur Verfügung steht, hat Apple es in der Hand, zu verhindern, dass die für (gut) funktionierende Web-Apps nötigen Fähigkeiten zur Verfügung stehen. Apple stellt daher einige grundlegende Fähigkeiten bereit, damit nicht zu viele Web-Apps gar nicht funktionieren. Aber sie schränken diese Fähigkeiten ganz bewusst ein, damit Web-Apps gegenüber Apps aus dem App-Store nicht konkurrenzfähig sein können
- Eine zentrale Funktion guter Apps ist Offline-Fähigkeit. Nur damit sind Web-Apps echt konkurrenzfähig gegenüber Apps aus dem App-Store
- Offline-Fähigkeit bedingt, dass die benötigten Daten lokal gespeichert werden. Damit Web-App's nicht konkurrenzfähig sind, schränkt Apple unter anderem die lokal speicherbare Menge Daten sehr stark ein
- Diese Einschränkungen werde ungenügend bis gar nicht dokumentiert. Apple will Web-App-Entwicklern das Leben so schwer wie möglich machen
- Wie es scheint, ermöglicht Apple es Web-Apps nur, 5MB zu speichern. Apple gibt Entwicklern keine Möglichkeit, diese Grenze zu erkennen. Benutzer können offenbar im Einstellungs-App die Grenze auf 50MB erhöhen. Apple gibt Entwicklern keine Möglichkeit, die Grenze aus dem App heraus zu erhöhen (siehe z.B. https://stackoverflow.com/a/8991626/712005)
- Nur um den Gegensatz klar zu machen: Chrome, Edge und Firefox stellen Benutzern so viel Speicherplatz zur Verfügung, wie die Festplatte hergibt! Und Android ermöglicht die Installation von Apps am App-Store vorbei. In Android kann man sogar eigene App-Stores anbieten!
- Gemäss den Messungen benötigt vermehrung.ch 90 bis 120 MB lokalen Speicher. **Damit kann vermehrung.ch nicht auf iOS-Geräten funktionieren**
- Damit vermehrung.ch auf Apple-Mobilgeräten funktionieren könnte, müsste extrem viel Aufwand getrieben werden. Und vor allem müsste die Offline-Fähigkeit entfernt werden. Was aber gerade für die Benutzung auf Mobil-Geräten sehr wichtig ist
- Damit vermehrung.ch auf Apple-Mobilgeräten funktionieren könnte, müsste es also nochmals von Grund auf beruhend auf der Apple-Programmiersprache Swift neu entwickelt werden. Und über den App-Store angeboten werden

vermehrung.ch ist Opfer des Kollateralschadens, der daher rührt, dass Apple an allen Überweisungen 30% verdienen will.

Sorry Apple-Mobilgeräte-BenutzerInnen. Ihr habt für viel Geld ein Gerät gekauft, dass euch von den modernsten Apps ausschliesst.

**Comment by barbalex** [comment]
Mehr dazu hier:
- https://en.wikipedia.org/wiki/Epic_Games_v._Apple
- https://t3n.de/news/apple-vs-epic-microsoft-seite-1315266/

**Comment by barbalex** [comment]
Ich habe das nun in der Dokumentation beschrieben: https://vermehrung.ch/Dokumentation/iOS (nach dem Update auf Version 0.48.4 verfügbar).

**Comment by barbalex** [comment]
Ab Version 0.49.1 werden Benutzerinnen mit iOS beim Einloggen direkt auf die Dokumentation geleitet, die erklärt, dass vermehrung auf iOS nicht funktioniert und wieso: https://vermehrung.ch/Dokumentation/iOS/

**Comment by barbalex** [comment]
Schliesse diesen Issue, weil es leider keine gute Lösung gibt
