### ISSUE TITLE
Wesentliche Funktionalität: Umgehen mit beendeten Kulturen und ehemaligen Mitgliedern

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#6]
Beendete Kulturen und ehemalige Mitglieder sind zwar wichtig für die Dokumentation, sind für die Übersicht aber hinderlich (können sehr lange Listen sein). Deshalb wäre es wichtig, dass insbesondere die beendeten Kulturen ausgeblendet werden können (Filter?). Bei den Personen ist dies aber weniger wichtig. Prio liegt bei den Kulturen.

**Comment by barbalex** [comment]
Macht Sinn.

**Comment by barbalex** [comment]
Ist implementiert: für Gärten, Kulturen und Personen.
