### ISSUE TITLE
Radsymbol einheitlich verwenden - Benutzerfreundlichkeit

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#60]
Bei der Erstellung der Anleitung ist uns aufgefallen, dass das Radsymbol in der Titelleiste eine andere "Bedeutung" hat als in den Untermenüs. In der Titelleiste können damit gelöschte Datensätze und Inaktive Datensätze verborgen werden. In den Untermenüs sind Anzeigeoptionen auswählbar. 

Unser Vorschlag: Da es die Funktion "gelöschte Datensätze anzeigen" nicht braucht und die Auswahl der inaktiven Datensätze eigentlich einen Filter darstellt: Radsymbol aus Titelleiste entfernen, stattdessen entweder direkt in der Filterumgebung (am Besten ganz oben) oder auch in der Titelleiste (violetter Balken) einen Schieber einfügen mit "nur aktive Datensätze anzeigen". Wäre das möglich?

**Comment by barbalex** [comment]
Gute Idee. Nimm mir eine Verbesserung vor, aber wenig prioritär. Danke für den Vorschlag

**Comment by Seraina1** [comment]
Wurde dies bereits umgesetzt? Das Radsymbol in der Titelseite ist nicht mehr zu sehen...

**Comment by barbalex** [comment]
> Das Radsymbol in der Titelseite ist nicht mehr zu sehen

Bin nicht sicher, was damit gemeint ist. Meines Wissens wurde eben nichts verändert. Wir haben ja auch kein Budget dafür.

**Comment by Seraina1** [comment]
Ok, dann wäre das sicher etwas, dass man für 2023 (mit neuem Budget) einplanen und erledigen kann.

**Comment by barbalex** [comment]
> Issue kann ich aktuell nicht mehr gut nachvollziehen,

Da ich auch nicht sicher bin, was gemeint ist: Schliessen wir das.
