### ISSUE TITLE
Label für Herkünfte

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#61]
@jmenzi
[Jasmin hat gewünscht](https://github.com/barbalex/vermehrung/issues/58#issuecomment-712732746):

> Die Herkünfte wären besser sortiert, wenn sie nach Herkunft als Text und danach als Nummer sortiert werden

Herkünfte sind heute so angeschrieben und sortiert: `NR, GEMEINDE, LOKALNAME`

Mir schiene es unlogisch, wenn die Nummer zuvorderst steht, sie aber zuerst nach Gemeinde und Lokalname sortiert wären.

Was meinst du zu: `GEMEINDE, LOKALNAME, (NR)`?

**Comment by jmenzi** [comment]
Ja, eine gute Idee. Aber bitte auch mit Nummer. Danke für den Vorschlag.

**Comment by barbalex** [comment]
@jmenzi  Ist in Version 0.48.6 gemacht. Und generell alle Labels systematischer aufgebaut
