### ISSUE TITLE
Zeit-Achsen zeigen nur negativ Werte an

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#62]
Lieber Alex

Heute wollte ich die Präsentation der DB für nächsten Montag vorbereiten. Dabei habe ich bemerkt, dass aktuell die Zeitachsen bei mir nur negative Werte anzeigen. Könntest du das noch bis Ende Woche reparieren? Vielen Dank. Grüsse, Jasmin

**Comment by barbalex** [comment]
o.k., scheinen alle zu sein

**Comment by barbalex** [comment]
Trotzdem die Frage nochmals: Kannst du bitte ein Beispiel nennen, wo es nicht stimmen kann? Du kennst die Daten besser.

Denn negative Werte werden automatisch berechnet, wenn die Zählungen kleiner sind als Auspflanzungen. Es hängt also von den Daten ab. Und ich kenne die Daten nicht bzw. habe keine Ahnung, wo wirklich Zählungen erfasst wurden bzw. wo überall es sein kann, dass Auspflanzungen ohne Zählungen erfasst wurden.

**Comment by barbalex** [comment]
Hab mal bei Abies alba was getestet. Da wird wirklich falsch gerechnet. Ich brauche also vorläufig keine Beispiele

**Comment by barbalex** [comment]
O.k., Fehler gefunden: das war Kollateralschaden, der entstand, als ich die Funktionalität, welche verknüpfte Daten verknüpfte, umbauen musste, weil sie unbrauchbar langsam und unzuverlässig war.

Ist in Version 0.48.9 korrigiert.

**Comment by barbalex** [comment]
In Version 0.48.9 klappt es auch in den Zeitachsen pro Herkunft wieder.
