### ISSUE TITLE
Neue Funktion: Inventar erfassen bzw. Zählen pro Teilkultur

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#63]
@jmenzi schrieb am 29.10.:

> Das Problem ist, dass man die Aufnahmen für jede Teilkultur erfasst. Du musst dir vorstellen, dass man jeden Kasten abläuft und die Zahl pro Teilkultur erfassen möchte Kasten 1, Beet 1, Nr 1 dann weiter Kasten 1, Beet 1, Nr 2 ect. Man kann nicht pro Art immer wieder in der Anlage umherlaufen um diese zu finden. Ich kann also nicht die Kultur öffnen und hier Eingaben machen. Ich habe mir überlegt, ob es eine Möglichkeit gibt über den Sturkturbaum via Teilkulturen die Erfassung zu machen, da diese nach Ort sortiert werden können. Wichtig wäre dann, dass bei den Teilkulturen die Art angezeigt wird. Das hatten wir ja schonmal diskutiert und ist aufgrund der Datenstruktur nicht möglich, jedoch gibt es vielleicht eine Möglichkeit über eine Art Anzeigeverknüpfung hier die Daten der Teilzählung zu erfassen auch wenn die Daten dann unter der Kultur gespeichert werden?

**Comment by barbalex** [comment]
@jmenzi bitte klicke auf github.com rechts im Bereich "Notifications" auf "subscribe", um von diesem Issue alle Updates zu erhalten. Dann können wir hier darüber diskutieren

**Comment by barbalex** [comment]
@jmenzi Beruhend auf einem Input habe ich den nun folgenden Vorschlag entwickelt.

Wir könnten bei den Gärten im Navigationsbaum einen neuen Ast bauen. 

(Oder ein dafür spezialisiertes Listen-Formular wie z.B. bei apflora für die EK-Planung - das aber vermutlich nur auf PC's vorteilhaft wäre, weil es für Mobilgeräte zu gross wäre - weshalb ich das nicht empfehle.) 

Dieser Ast dient dazu, effizient zu zählen bzw. Inventare zu erstellen.

Er listet daher auf:
- Für Kulturen, welche keine Teilkulturen verwenden: `ART; von HERKUNFT-NR`
- Für Kulturen, welche Teilkulturen verwenden: `ART; von HERKUNFT-NR; TEILKULTUR`
- Die Teilkultur wird dargestellt durch: ihren Namen. Wir können das ev. erweitern zu: Wenn es keinen Namen gibt, aber Orte, dann `ORT1 / ORT2 / ORT3` oder so ähnlich
- Zusätzlich die erhobenen Zahlen. Also z.B. wenn eine Kultur mit Teilkulturen arbeitet: `ART; von HERKUNFT-NR; TEILKULTUR; ___ / ___ / ___`. Man sieht somit immer, wo schon gezählt wurde
- Falls Inventare über mehrere Tage erhoben werden können sollten, müsste man noch das Datum ergänzen: `ART; von HERKUNFT-NR; TEILKULTUR; DATUM; ___ / ___ / ___`

Klickt man auf einen Unterast, erstellt vermehrung.ch eine neue Zählung mit dem aktuellen Datum für die entsprechende Kultur Oder: das Formular rechts zeigt eine Schaltfläche, mit der man die neue Zählung erstellen kann. Oder: Das Formular rechts wird zunächst leer angezeigt. Es erzeugt die neue Zählung, sobald ein erster Wert darin erfasst wird.

Im Formular wird die Zählung dargestellt. Vermutlich am besten nur die Mengen, mit der Option, die Zählung einzublenden.

Auf einem PC oder grossem Tablett kann man somit mittels Navigationsbaum navigieren. 

Auf kleineren Tabletts und auf Smartphones erscheint der Ast des Navigationsbaums als Liste, mittels derer man navigiert. Also:
- Liste öffnen
- Auf (vorbereitete) Zählung klicken
- Daten erfassen
- Auf das Symbol mit dem nach oben gerichteten Pfeil klicken, um zurück zur Liste zu kehren
- Auf die nächste Zählung klicken
- und so weiter

In der Mobilansicht gibt es ein spezielles Problem zu lösen: Kehrt man vom Formular in die Liste zurück, sollte sie am selben Ort gescrollt sein, wo man zuletzt eine Zählung geöffnet hat. Sonst verliert man bei grossen Gärten die Übersicht und scrollt unendlich herum (diese Funktionalität wäre auch für andere Listen vorteilhaft).

Ev. wäre es nützlich, wenn der neue Ast alle Inventare auflisten würde. Dann könnte man nämlich auch über einen Zeitraum von mehr als einem Tag ein Inventar erfassen. Also:

- Gärten
  - ...
  - GAW
    - Kulturen
    - Inventare
      - 2020.10.05
        - `ART; von HERKUNFT-NR; TEILKULTUR; ___ / ___ / ___`
        - `ART; von HERKUNFT-NR; TEILKULTUR; ___ / ___ / ___`
      - 2020.06.03
      - 2019.10.15

"Inventar" ist in vermehrung.ch ein neues Konzept. Es ist aber nur ein Datum, an dem Zählungen aller Kulturen erfasst werden. Daher braucht es dafür nicht unbedingt eine neue Datenstruktur. Das Datum wird einfach zwischengespeichert, während man in einem Inventar navigiert. Das hat allerdings zur Folge, dass unter dem Ast "Inventare" alle "Datümer" erscheinen, an denen mindestens eine Zählung erfasst wurde. Und somit jede Zählung das Etikett "Inventar" erhält.

Es wäre auch möglich, das Konzept "Inventar" neu in das Datenmodell aufzunehmen. Eine Gruppe von Zählungen könnte somit damit beschrieben werden. Was u.a. dazu führen würde, dass nur explizit erfasste Inventare in der Liste der Inventare erscheinen würden. Ein Inventar könnte je nach euren Bedürfnissen mit einem Namen beschrieben werden, z.B. "Herbstinventar". Die Datenstruktur der Tabelle "inventare" hätte somit:
- id
- garten_id
- ev.: name
- ev.: datum

Und in der Tabelle "zaehlung" würde ein Feld "inventar_id" ergänzt.

Der Navigationsbaum wäre dann:

- Gärten
  - GAW
    - Kulturen
    - Inventare
      - Herbst 2020
        - `ART; von HERKUNFT-NR; TEILKULTUR; ___ / ___ / ___`
        - `ART; von HERKUNFT-NR; TEILKULTUR; ___ / ___ / ___`
      - Frühling 2020
      - Herbst 2019

Für die Erfassung von Inventaren durch Benutzerinnen bedeutet das kaum mehr Arbeit: Nur die oben mit "ev." bezeichneten Felder wäre pro Inventar zusätzlich zu erfassen. Die inventar_id wird automatisch bei der Zählung ergänzt.

Müssen Inventare vollständig sein? Und falls ja, innerhalb welchen Zeitraums? Gemäss Datenmodell muss eine Zählung in einer Kultur immer die summierten Zahlen aller Teilkulturen darstellen. Aber es gibt keine Vorgabe, dass in jeder Kultur eines Gartens gezählt werden muss. Und ich würde diese Vorgabe auch nicht schaffen, wenn es keinen guten Grund dafür gibt. Bin einfach neugierig, ob das ein Thema ist. Und es würde die Programmierung beeinflussen.

**Comment by barbalex** [comment]
Gemäss Telefon vom 18.11.2020 stellen wir das zurück, bis vermehrung.ch auf Mobilgeräten besser funktioniert

**Comment by barbalex** [comment]
@jmenzi

Wir haben das zurückgestellt, bis vermehrung.ch auf Mobilgeräten besser funktioniert.

Diese Voraussetzung ist jetzt gegeben. 
Und ich hätte gerade etwas Zeit, das umzusetzen.

Bist du mit meinem Vorschlag [oben](https://github.com/barbalex/vermehrung/issues/63#issuecomment-719467691) einverstanden? Soll ich es jetzt ergänzen?

**Comment by jmenzi** [comment]
> Müssen Inventare vollständig sein? Und falls ja, innerhalb welchen Zeitraums? Gemäss Datenmodell muss eine Zählung in einer Kultur immer die summierten Zahlen aller Teilkulturen darstellen. Aber es gibt keine Vorgabe, dass in jeder Kultur eines Gartens gezählt werden muss. Und ich würde diese Vorgabe auch nicht schaffen, wenn es keinen guten Grund dafür gibt. Bin einfach neugierig, ob das ein Thema ist. Und es würde die Programmierung beeinflussen.

Nein, Inventare müssen nicht vollständig sein, sollten es aber. Sprich, gerne hätten wir vollständige Inventare, manchmal zählen wir aus Zeitgründen aber nicht alles aus. Es wäre ein zu grosse Einschränkung, wenn durch fehlende Zählungen Fehlermeldungen entstehen würden. Aber grundsätzlich hast du recht.

**Comment by barbalex** [comment]
Beachte auch https://github.com/barbalex/vermehrung/issues/63

**Comment by Seraina1** [comment]
Issue ist vorerst nicht mehr aktuell, da die Funktion der Teilkulturen längerfristig wohl nicht mehr gebraucht werden.
