### ISSUE TITLE
Zwischenlager ohne Pflanzen reduzieren die Übersicht

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#64]
@jmenzi schrieb am 29.10.2020: 

> Wenn ein Zwischenlager keine Pflanzen enthält, müsste es auf inaktiv gesetzt werden – Sprich, wenn keine Daten da sind. Sonst wird es echt unübersichtlich mit all diesen Kulturen für die Erfassung!

**Comment by barbalex** [comment]
@jmenzi

Was genau heisst:

> Sprich, wenn keine Daten da sind

Mögliche Daten sind wohl:
- Zählungen
- An-Lieferungen
- Aus-Lieferungen
- Events

Meinst du: 
- Wenn keine An-Lieferung erfolgte 
- oder die letzte Zählung 0 ergab und es seither keine Anlieferung gab
- oder so viele ausgeliefert wurden, wie insgesamt angeliefert wurden
- aber was gilt, wenn dazwischen gezählt wurde?
- also eventuell: wenn seit der letzten Zählung so viele ausgeliefert wurden, dass damit die Anzahl aus der letzten Zählung inklusive allfälliger seither erfolgen Anlieferungen auf 0 reduziert wurde? (auf diese Weise werden die Zeitachsen berechnet)

Es ist nicht ganz simpel.

Was genau heisst:

> müsste es auf inaktiv gesetzt werden

- Wann müsste das geschehen bzw. wodurch würde das ausgelöst?
- Wenn das automatisch passiert, wenn man eine Zählung oder Auslieferung erfasst, könnte sich der Datensatz vor den Augen der Benutzerin inaktiv erklären und verschwinden. Das scheint etwas unheimlich...
- Man könnte dann nicht in solche Zwischenlager liefern, ohne sie zuvor wieder aktiv zu setzen oder generell inaktive Objekte anzuzeigen. Wäre das nicht unpraktisch?

Der Zweck ist glaube ich, dass innerhalb des Gartens in der Liste der Kulturen die Übersichtlichkeit erhöht wird.

Vielleicht sollte man eine neue Option genau dafür schaffen?
Nur ist leider nicht einfach, zu wissen, welche nicht angezeigt werden sollen, siehe oben.

Ich sehe bisher leider nur sehr komplexe Lösungen.

**Comment by jmenzi** [comment]
Wir haben das Problem nun so gelöst, dass die Zwischenlager ohne Pflanzen auf inaktiv gesetzt wurden. Somit sind diese nicht mehr sichtbar. Wir müssen bei einer Lieferung nun die Zwischenkultur wieder auf aktiv setzen.

**Comment by barbalex** [comment]
Ich bin offen für eine bessere (= automatische, nicht mir Arbeit verbundene und weniger fehlerträchtige) Lösung. Wenn wir klären können, wie das genau funktionieren soll.

**Comment by barbalex** [comment]
Eine bessere Lösung wäre wichtig, siehe https://github.com/barbalex/vermehrung/issues/77#issuecomment-764529023

**Comment by barbalex** [comment]
Das wird nun mit https://github.com/barbalex/vermehrung/issues/81 gelöst. Daher schliesse ich diesen Issue
