### ISSUE TITLE
Garten: Verein konkret - Saxifraga Kulturen können nicht auf aktiv gesetzt werden

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#65]
Die Datenbank meldet einen Fehler, wenn ich eine der beiden inaktiven Kulturen auf aktiv setzen will. Dies obwohl keine andere Kultur von Saxifraga auf aktiv gesetzt ist.

**Comment by barbalex** [comment]
Wenn ich reinschaue:
- Ist die eine mit Herkunft ZHHK1051.592 aktiv. Na ja, das ist sie, weil ich soeben versucht habe, ob ich sie aktiv setzen kann. Hab sie soeben wieder inaktiv gesetzt
- und die andere mit Herkunft ZHHK1031.634 inaktiv

Das heisst: bei mir ist dieser Fehler nicht aufgetreten.

Was war das für ein Fehler?

**Comment by jmenzi** [comment]
Bevor ich ein Issue eröffne mache ich immer Daten neu laden plus :-).
Jetzt zeigt es mir Saxifraga auch an, jedoch wurden die Zahlen der letzten zwei Zählungen nicht gespeichert. Es kam diejenige Meldung, welche kommt, wenn man zwei gleiche Kulturen einer Art in einem Garten eröffnet.

**Comment by barbalex** [comment]
Kannst du diesen Fehler wieder provozieren? Wenn ja, wie?

**Comment by jmenzi** [comment]
![Saxifraga_aktiv](https://user-images.githubusercontent.com/6448181/99500155-3a8cff80-297a-11eb-9c38-81242b0c9c63.PNG)

Heute sind sowohl Sagittaria also auch Saxifraga wieder auf inaktiv. Sobald ich Saxifraga auf aktiv setzen will, kommt diese Fehlermeldung. Danach werden sämtliche Eingaben nicht mehr gespeichert.

**Comment by barbalex** [comment]
#### Analyse
O.k., dank dem Bild ist es nun klar:

Zum Zeitpunkt, als du diese Kultur aktiv stellen wolltest, gab es in der Datenbank schon für diese Herkunft dieser Art in diesem Garten eine aktive Kultur.

Als du die Kultur aktiv gesetzt hast, hat vermehrung.ch eine Operation erstellt, welche in der Datenbank die Kultur aktiv setzen sollte. Die Operation ist aber gescheitert, weil das nicht mehr möglich war.

Solch komplexe Prüfungen der Daten sind datenbankseitig viel einfacher und effizienter als App-seitig. Darum passiert das in der Datenbank.

#### Allgemeine Lösung
Ich habe nun die Anwendung so angepasst, dass in diesem Fall:
- die Fehlermeldung direkt beim Feld erscheint
- sie folgendermassen lautet: "Pro Art, Herkunft und Garten darf nur eine Kultur aktiv sein (plus ein Zwischenlager). Offenbar gibt es schon eine aktive Kultur"
- die Operation automatisch gelöscht wird

Das wird aktiv in Version 0.49.4.

#### Lösung für dich
Bei dir gibt es jetzt eine Operation, welche hartnäckig in die Datenbank schreiben will, aber das nicht kann. Du musst sie löschen. Es gibt drei Möglichkeiten:
- Wenn die Meldung erscheint auf die darin enthaltene Schaltfläche "Operation löschen" klicken
- Auf das Wolken-Symbol oben rechts klicken. Es öffnet sich eine Liste aller ausstehenden Operationen. Hier kannst du sie löschen
- Befehl "Daten neu laden plus: Einstellungen und Anmeldung zurücksetzen"

**Comment by jmenzi** [comment]
Ja, das habe ich alles probiert und jetzt aktuell gibt es da wohl keinen Konflikt mehr. Trotzdem tritt der Fehler immer noch auf. Saxifraga verschwindet immer. Zudem speichert die Datenbank keine Daten mehr, welche nach dem Auftreten dieses Fehlers noch eingegeben werden, was sehr gefährlich ist. Da diese absolute Restriktion auf nur eine Kultur einer Art sowieso etwas zu restriktiv ist, wäre es mir (wie schon früher angedeutet) eigentlich lieber, wenn du diese Restriktion herausnehmen könntest. Sie trifft ja auch nicht für alle Gärten zu.. z.B. der BoGa. Ich denke es ist besser, wir lassen diese Entscheidung offen. Die Datenbank schränkt hier zu sehr ein, denn es gibt auch andere "gärtnerische" Massnahmen, wie die Herkunftsreinheit gewährleistet werden kann (z.B. Blüten abschneiden).

**Comment by barbalex** [comment]
> Saxifraga verschwindet immer

Was heisst das? Ich habe leider keine Ahnung, was du beschreibst. Und kann es somit nicht provozieren.

> Zudem speichert die Datenbank keine Daten mehr, welche nach dem Auftreten dieses Fehlers noch eingegeben werden, was sehr gefährlich ist

Ja, das ist nicht gut.

Wie bei allen Fehlern muss ich sie provozieren können, um sie zu lösen. Du scheinst das regelmässig provozieren zu können? Was genau musst du machen, um es zu provozieren?

> speichert die Datenbank keine Daten mehr
Was genau heisst das? 
- Erscheinen Fehler, wenn man die Daten erfasst?
- Bleiben die Daten nach dem Erfassen im Formular selber sichtbar?
- Sind die Daten im Formular immer noch sichtbar, wenn man Datensätze gewechselt und wieder zurück navigiert hat bzw. die App neu startet?
- Erscheinen die im Formular erfassten Anzahlen nicht im Navigationsbaum?
- Erscheinen die von dir erfassten Daten nicht in anderen Instanzen von vermehrung.ch? Also wenn du vermehrung.ch auf einem anderen PC/Browser öffnest? (das würde bedeuten: sie werden bei dir lokal gespeichert aber nicht an den Server übermittelt)

> Da diese absolute Restriktion auf nur eine Kultur einer Art sowieso etwas zu restriktiv ist

Wir diskutieren wieder über eine Kernfunktion. Sie ist in den Hauptzielen 1 und 2 ausgedrückt, siehe: https://vermehrung.ch/Dokumentation/Ziele. Die gewählte konzeptionelle Struktur ermöglicht es, diese zwei Ziele zu erreichen. Darum habe ich diese Ziele an den Anfang der Entwicklung gestellt. Das mitten im Rennen zu ändern würde einem Neu-Start entsprechen. Will heissen: potentiell drei bis sechs Monate Arbeit! Im Minimum aber sehr viel Arbeit verknüpft mit sehr viel Potential für neue Fehler, weil der ganze Aufbau von vermehrung.ch aufgrund dieser Vorgabe erfolgte.

Beispiele, was sich ändern würde, könnte man pro Art-Herkunft mehrere aktive vermehrende Kulturen im selben Garten erfassen (die Liste ist zufällig herausgegriffen, es gibt sicher mehr Gründe): 
- Die Zeitachse pro Herkunft und Kultur verliert an Bedeutung, denn  es kann jetzt in einem Garten mehrere solche Kulturen geben. Es braucht also zusätzlich eine Zeitachse pro Art-Herkunft (worin alle Kulturen der Art mit dieser Herkunft zusammengefasst werden)
- Es wäre nicht gegeben, dass in all diesen Kulturen zum selben Zeitpunkt gezählt würde. Wie will man dann ausdrücken, wie viele Pflanzen zu einem bestimmten Zeitpunkt existieren? Schon die einzelnen im Diagramm dargestellten Punkte müssten sich also zusammensetzen aus:
  - Summe der Zählungen zu diesem Datum
  - In den Kulturen, in denen an diesem Datum nicht gezählt wurde: 
    - Summe der letzten Zählung 
    - oder Summe der jeweils letzten Prognose (wenn zuletzt eine Prognose existiert)
    - oder die bis hierhin berechnete Summe plus Summe der zwischen diesem Datum und dem auszuwertenden erfolgten Lieferungen
- An- und Aus-Lieferungen: Mit der gewählten Struktur kann man immer pro Garten genau eine erfassen. Wenn es aber mehrere Art-Herkunft-Kulturen gäbe, müsste man oft auch die Lieferung aufteilen. Das möchte bestimmt niemand
- Wenn es mehrere aktive Kulturen einer Art mit gleicher Herkunft im selben Garten gibt, kann man den Wert "von Anzahl Individuen" nicht mehr beurteilen: muss ich jetzt die Anzahlen aller Kulturen summieren? Oder waren es dieselben Individuen? Oder etwas dazwischen?

Nochmals: Die aktive vermehrende Kultur aus einer Art und Herkunft im Garten ist ein konzeptionelles Gefäss, damit die Verwaltung mit den gesetzten Zielen möglichst einfach ist. Will man sich innerhalb des Gartens weiter organisieren, gibt es dafür die Teil-Kulturen.

Grundsätzlich besteht ein System darin, dass man sich einschränkt. Damit man Dinge erreichen kann, die sonst nicht möglich wären. Hat ein System zu viele Freiheitsgrade, wird es komplex und unverständlich. Einschränkungen erleichtern die Übersicht und ermöglichen es, etwas zu erreichen, was man sonst nicht hätte erreichen können.

Alle hassen Einschränkungen (ich auch). Aber ohne diese wäre sehr vieles nicht möglich. Nicht zuletzt unsere Gesellschaft. Stell dir vor, es gäbe keine Gesetze und keine Polizei, welche sie durchsetzt... Die wichtigen Fragen sind:
- Was soll das System erreichen? > Ziele (= Verfassung)
- Welche Einschränkungen sind optimal, damit das System ermöglichen kann, diese Ziele zu erreichen (= Gesetze)

Oder nochmals anders formuliert: Damit Ziele 1 und 2 mit vermehrung.ch erreicht werden können, muss vermehrung.ch einschränken, wie die Daten erfasst werden. Eine freie Excel-Liste würde nicht genügen.

> Sie trifft ja auch nicht für alle Gärten zu.. z.B. der BoGa

- Was ist die "BoGa"?
- Inwiefern trifft das hier nicht zu?

> Ich denke es ist besser, wir lassen diese Entscheidung offen

Ja, wenn wir nach jeder Diskussion wieder neu anfangen wollen.

**Comment by jmenzi** [comment]
Ein Teil des Problems konnte ich lösen. Die gelöschte Kultur wird offenbar bei der Regel "Herkunftsreinheit - nur eine Herkunft pro Art pro Garten" auch mitgezählt. Wenn wir bei den gelöschten Daten das Häkchen aktiv entfernen, wird der Fehler nicht mehr angezeigt. Ein Grund mehr, gelöschte Daten nicht in der Datenbank fix zu integrieren - in der AP-Flora-Datenbank kann man ja auch nicht alle jemals gelöschten Daten anzeigen lassen.

**Comment by barbalex** [comment]
> Wenn wir bei den gelöschten Daten das Häkchen aktiv entfernen, wird der Fehler nicht mehr angezeigt

Sorry, mein Fehler. Ich hatten im Index vergessen, das _delete Feld zu berücksichtigen. Ist korrigiert.

> Ein Grund mehr, gelöschte Daten nicht in der Datenbank fix zu integrieren - in der AP-Flora-Datenbank kann man ja auch nicht alle jemals gelöschten Daten anzeigen lassen.

Ja, in apflora ist das nicht so, weil apflora nicht offline fähig ist. Offline-Fähigkeit bedingt zwingend, dass Apps die Löschung von Datensätzen beim Kontakt mit dem Server erfahren. Auch wenn sie einmal monatelang nicht online gewesen sein sollten. Darum werden Datensätze nicht gelöscht, sondern als gelöscht markiert.

Das hat übrigens nichts damit zu tun, ob gelöschte Daten in der App angezeigt werden können sollten. Ich habe die Funktion integriert, weil ich dachte, sie könne sporadisch nützlich sein. Wieso nützlich?

Man kann in vermehrung.ch _jeden einzigen Bearbeitungsschritt seit der Erstellung eines Datensatzes_ jederzeit einsehen (https://vermehrung.ch/Dokumentation/Historisierung) und wenn nötig rückgängig machen (https://vermehrung.ch/Dokumentation/offline/#konflikte).

Apps, die das ermöglichen, sind selten.

Und das funktioniert natürlich nur, wenn man gelöschte Datensätze einblenden kann. Sonst könnte man nämlich alles rückgängig machen, bloss keine Löschungen.
