### ISSUE TITLE
Zählungen: Pflanzenzahlen werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#66]
Seit dem Fehler mit Saxifraga werden bei den Zählungen die Anzahl der Pflanzen nicht mehr angezeigt im Strukturbaum. Trotz neu Laden aller Daten.

**Comment by barbalex** [comment]
Dann musst du wohl nicht nur die Daten neu laden, sondern auch die Einstellungen zurücksetzen.
Vielleicht reicht es aber auch, bloss die Anwendung neu zu starten (je nachdem was der Fehler war).

**Comment by jmenzi** [comment]
Das habe ich natürlich probiert :-) Klappt leider nicht.

**Comment by barbalex** [comment]
Ich verstehe leider noch nicht genau, was das Problem ist:
- Zeigt der Baum Anzahlen nicht, welche im Formular angezeigt werden? Das heisst: Es gibt einen Widerspruch zwischen Baum und Formular?
- Wurden Daten (im Zusammenhang mit dem anderen Fehler) erfolglos erfasst, womit sie auch im Formular nicht angezeigt werden?

**Comment by barbalex** [comment]
Bei mir werden sie beim selben Beispiel richtig angezeigt.

Aha: Nach "Daten neu laden plus: Einstellungen und Anmeldung zurücksetzen" allerdings nicht mehr.

Ich kann das also nachvollziehen 🎉

**Comment by barbalex** [comment]
Aha. Das passiert nur beim ersten Aufstarten nachdem man alle Daten vom Server neu geladen hat.
Entweder dauert es einfach lange, bis alle Daten verfügbar und ausgewertet sind.
Oder es gibt hier einen Fehler in der Anwendung, der bewirkt, dass sie nach dem erstmaligen neu Laden noch nicht automatisch angezeigt werden.

Ich geh dem noch nach, aber du solltest einfach die App neu starten können, um das zu beheben.

**Comment by jmenzi** [comment]
![Fehler bei Anzeige 2](https://user-images.githubusercontent.com/6448181/99536101-2d880480-29aa-11eb-9e07-afc894f4d110.PNG)

Ok, jetzt werden die Zahlen im Strukturbaum angezeigt, dafür aber die Daten in der Zählung nicht mehr. Allenfalls sind die verloren geglaubten Daten noch da, man sieht sie einfach nicht?

**Comment by jmenzi** [comment]
Nach Neuladen der Daten, sind diese wieder weg. Auch wird die Zeitachse nicht aktualisiert. Hier habe ich z.B. drei neue Zählungen hinzugefügt, welche dann beim nächsten Laden keine Zahlen anzeigen. 
![Fehler, bei Anzeige 3](https://user-images.githubusercontent.com/6448181/99559728-62558500-29c5-11eb-99f9-8091e81af7fd.PNG)

**Comment by barbalex** [comment]
Das ist der letzte verbliebene Ort, wo ich eine Funktion eines verwendeten Werkzeugs benutze, um die Summen aller Teilzählungen zu bilden (überall sonst habe ich das umgebaut, weil es die Leistungsfähigkeit von vermehrung.ch beeinträchtigte und - sic - dazu führte, dass Daten beim ersten mal nach dem Laden nicht angezeigt wurden).

Bitte probiere ab Version 0.49.5, ob es besser funktioniert.

**Comment by barbalex** [comment]
Ich schliesse mal hoffnungsfroh 🙏
