### ISSUE TITLE
Fehler beim Log-In

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#67]
Leider kann ich mich nach dem letzten Daten neu laden plus nicht mehr einloggen. Ich habe von meinem PC deshalb keinen Zugriff mehr auf die DB :-(. 

![Anmeldefehler](https://user-images.githubusercontent.com/6448181/99536288-717b0980-29aa-11eb-9fba-8034aadb0fd8.PNG)

**Comment by barbalex** [comment]
Ursache ist: Die Werte werden von deinem Browser/Passwortwerkzeug automatisch in die Felder gesetzt, _ohne dass die Felder fokussiert werden_.

Änderungen von Werten in Feldern werden erst registriert, wenn der Fokus das Feld verlässt.

Das passiert aber nicht, wenn die Werte ohne zu Fokussieren gesetzt wurden. Du klickst also auf "ANMELDEN", ohne dass die für dich sichtbaren Werte für vermehrung.ch selbst sichtbar wären.

Ich muss eine Lösung für dieses Problem finden.

Vorläufig kannst du folgendermassen einloggen: Klick in irgend eines der beiden Felder, bevor du auf "ANMELDEN" klickst.

**Comment by jmenzi** [comment]
Ok, das klappt soweit. Danke.

**Comment by barbalex** [comment]
Habe jetzt herausgefunden, dass ganz viele Projekte mit diesem Effekt kämpfen 😢 
Aber auch, wie man es umgeht 🎉 

Ist in Version 0.49.8 korrigiert.

Danke für die Meldung.
