### ISSUE TITLE
Fehlermeldung bei Erfassung neuer Person

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#68]
Leider kann ich aktuell keine neuen Personen erfassen. Siehe Screenshot. 
<img width="1675" alt="Bildschirmfoto 2020-12-01 um 11 39 54" src="https://user-images.githubusercontent.com/6448181/100730580-8607ca80-33ca-11eb-8c49-73ec6a004158.png">

**Comment by barbalex** [comment]
O.k., werde dem nachgehen. Du muss jetzt aber die Operation löschen, sonst geht gar nichts mehr

**Comment by jmenzi** [comment]
gemacht

[signature_1571016165]

Von: Alexander Gabriel <notifications@github.com>
Antworten an: barbalex/vermehrung <reply@reply.github.com>
Datum: Dienstag, 1. Dezember 2020 um 11:48
An: barbalex/vermehrung <vermehrung@noreply.github.com>
Cc: Jasmin Menzi <menzi@toposmm.ch>, Author <author@noreply.github.com>
Betreff: Re: [barbalex/vermehrung] Fehlermeldung bei Erfassung neuer Person (#68)


O.k., werde dem nachgehen. Du muss jetzt aber die Operation löschen, sonst geht gar nichts mehr

**Comment by barbalex** [comment]
Sollte in Version 0.50.4 behoben sein. Danke für die Meldung, Sorry für den Fehler!
