### ISSUE TITLE
Fehlermeldung bei Kulturen nach Upload Foto

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/vermehrung#69]
Hoi Alex

Nachdem ich gestern bei einer Kultur ein Foto hochladen wollte, erschien diese Fehlermeldung, die trotz Ab- und Wiederanmeldung nicht wegging. Jetzt erscheint die Fehlermeldung bei jeder Kultur.
Könntest du dir das mal anschauen?
Vielen Dank!

![Bildschirmfoto 2020-12-02 um 18 22 34](https://user-images.githubusercontent.com/42208152/101058093-0f66fa80-358d-11eb-95e4-2f5ae58c35f2.png)

**Comment by jmenzi** [comment]
Bei mir leider das selbe. Ich kann keine Daten mehr eingeben. Wäre dringend, dass dieses Problem gelöst wird. Vielen Dank.

**Comment by barbalex** [comment]
Wenn ich Kulturen öffne, passiert das nicht.

Mit anderen Worten: dass es bei euch nun immer auftritt liegt am Zwischenspeicher bzw. Cache (der ein Problem hat, weil es einen Fehler gibt, den wir finden müssen).

Die provisorische Lösung ist daher, nicht nur ab- und wieder anzumelden. Sondern den ganzen cache zu leeren. Wie es vom Formular angeboten wird, siehe printscreen.

Aus eurer Beschreibung ist mir nicht ganz klar,  ob ihr auch den cache geleert habt. Habt ihr das?

Die dauerhafte Lösung, ist, den Fehler zu finden, den ihr ausgelöst habt, der zu einem korrupten cache geführt hat. Werde das selber versuchen und hoffe, ich kann es nachvollziehen.

**Comment by barbalex** [comment]
O.k., war ein ganz blöder Fehler im Code, d.h. von mir 😢 

Wird in Version 0.50.5 in ein paar Minuten korrigiert.

Sorry!

**Comment by jmenzi** [comment]
Perfekt, vielen Dank! Dann fange ich so in 20 min mit den Eingaben an :-)

**Comment by barbalex** [comment]
Die neue Version ist jetzt live. Wenn ihr neu startet, könnt ihr aktualisieren.
Ich konnte das übrigens nicht nachvollziehen, weil ich Kulturen öffnete, die keine Dateien hatten.
