### ISSUE TITLE
Gartenplan für die Gartenanlage in Wangen

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#7]
Sehr hilfreich wäre eine Art Schema, Übersicht für die Gartenanlage in Wangen, welche alle Beete, Kästen und Nr enthält. Quasi eine Skizze bei der man auf ein Beet klicken könnte und dann die entsprechenden Kulturen aufgelistet werden. Falls dies nicht möglich oder zu aufwendig ist, wäre es schon mal von Vorteil, wenn man bei der Gartenanlage ein pdf oder Foto herunterladen könnte, welches das Übersichtsschema zeigt.

**Comment by barbalex** [comment]
PDF/Foto geht gut.

Interaktives Schema ist ziemlich anspruchsvoll. Man müsste sozusagen alle Reihen digitalisieren und in einer Karte darstellen. Wäre möglich, aber ist es den Aufwand wert?

**Comment by barbalex** [comment]
Bei Garten und Kultur können jetzt Dateien abgelegt werden. Ich schliesse daher den Issue. 

Falls einmal räumliches Digitalisieren gewünscht würde: Ich werde für die Koordinaten-Felder PostGIS mit WGS84 einführen (wie bei apflora). Geometrien erfassen wäre danach möglich, wenn auch natürlich mit einigem Entwicklungsaufwand verbunden.
