### ISSUE TITLE
Anzeigefehler im Strukturbaum

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#71]
<img width="1672" alt="Bildschirmfoto 2020-12-07 um 10 47 42" src="https://user-images.githubusercontent.com/6448181/101335842-01112b00-387a-11eb-92c4-b85caab214f8.png">
Bei längerem Arbeiten werden die Infos im Strukturbaum plötzlich am falschen Ort angezeigt. Neuladen behebt den Fehler jeweils, aber er tritt immer wieder auf.

**Comment by barbalex** [comment]
Ich arbeite gerade seit Wochen parallel an einer neuen Version von vermehrung, ausgehend von https://github.com/barbalex/vermehrung/issues/47#issuecomment-725593086. 

Der Baum muss in der neuen Version anders aufgebaut werden. Das ist der eine Grund, warum in ein paar Wochen das Problem behoben werden könnte.

Der andere ist: Dieses Problem ist nicht einfach nachzuvollziehen. Und erscheint erst nach längerem Arbeiten. Möglicherweise früher bzw. später je nach Leistungsfähigkeit des verwendeten Geräts. Es könnte nämlich an der Arbeitsspeicherbelastung liegen. Die wiederum mit der künftigen Version stark reduziert werden sollte. Zumindest ist diese das Ziel.

**Comment by barbalex** [comment]
Version 1.0.0 ist live. Der Strukturbaum wird ganz anders aufgebaut. Bitte melde Fehler im Strukturbaum in einem neuen issue.
