### ISSUE TITLE
Konfliktmeldung - kann nicht behoben werden

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#72]
<img width="1657" alt="Bildschirmfoto 2020-12-07 um 12 12 09" src="https://user-images.githubusercontent.com/6448181/101344378-b09fca80-3885-11eb-9c3f-114d2d10a778.png">
Leider gibt es seit zwei Eingaben eine Konfliktmeldung, welche ich nicht bearbeiten kann. Auch Daten neu laden plus kann dies nicht beheben. Habe Angst, dass nun die Daten wieder nicht gespeichert werden. Bin gerade an einer intensiven Dateneingabe.

**Comment by jmenzi** [comment]
Konnte das Problem soweit lösen, dass ich den Datensatz gelöscht habe. Als ich dies gemacht habe, war eine ältere Version wieder automatisch da und der Konflikt ist verschwunden. Offenbar war der Datensatz zweimal vorhanden, aber er wurde nur einmal angezeigt und das Konfliktmanagement hat dies nicht erkannt.

**Comment by jmenzi** [comment]
Scheint etwas mit dem Datum zu tun haben. Bei der Eingabe blinkt kurz 2002 auf und verschwindet wieder. Danach steht 2020. Mit Löschen des aktuellen Datensatzes kann das Problem gelöst werden. Tritt aber offenbar systematisch bei irgendwelchen Voraussetzungen auf.

**Comment by jmenzi** [comment]
Passiert nur bei manueller Eingabe des Datums. Wählt man das Datum im Kalender aus, entsteht der Fehler nicht.

**Comment by barbalex** [comment]
Sollte in Version 1.0.0 nicht mehr passieren
