### ISSUE TITLE
Operationen werden in neuer Version nur lokal aber nicht online ausgeführt - Konfliktmeldung Offline Version

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#75]
Gilt für sämtliche Änderungen. Siehe Screenshots. Bei Abmeldung gehen alle Einträge verloren. 
![Bildschirmfoto 2021-01-11 um 09 48 27](https://user-images.githubusercontent.com/6448181/104161092-88f6d180-53f2-11eb-8b67-028cbf1424b3.png)
![Bildschirmfoto 2021-01-11 um 09 49 28](https://user-images.githubusercontent.com/6448181/104161096-8b592b80-53f2-11eb-8bae-eb99d7f069d1.png)

**Comment by barbalex** [comment]
Wow. Damit hätte ich nicht gerechnet. Das ist ganz schön zentral.

Eine abhängige Software hat bei einem Update das Verhalten der dafür wesentlichen Funktion undokumentiert verändert 😢 
Sorry, hab die Software zurück gestellt und muss nun für die neue Version die Programmierung ändern.

Aber ab der nun verfügbaren Version 1.0.7 funktioniert es wieder.

Sorry!

**Comment by barbalex** [comment]
Tröstlich ist: Offenbar habe ich gut erklärt, dass beim Abmelden in diesem Fall Daten verloren gingen.

**Comment by jmenzi** [comment]
Leider kann ich für die beiden Personen für welche ich ein Konto anlegen wollte kein Konto anlegen. 
Rene Bertiller und Francesca Helfer. Kann sein, dass es das irgendwie im Fehlermodus geschluckt hat und nun klappts nicht. Bei Personen, die ich während dieser Fehlermeldung nicht bearbeitet habe, kann ich problemlos ein Konto erstellen.

**Comment by barbalex** [comment]
Der Grund ist: Für die beiden existiert auf dem Auth-Provider nun schon ein Konto. Bloss vermehrung weiss nichts davon.
Zuerst versuche ich, dass das künftig nicht mehr passiert. Dann kann ich die Konten beim Auth-Provider löschen, worauf es wieder klappen wird.

**Comment by barbalex** [comment]
Nun habe ich das Verhalten des Authorisierung-Servers so angepasst, dass er in diesem Fall die nötigen Infos der schon existierenden Konten abfragt und an vermehrung.ch schickt. Du kannst also ab der neuen Version 1.0.8 die Konten wieder neu schaffen und es sollte klappen.

Bitte künftig für so was ein neues issue öffnen.
