### ISSUE TITLE
Fehler in der Anzeige des Strukturbaumes

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/vermehrung#76]
Hoi Alex

In der Datenbank werden teilweise nicht alle Untermenüs im Strukturbaum 
angezeigt (siehe Screenshot). Wenn die Datenbank/Webseite aktualisiert wird und die Daten neu geladen werden, erscheinen alle Untermenüs dann wieder. 

Könntest du dir diesen Fehler einmal anschauen, sodass wir die Datenbank nicht immer aktualisieren müssen?

Herzlichen Dank!
![Strukturbaum_Fehler_nach_Daten_neuladen_ok_210114](https://user-images.githubusercontent.com/42208152/104574808-c196e500-5656-11eb-8299-ca791b244d49.png)

**Comment by barbalex** [comment]
Wie kann man diese Verhalten provozieren? (Eine Voraussetzung, dass ich versuchen kann, den Fehler zu beheben, ist, dass ich ihn provozieren kann)

**Comment by praktikatopos** [comment]
Bei mir passiert es, wenn ich im Strukturbaum navigiere.

**Comment by barbalex** [comment]
Kannst du Muster erkennen? Zum Beispiel:

- nur in bestimmten Ästen des Navigationsbaums
- wenn (bestimmte) Filter gesetzt sind
- wenn in bestimmten Reihenfolgen navigiert wird
- erst nach x Minuten Arbeit
- nur oder bevorzugt, wenn zuvor:
  - gefiltert worden war
  - Daten exportiert wurden
  - Optionen verändert wurden
- ...

**Comment by praktikatopos** [comment]
Den Fehler konnte ich 1 min nach der Anmeldung provozieren. Einen anderen Filter als der Standardfilter (nur aktive Gärten/Personen/Kulturen) habe ich nicht gesetzt. Bei drei Arten habe ich die Kulturen und deren Lieferungen aufgemacht, bei der dritten Art (Gagea lutea) wurden bei den Kulturen dann die An-/Auslieferungen, Zählungen und Events nicht mehr angezeigt. Es scheint, dass die Lieferungen diesen Fehler provozieren. Auch wenn ich für einen Garten die Lieferungen der einzelnen Kulturen sehen möchte, erscheinen diese nicht richtig. Das gleiche passiert, wenn ich die Sammlungen einer Herkunft und dann die Auslieferungen anzeigen möchte. Häufig passiert der Fehler nicht beim ersten Mal Aufklappen, sondern wenn gleich danach etwas anderes angeklickt/aufgemacht wird.

**Comment by jmenzi** [comment]
![Fehler_Strukturbaum](https://user-images.githubusercontent.com/6448181/104919822-2aec6000-5997-11eb-8f31-f3cca6a3c99e.PNG)

Bei mir tritt der Fehler auch sofort auf, nachdem ich mich eingeloggt habe. Er betrifft alle Ebenden des Navigationsbaums.

**Comment by barbalex** [comment]
Sehr ärgerlich, dass ich das bisher nicht nachvollziehen kann

**Comment by barbalex** [comment]
Das waren schlicht Programmierfehler.

Der Code, der den Navigationsbaum aufbaut ist 2192 (!) Zeilen lang. Darin hatte es zwei sich zig-fach wiederholende systematische Fehler.

Es tut mir sehr leid, dass ihr so lange darunter leiden musstet 😞 

Hoffe, es ist nun in Version 1.1.4 behoben.
