### ISSUE TITLE
Doppelte Zwischenlager

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/vermehrung#77]
Hoi Alex

Zwischenlager in der Gartenanlage Wangen und im Kühlschrank topos werden z.T. nun doppelt (z.T. auch dreifach) angezeigt. Die Zwischenlager scheinen aber nicht kopiert worden zu sein. Denn es gibt Zwischenlager, die eine Anlieferung haben, das doppelte Zwischenlager jedoch nicht (z.B. Carex praecox, Zwischenlager topos Kühlschrank, AKE1071.57). Könntest du dir das einmal anschauen?

Herzlichen Dank!
![Doppelte_Zwischenlager](https://user-images.githubusercontent.com/42208152/105160099-1ed7de00-5b10-11eb-985c-facca1b5da49.PNG)

**Comment by barbalex** [comment]
Das passiert bei mir nicht.

Passiert es bei dir immer?
Auch (sofort) nach Neustart?
Auch (sofort) nach Neu-Anmeldung?

- In welchen Browser arbeitest du, in welcher Version?
- Was ist das für ein PC, auf dem du arbeitest:
  - Mac oder PC? 
  - Virtuelles Windows auf Mac? 
  - Wie alt ist er? 
  - Wieviel RAM (Arbeitsspeicher) hat er? 
- Kannst du einmal die Auslastung von Arbeitsspeicher und CPU prüfen?

**Comment by barbalex** [comment]
Nach aktuellem Stand des Wissens wird dies vermutlich derselbe Fehler sein, wie https://github.com/barbalex/vermehrung/issues/76

**Comment by barbalex** [comment]
In welchem Ast des Baums warst du im obigen Bild?

**Comment by barbalex** [comment]
> Die Zwischenlager scheinen aber nicht kopiert worden zu sein. Denn es gibt Zwischenlager, die eine Anlieferung haben, das doppelte Zwischenlager jedoch nicht (z.B. Carex praecox, Zwischenlager topos Kühlschrank, AKE1071.57)

Sorry, das habe ich nicht verstanden. Kannst du mir das bitte nochmals erklären?

**Comment by praktikatopos** [comment]
Die doppelten Zwischenlager sind gleich nach Anmeldung da, d.h. am besten sieht man sie, wenn der Filter der Kulturen auf "unbestimmt" gesetzt wird und man dann die Kulturen im Menü Arten anschaut (wie ich es im obigen Screenshot für Pulsatilla vulgaris gezeigt habe).

In manche Zwischenlager gab es schon Lieferungen und die sind auch noch drin. Nun gibt es z.T. auch Zwischenlager derselben Art und Herkunft ohne diese Lieferung (siehe Screenshots). Darum scheint es für mich so, als seien die Zwischenlager nicht kopiert worden, sondern vielleicht noch einmal neue generiert worden. 
![Bildschirmfoto 2021-01-20 um 13 59 40](https://user-images.githubusercontent.com/42208152/105179823-142a4280-5b2a-11eb-9653-e403fa34f47e.png)
![Bildschirmfoto 2021-01-20 um 13 58 21](https://user-images.githubusercontent.com/42208152/105179832-168c9c80-5b2a-11eb-8181-8f58575a0c0c.png)

Ich habe einen Fernzugriff auf den Büro-Mac, der 16 GB Arbeitsspeicher hat. Der Arbeitsspeicher ist mit 10.36 GB belegt, ca. 5-10 % des CPUs wird insgesamt benutzt. Google Chrome, Version 87.0.4280.141, benötigt max. 2 % CPU, ca. 150 MB Arbeitsspeicher.

**Comment by barbalex** [comment]
> wenn der Filter der Kulturen auf "unbestimmt" gesetzt wir

Es gibt vier Felder, wo ich mir denken kann, dass du "unbestimmt" meinen könntest, weil man "ja", "nein" oder keines davon wählen kann:
- gelöscht
- Zwischenlager
- Erhaltungskultur
- aktiv

Welches davon meinst du?

**Comment by praktikatopos** [comment]
> Es gibt vier Felder, wo ich mir denken kann, dass du "unbestimmt" meinen könntest, weil man "ja", "nein" oder keines davon wählen kann:
> 
> * gelöscht
> * Zwischenlager
> * Erhaltungskultur
> * aktiv
> 
> Welches davon meinst du?

Entschuldigung, ich habe die Einstellungen des Filters etwas ungenau beschrieben. 

- gelöscht: "nein"
- Zwischenlager: keines davon
- aktiv: keines davon

**Comment by barbalex** [comment]
Aha. Wenn man den Filter so wählt, dass _nicht-aktive_ Kulturen angezeigt werden, werden zum Teil viele ähnliche nicht aktive Kulturen sichtbar.

Nun ja, nichts hindert euch daran, beliebig viele nicht-aktive Kulturen zu schaffen. Es sind nicht die gleichen. Aber die darin erfassten und daher sichtbaren Daten sind gleich. Somit hat dieses Problem nichts mit den Fällen zu tun, in denen der Navigationsbaum Daten am falschen Ort anzeigt. Oder verdoppelt.

Wie  [dokumentiert](https://vermehrung.ch/Dokumentation/Kulturen#aktiv-vs-erloschen) hindert euch vermehrung.ch nur, mehrere _aktive_ Kulturen mit derselben Herkunft und Art in einem Garten zu schaffen.

Wenn du bei aktiv weder ja noch nein wählst, können somit  pro Garten:
- maximal ein Datensatz erscheinen, der eine aktive Kultur derselben Herkunft derselben Art darstellt
- beliebig viele nicht aktive Kulturen dieser Herkunft und Art

Was ich nicht verstehe: Wieso existieren zum Teil so viele inaktive Kulturen derselben Herkunft und Art im selben Garten? Wenn man eine neue Kultur schafft, ist der Wert im Feld "aktiv" auf "ja" voreingestellt.

**Comment by praktikatopos** [comment]
> Was ich nicht verstehe: Wieso existieren zum Teil so viele inaktive Kulturen derselben Herkunft und Art im selben Garten? Wenn man eine neue Kultur schafft, ist der Wert im Feld "aktiv" auf "ja" voreingestellt.

Für die GAW und der Kühlschrank topos werden meines Wissens automatisch Zwischenlager für jede Art und jede Herkunft generiert, um Lieferungen effizienter zu machen. Um eine bessere Übersicht zu erhalten, haben wir gewisse Zwischenlager dann inaktiviert. Aktiv würden sie erst wieder werden, wenn es eine neue Lieferung gibt. So kann es sein, dass so viele Zwischenlager inaktiv wurden. Wir haben aber keine neuen Zwischenlager erstellt. Darum erstaunt es uns auch, dass es so viele Zwischenlager hat...

**Comment by barbalex** [comment]
> Für die GAW und der Kühlschrank topos werden meines Wissens automatisch Zwischenlager für jede Art und jede Herkunft generiert, um Lieferungen effizienter zu machen

Ich glaube, hier liegt der Hund begraben 🤔 

Gehe dem nach.

**Comment by barbalex** [comment]
@praktikatopos @jmenzi

Der Trigger, der dafür sorgt, dass es für jede gesammelte Kombination von Art und Herkunft in den zwei Gärten GAW und Topos Kühlschrank immer ein aktives Zwischenlager gibt, hatte einen Fehler. Er hat `aktiv` nicht auf `true` gesetzt. (ist jetzt korrigiert)

Darum wurden in diesen zwei Gärten zu viele inaktive Zwischenlager geschaffen.

Ich werde eine Abfrage bauen, um aufzulisten, welche Zwischenlager vermutlich zu viel sind. Dann könnt ihr entweder von Hand die nicht benötigten löschen oder ich mache das mit dieser Abfrage. Sorry, das geht auf meine Kappe 😢. 

Ist aber auch grundsätzlich das Risiko bei so komplexen Vorgaben. Man denkt, man habe eine gute Idee und dann findet man leider allzu oft heraus, dass die komplexe Situation komplexer ist, als angenommen. 

Z.B. folgendes Problem: 

**Wenn ihr das Feld `aktiv` auf nein setzt, um "die Übersicht zu behalten", wird bei der nächsten Änderung einer Sammlung mit derselben Art und Herkunft automatisch wieder ein neues Zwischenlager mit `aktiv = true` gesetzt. Auch, wenn der Trigger keinen Fehler mehr hat.**

Der Automatismus kann unmöglich gewähren, dass es immer maximal ein aktives Zwischenlager gibt, wenn ihr das aktive Zwischenlager inaktiv setzt. Während er nicht wissen kann, wie viele inaktive es geben darf, weil die Anzahl inaktiver Kulturen sinnvollerweise nicht beschränkt ist.

Das würde (glaube ich) nur funktionieren, wenn wir noch eine Regel ergänzen: Es darf pro Art und Herkunft in diesen zwei Gärten maximal eine _inaktive_ Kultur geben. Fragt sich nur, wer danach noch weiss, dass es eine so detaillierte Regel gibt. Bzw. wer den komplexen Code versteht.

Oder ihr setzt die Zwischenlager nicht mehr inaktiv.

Sonst wird der Trigger auch künftig immer wieder neue aktive Zwischenvermehrungen schaffen.

Wieso setzt ihr denn die Zwischenlager inaktiv? Wenn ihr nur die Nicht-Zwischenlager sehen wollt, könnt ihr da nicht einfach einen Filter setzen, mit der Bedingung: Zwischenlager = Nein?
(Das würde allerdings Auswahllisten nicht beeinflussen. Z.B. wenn man in einer Lieferung eine Kultur wählt, wären immer noch alle aktiven Zwischenlager sichtbar. Ist dies euer Problem? In diesen Auswahllisten kann man aber mit Tippen filtern - würde das das Problem nicht lösen?)

Das wäre mir ehrlich gesagt viel lieber als einen noch komplexere Kombination von Daten-Bedingungen und Triggern zu bauen.

Oder wir schaffen diesen Automatismus wieder ab, der in _gewissen_ Gärten automatisch neue Zwischenlager schafft. Dabei ist es ganz schlecht, dass nur im Code aufgelistet ist, welche Gärten das sind (dem sagt man beim Programmieren eine "magische" Liste). Nun, das würde auch nichts ändern. Denn dann müsstet ihr diese Zwischenlager von Hand erstellen und das Problem der Übersicht wäre wieder dasselbe.

Eigentlich müssten wir bei den Gärten eine neue Eigenschaft ergänzen. Zum Beispiel so benannt: "Dieser Garten soll automatisch generierte Zwischenlager aller Kombinationen von Art und Herkunft enthalten". Dann gibt es keine im Code versteckte magische Liste mehr, die man rasch vergisst, später nicht mehr versteht und die nur der Entwickler ändern kann. Dafür haben wir die Benutzeroberfläche komplexer gemacht. Denn dieses neue Feld kann gewöhnliche Gärtner verwirren. Und sollte wohl nur von Managern verändert werden können. Wegen der potentiellen Verwirrung sollte es Nicht-Managern wohl nur angezeigt werden, wenn es auf Ja gesetzt wurde.

Zusammenfassung: Wir haben ein grundsätzliches Problem zu lösen, damit der Automatismus zuverlässig und nachvollziehbar funktionieren kann. Folgende Möglichkeiten:
- Neue Regel: In den Gärten, die Zwischenlager aller Herkünfte aller Arten haben sollen, darf es maximal ein inaktives Zwischenlager geben
- Zusätzlich die aktuell "magische" Liste explizit machen: Neues Feld bei Gärten, mit dem bestimmt wird, in welchen Gärten automatisch Zwischenlager für alle Herkünfte aller Arten geschaffen werden. Dieses Feld kann nur von Managern verändert werden. Und wird Nicht-Managern nur angezeigt, wenn Ja gewählt wurde (um sie nicht zu verwirren) (das hat zur Folge, dass die Trigger viel anspruchsvoller werden - aber das sollte ich schon hinkriegen)
- Oder: Zwischenlager werden nicht mehr inaktiv gesetzt. Wir finden eine andere Lösung, um die Übersicht in solchen Gärten zu behalten

**Comment by barbalex** [comment]
Hier die Liste der aktuell existierenden Zwischenlager aus den zwei Gärten mit Art und Herkunft:
[2021-01-21_zwischenlager.xlsx](https://github.com/barbalex/vermehrung/files/5848653/2021-01-21_zwischenlager.xlsx)

**Comment by barbalex** [comment]
Hinweis zur Liste: Vermutlich könnt ihr einfach im Feld `changed_by` die `NULL`-Werte filtern, um diejenigen Zwischenlager zu erhalten, welche vom Trigger geschaffen wurden.

**Comment by barbalex** [comment]
Ich habe nun diese Liste um ein Feld ergänzt: Wie oft die Kombination von Art und Herkunft im Garten existiert. Da die Liste eh nur Zwischenlager enthält, könnt ihr Filtern auf alle, die hier einen Wert > 1 haben.

Wenn ihr wollt, könnt ihr hier ein neues Feld einfügen und dort markieren, was ich mit einer Aktualisierungsabfrage löschen soll.

[2021-01-21_zwischenlager.xlsx](https://github.com/barbalex/vermehrung/files/5850036/2021-01-21_zwischenlager.xlsx)

**Comment by barbalex** [comment]
Zwischenlager, die man ausblenden möchte:
Hat keine Zählungen, Lieferungen und Events

**Comment by barbalex** [comment]
@praktikatopos @jmenzi
habe den Trigger jetzt ausgeschaltet. Es sollten also keine neuen Zwischenlager mehr geschaffen werden

**Comment by barbalex** [comment]
@praktikatopos @jmenzi

Das wird ja jetzt via https://github.com/barbalex/vermehrung/issues/81 gelöst.

Ich schliesse daher diesen Issue. Aber ich erwarte eigentlich noch, dass ich bei der Bereinigung der nun zuviel vorhandenen Kulturen wie oben (https://github.com/barbalex/vermehrung/issues/77#issuecomment-764693992) beschrieben helfe.

**Comment by praktikatopos** [comment]
> Ich schliesse daher diesen Issue. Aber ich erwarte eigentlich noch, dass ich bei der Bereinigung der nun zuviel vorhandenen Kulturen wie oben (#77 (comment)) beschrieben helfe.

Danke für die Liste. Es war relativ einfach, doppelte Zwischenlager herauszufiltern. Diese habe ich dann auch markiert. Jedoch wollen wir nun alle Zwischenlager der GAW und topos Kühlschrank löschen, die keine Lieferung, kein Event und keine Zählung erfasst haben. Sind leere Zwischenlager (ohne Event, Lieferung oder Zählung) diejenigen Kulturen, die in der Spalte R "parent_rev" der Excel-Tabelle den Wert NULL haben? Oder wie sind Events, Lieferungen etc. mit den Kulturen verknüpft?

**Comment by barbalex** [comment]
> Sind leere Zwischenlager (ohne Event, Lieferung oder Zählung) diejenigen Kulturen, die in der Spalte R "parent_rev" der Excel-Tabelle den Wert NULL haben?

nein

> Oder wie sind Events, Lieferungen etc. mit den Kulturen verknüpft?
https://vermehrung.ch/Dokumentation/Struktur/

Du siehst dieser Tabelle nicht an, wie viele Lieferungen, Events und Zählungen sie haben. Denn diese Information ist auf der n-Seite der Beziehung erfasst, also in den jeweiligen Tabellen.

Ich müsste die Abfrage erweitern um drei Feldern, in denen die jeweilige Anzahl berechnet wird.

Soll ich das machen?

**Comment by praktikatopos** [comment]
> Ich müsste die Abfrage erweitern um drei Felder, in denen die jeweilige Anzahl berechnet wird.
> 
> Soll ich das machen?

Das wäre super!

**Comment by barbalex** [comment]
Voilà:
[2021-02-08_zwischenlager.xlsx](https://github.com/barbalex/vermehrung/files/5944334/2021-02-08_zwischenlager.xlsx)

Ich habe im Excel-File bereits folgende Filter gesetzt:
- deleted = false
- anzahl_anlieferungen = 0
- anzahl_auslieferungen = 0
- anzahl_zaehlungen = 0
- anzahl_events = 0
- anzahl_teilkulturen = 0

**Comment by barbalex** [comment]
uups, ausser die Filter waren noch nicht gespeichert, bevor ich die Datei angehängt habe. Dann musst du sie bei Bedarf selber setzen

**Comment by praktikatopos** [comment]
Herzlichen Dank für die Tabelle! Die Filter waren noch drin ;)

Kannst du alle leeren Zwischenlager löschen? Ich habe sie in der letzten Spalte ("löschen") mit "1" markiert.

[2021-02-08_zwischenlager_ET.xlsx](https://github.com/barbalex/vermehrung/files/5945125/2021-02-08_zwischenlager_ET.xlsx)

**Comment by eveterzer** [comment]
Wenn ich es richtig gesehen habe, sind die leeren Zwischenlager in der GAW gelöscht. Danke dafür! Im topos Kühlschrank hat es aber noch leere Zwischenlager. Könntest du diese auch löschen? Wenn #81 umgesetzt wird, brauchen wir all die leeren Zwischenlager nicht mehr. So wird dann auch die Übersichtlichkeit deutlich besser.
