### ISSUE TITLE
Fehler Anzeige Zeit-Achse

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/vermehrung#78]
Hoi Alex

Die Übersichtszeitachse einer Art wird nicht mehr angezeigt (siehe Screenshot). Provozieren kann ich den Fehler, wenn ich mich anmelde, im Stammbaum unter Arten eine Art auswähle, dann die Zeit-Achse (für alle Herkünfte) öffne und dann mit dem Cursor über die Zeitachse fahre oder auch auf die Zeitachse klicke.

Könntest du dir das Problem anschauen? Herzlichen Dank.
![Bildschirmfoto 2021-01-21 um 09 46 07](https://user-images.githubusercontent.com/42208152/105327863-b8b29000-5bcf-11eb-8aa2-6b968e00f1c4.png)

**Comment by barbalex** [comment]
Danke für den genauen Beschrieb. Sollte in Version 1.1.2 gelöst sein
