### ISSUE TITLE
Fehlermeldung bei Ein- und Ausblenden von fakultativen Ordnern

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/vermehrung#79]
Hoi Alex

Neuerdings gibt es eine Fehlermeldung, wenn fakultative Ordner ein- oder ausgeblendet werden (siehe Screenshot, wo ich den Ordner "Zählungen" einblenden wollte). Könntest du dir das einmal anschauen?

Herzlichen Dank!
![Bildschirmfoto 2021-01-25 um 18 10 04](https://user-images.githubusercontent.com/42208152/105740217-45937b80-5f39-11eb-8f52-fa1d6064f010.png)

**Comment by barbalex** [comment]
Ich habe vor ein paar Wochen die Art geändert, wie gespeichert wurde, welche Qualitätskontrollen gewählt sind.

Dafür musste ich zwei neue Felder bei den Optionen schaffen. 

Und dabei habe ich vergessen, die Benutzerrechte zu erteilen.

(Vermehrung ist sehr strickt bei Benutzerrechten. Man sieht nur, was erlaubt ist.)

Ist jetzt korrigiert. Danke für die Meldung.
