### ISSUE TITLE
Interaktive Startseite zentral für Benutzerfreundlichkeit

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#8]
Die besprochene interaktive Startseite ist für uns zentral um die Datenbank auch benutzerfreundlich zu machen. So wie wir es verstehen, wird dies aber noch erledigt (Navigationsbaum ist interaktiv)?

**Comment by barbalex** [comment]
Wie genau stellst du dir das vor?

Wir brauchen einerseits etwas, das es ermöglicht zu jedem Datensatz zu navigieren.

Anderseits gibt es ev. Benutzergruppen, die nur ganz bestimmte Sachen können sollten bzw. von allem anderen nur verwirrt würden. Wie z.B. die Freiwilligen in apflora.

Kannst du versuchen, zu skizzieren:
- welche Benutzergruppen klar abgegrenzt werden können
- welche Funktionalitäten diese benötigen

Ausgehend davon können wir versuchen, die Anwendung benutzerfreudlicher zu machen.

**Comment by barbalex** [comment]
Beispiel Benutzerin x vermehrt Arten ihrem Garten: Sie braucht im Strukturbaum die Äste:
- Gärten (mit ihrem Garten / ihren Gärten)
- Personen, wo sie nur ihren eigenen Datensatz sieht

Alles andere wird nicht angezeigt. Damit sollte die Anwendung recht übersichtlich sein, nicht?

**Comment by jmenzi** [comment]
Login vor Benutzeroberfläche schalten. 
Dann nur Zugriff je nach Benutzergruppen:
-	Topos: Zugriff und Schreibrecht auf alles
-	Gartenanlage (Bernhard, allenfalls weitere) : Zugriff und Schreibrecht auf alles
-	Artverantwortliche:  Zugriff nur auf Artniveau nötig, Lieferscheine erstellen
-	Freiwillige ZV, Kommerzielle ZV :  Zugriff auf eigene Kulturen, eigenen Garten, Lieferscheine erstellen, Zählungen erfassen, Events erfassen

**Comment by barbalex** [comment]
abgelöst durch https://github.com/barbalex/vermehrung/issues/23
