### ISSUE TITLE
Formular Lieferung, Bereich "nach": Möglichkeit, neue Kultur anzulegen

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#81]
### Zweck

Wenn eine Lieferung an einen Garten erfasst wird, und festgestellt wird, dass im gewünschten Garten keine Kultur dieser Art mit dieser Herkunft existiert, ist es aufwändig, zuerst eine neue Kultur zu erstellen um danach die Lieferung abschliessen zu können.

### Benutzerführung

- [x] Um den Vorgang zu starten, gibt es rechts neben dem nach-Kultur-Feld eine Schaltfläche
- [x] Diese Schaltfläche ist nur aktiv, wenn in der Lieferung die Art erfasst ist und eine Herkunft ableitbar ist (weil im Bereich "von" eine Sammlung oder Kultur gewählt wurden)
- [x] Die Benutzerin wählt, ob die neue Kultur ein Zwischenlager sein soll oder nicht (davon hängt ab, aus welchen Gärten gewählt werden kann)
- [x] Die Benutzerin wählt den Garten.
    Zur Auswahl stehen Gärten, die noch nicht eine aktive Kultur dieser Art mit dieser Herkunft haben, das je nach Wahl Zwischenlager ist oder nicht
- [x] vermehrung erstellt die Kultur (mit: Art, Herkunft, aktiv = ja und Zwischenlager wie gewählt)
- [x] vermehrung setzt die nach-Kultur

**Comment by barbalex** [comment]
@jmenzi @praktikatopos
Wenn das so wie oben beschreiben für euch o.k. ist, beginne ich mit der Implementierung

**Comment by jmenzi** [comment]
Soweit ich dies beurteilen kann, ist das genau das, was ich gerne hätte. Also gerne entsprechend der Prioritäten umsetzen.

**Comment by barbalex** [comment]
> Stehen hier dann weiterhin auch jene Gärten/Kulturen zur Auswahl, bei denen bereits eine Kultur für die entsprechende Art und Herkunft erstellt ist?

Ja. Nur im Fenster, das sich öffnet damit die Benutzerin die neue Kultur anlegen kann, werden bestehende nicht angeboten. Denn es soll ja pro Garten und Art nur eine Kultur geben.

**Comment by barbalex** [comment]
In Version 1.4.0 implementiert

**Comment by Seraina1** [comment]
Danke für die bereits gemachten Implementierungen!

Zu diesem Issue habe ich noch eine Frage:

Wie du im  untenstehenden Bild siehst, müsste bei diesem Beispiel nun mit dem Plus ein Zusatzfenster geöffnet werden können um eine neue Kultur in der gewünschten Gärtnerei direkt erstellen zu können, oder?

![Bildschirmfoto 2023-04-24 um 09 34 39](https://user-images.githubusercontent.com/81672429/233930032-6837c9cc-9776-4e3d-b57a-6bd9aedc3ea2.png)

Abies alba habe ich eine Sammlung erstellt und möchte diese nun in eine Gärtnerei ausliefern. Dafür würde ich in der GAW gerne eine neue Kultur erstellen (die bereits bestehenden aktiven Beispiel-Kulturen von Abies alba habe ich dafür vorher gelöscht). Allerdings zeigt es mir weder beim Dropdown eine Gärtnerei an, noch kann ich das Plus anklicken und eine neue Kultur in der GAW über diesen Weg erstellen. Weisst du, wo hier der Knoten ist? Oder habe ich einen Denkfehler gemacht?

**Comment by barbalex** [comment]
Das war ein Fehler in der Logik des Codes. Ist in Version 1.5.1 korrigiert. Danke für die Meldung

**Comment by barbalex** [comment]
Sorry für die unüblich lange Reaktionszeit - wir waren in den Ferien

**Comment by Seraina1** [comment]
Auch ich komme (leider) erst jetzt dazu, mir deine Anpassungen in der Datenbank anzusehen.

Nach deiner Anpassung habe ich es nochmals versucht. Nun funktioniert es soweit. 
Allerdings ist mir aufgefallen, dass bei der Gärtnerei, bei der die neue Kultur erstellt wurde, der weitere Strukturbaum nicht mehr geöffnet werden kann bzw. er nicht aufgeklappt wird. Auch nicht, nachdem die Seite neu geladen wurde. Dies ist mir aber nur bei jenen Kulturen/Gärtnereien aufgefallen, bei denen eine erstmalige Lieferung dieser Art erfolgt. Sind bereits frühere Anlieferungen bei der entsprechenden Art und Gärtnerei erfasst, funktioniert soweit alles.
