### ISSUE TITLE
Bedarfsplanung klären

### ISSUE THREAD

**Issue by barbalex** [barbalex/vermehrung#83]
Ziele und Massnahmen klären. Damit eine vernünftige Bedarfsplanung möglich wird.

**Comment by jmenzi** [comment]
Die Bedarfsplanung muss integriert werden aus folgenden Gründen:

- Gärtner*innen wünschen sich bei Benutzung der Datenbank eine Unabhängigkeit von einer Excel-Tabelle
- Gärtner*innen können mobil jederzeit im Garten nachschauen, wie viel sie produzieren müssen
- Der automatisierte Export für die Bedarfsplanung soll auch den Bedarf enthalten, weshalb dieser in der Datenbank erfasst werden muss

ABER: 
- Artverantwortliche werden den Bedarf nicht selbst in die DB eingeben, dies werden nur die Manager machen
- Die Planung durch die AV wird in der Excel-Tabelle erfolgen, der Bedarf wird dann jedoch von der Koordinationsstelle in der Datenbank auf die einzelnen Gärten verteilt. 
- Der Übersichthalber wäre es aber trotzdem gut, wenn der Gesamtbedarf pro Herkunft in der Datenbank über die einzelnen Gärten summiert werden kann. 

Erläuterungen zum Bedarf:

- Der Bedarf wir jährlich erfasst, weshalb eine Erfassung pro Jahr nötig ist. Es werden jeweils das aktuelle Jahr, sowie zwei zukünftige Jahre erfasst. Beispielsweise wird 2021 der Bedarf für 2021 im Detail festgelegt sowie eine Schätzung für 2022 und 2023 abgegeben. Im Jahr 2022 wird die Schätzung für 2022 dann angepasst.

- Der Bedarf wird von den AV als Menge pro Art und Herkunft angegeben. Er kann beispielsweise folgende Werte annehmen:
  --> Samen
  --> 100 Pflanzen
  --> 20 bis 50 Pflanzen
  --> so viele wie möglich, maximal 100 Pflanzen
  --> Samen und 50 Pflanzen

- Der Bedarf muss zusammen mit dem aktuellsten Vermehrungsstand in einem Export exportiert werden. Der Export sollte übersichtlich sein und keine GUILDs enthalten. Gerne stellen wir die eine Vorlage bereit. 

- Exporte des aktuellen Standes inkl. Bedarf müssen sowohl für alle AP-Arten als Gesamtexport als auch für den einzelnen Garten möglich sein. 

- Wo der Bedarf erfasst und angezeigt werden soll (siehe Issue 88)

- Geplante Zählungen können aus der Datenbank entfernt werden, da diese mit der Bedarfsplanung nicht mehr gebraucht werden. Geplante Lieferungen bleiben jedoch aktuell und werden benötigt. 

- Allenfalls müsste man sich beim Export nochmals Gedanken darüber machen, wie der aktuellste Stand in einem Export möglichst gut berechnet werden kann. Wichtig ist sicher, dass er auf der letzten Zählung basiert. Inwiefern dann die Aus-Lieferungen automatisch abgezählt werden sollen oder einfach zur Information aufgelistet werden, da können wir gerne nochmals darüber reden.

**Comment by barbalex** [comment]
Deine Ausführungen sind sehr hilfreich. Und Grundlage dafür, es weiter auszuarbeiten.
Ich glaube, wir müssen die Aufgabe zweiteilen:

- Bedarfsplanung auf Ebene Kultur
- Bedarfsplanung auf Ebene Art-Herkunft

Ich glaube, wir (oder Seraina) müssten einmal eine Stunde reservieren, während der wir gemeinsam versuchen, das zu beschreiben. Dann etwas Zeit für die Reifung der Ideen lassen. Und danach wieder eine Stunde gemeinsam die Sache ausfeilen. Vielleicht wären wir dann schon fertig. Zumindest viel näher am Ziel.

**Comment by barbalex** [comment]
Vorgesehen gemäss Sitzung vom 13.4.2021:

- Topos: Ebene Kultur: Geplante Lieferungen werden erfasst
- Alex: Ebene Kultur: Geplante Lieferungen werden in der Grafik dargestellt
- Topos: Ebene Art-Herkunft: Planung erfolgt in Excel
- Alex: Ebene Art-Herkunft: Geplante Lieferungen werden dargestellt
- Alex: Export "aktueller Stand Kulturen für die Bedarfsplanung": Die geplanten Lieferungen werden dargestellt

**Comment by barbalex** [comment]
Geplante Lieferungen werden auf Ebene Kultur, Art und Art-Herkunft angezeigt. Auf Ebene Art und Art-Herkunft natürlich nur, wenn es sich um Auspflanzungen handelt (Grund: geplante Lieferungen zwischen Kulturen sind auf Ebene Art irrelevant).

**Comment by barbalex** [comment]
Ich schliesse den issue, da mein Teil umgesetzt ist
