### ISSUE TITLE
Verknüpfung von gelöschten Datensätzen noch vorhanden?

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/vermehrung#84]
Hoi Alex

Letzte Woche bei der Sitzung kam das Problem mit aktiven/inaktiven Datensätze auf. Ein Vorschlag war, Datensätze zu löschen, statt sie auf inaktiv zu setzen, da gelöschte Daten jederzeit wiederhergestellt werden können. Nun kam jedoch die Frage auf, was mit den verknüpften Daten dieses gelöschten Datensatzes passiert. Wenn ich also z.B. eine Person lösche, da sie nicht mehr aktiv vermehrt, verschwinden dann auch alle Lieferungen, die diese Person gemacht hat? Oder bleiben die Verknüpfungen bestehen?

Zentral ist diese Frage auch, wenn es um Teilkulturen geht. Teilkulturen sind eine sehr dynamische Sache und ändern sich ständig. Sie müssen daher häufig gelöscht werden. Was passiert mit den verknüpften Teilzählungen und Events? Können diese dann der Kultur als ganzes zugeordnet werden, bleiben diese für die Übersichten erhalten?

Danke für deine Rückmeldung

**Comment by barbalex** [comment]
Sieh dir mal die Datenstruktur an: https://vermehrung.ch/Dokumentation/Struktur/

Teilzählungen sind "Kinder" von Zählungen und damit von Kulturen. Löscht man eine Kultur, wird die Teilzählung grundsätzlich unsichtbar, obwohl sie in vermehrung.ch ebenso wie die Kultur, nicht gelöscht sondern bloss als gelöscht markiert wird. 

In Teilzählungen kann aber eine Teilkultur gewählt werden. Löscht man die Teilkultur, sollte sie auch in der Teilzählung nicht mehr sichtbar sein und kann bestimmt nicht mehr ausgewählt werden. Aber der Wert bzw. ihre ID ist immer noch im entsprechenden Feld "teilkutlur_id" enthalten. Er wird erst ersetzt, wenn eine andere Teilkultur gewählt wird. Weil Teilkulturen keine "Eltern" von Teilzählungen sind, beeinflusst ihre Löschung nicht die Sichtbarkeit der Teilzählung.

(Beziehungen werden eingeteilt in 1 und n. Die 1-Seite entspricht Eltern, die n-Seite den Kindern)

Genau das gleiche gilt für Events.

Analog ist es bei der Beziehung zwischen Lieferungen und Personen: Die Person wurde in der Lieferung gewählt. Ist sie gelöscht, ist sie vermutlich nicht mehr sichtbar und kann sicher nicht mehr gewählt werden. Aber ihre ID steht immer noch im Feld "person_id".

**Comment by jmenzi** [comment]
Lieber Alex, das verstehe ich nicht. Bitte rufe mich doch mal bei Gelegenheit an, ich glaube es ist einfacher, wenn du es mir kurz per Telefon erklärst. 
Grüsse, Jasmin

**Comment by jmenzi** [comment]
Der Grundsatz dieser Frage betrifft die Möglichkeit aktiv/inaktiv ersetzten zu können durch "gelöscht". Wichtig zu wissen ist hier zudem, ob ich die gelöschten Datensätze wieder herstellen und danach ist die Verknüpfung wieder drin und wieder angezeigt wird? Das wäre ja der Punkt bei aktiv, inaktiv...  Der Unterschied zu aktiv und inaktiv zu "löschen" ist ja, dass die Person z.B. einer Lieferung weiterhin angezeigt wird, auch wenn diese auf inaktiv gesetzt wird. Dies, da es durchaus noch interessant ist zu wissen, wer gewisse Sammlungen oder Lieferungen gemacht hat, auch wenn diese Person nicht mehr aktiv ist.

**Comment by barbalex** [comment]
Sorry, dass ich das zu wenig gut erklärt habe.

> Wichtig zu wissen ist hier zudem, ob ich die gelöschten Datensätze wieder herstellen und danach ist die Verknüpfung wieder drin und wieder angezeigt wird?

Wenn jemand in einem Auswahlfeld gewählt wurde und danach gelöscht wird, ist vermehrung.ch viele gnädiger als die meisten üblichen Apps, weil es eben nicht wirklich löscht. Was zur Folge hätte, dass die Person im Auswahlfeld verschwinden würde.

Die Person bleibt im Auswahlfeld sichtbar.

Das gilt für gelöscht genau so wie für aktiv.

Die Person kann aber nirgends mehr gewählt werden. Denn Auswahlfelder stellen nur aktive und nicht gelöschte Personen zur Verfügung. Will man diese Person an einem neuen Ort wählen können, muss man sie zuerst wieder aktiv setzen. Oder wenn sie gelöscht war: nicht gelöscht setzen.

Das gilt sinngemäss nicht nur für Personen sondern grundsätzlich für alle Datensätze, die in einem Auswahlfeld ausgewählt werden können.

**Comment by jmenzi** [comment]
Ok, jetzt verstehe ich es. Wir testen mal verschiedene Varianten aus. Aber so könnte man gewisse aktiv, inaktiv Attribute allenfalls weglassen. Wir melden uns aber nochmals, bevor wir hier weiter machen.
