### ISSUE TITLE
Springen innerhalb eines Ordners im Strukturbaum

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/vermehrung#85]
Hoi Alex

Wir haben bei der Sitzung von letzter Woche bereits angesprochen, nun habe ich mir das Problem mit dem Springen innerhalb des Strukturbaumes noch einmal genauer angeschaut. Ganz einfach zum Beschreiben ist der Fehler nicht, aber ich versuche es mal...
Nach der Anmeldung habe ich im Ordner "Arten" "Gentiana cruciata" mithilfe des Pfeiles auf- und wieder zugemacht. Das hat wunderbar ohne Springen geklappt. Als ich jedoch auf die Art geklickt habe, sodass die Art sich rot gefärbt hat, und ich den Datensatz noch einmal angeklickt habe, sprang die Anzeige nach oben zu Abies alba. Als ich dann wieder mit dem Pfeil eine andere Art aufmachen wollte, sprang die Anzeige dann auch zu Abies alba. Der Fehler hatte sich dann wie "eingeschlichen" und ging nicht mehr weg. Das Interessante ist jedoch, dass wenn ich danach die Art per Mausklick angewählt habe (wieder sodass die Art sich rot färbte), sprang der Strukturbaum innerhalb des Ordners nicht zu Abies alba, sondern die Anzeige im Strukturbaum sprang so, dass die eingefärbte Art am unteren Bildschirmrand erschien. Als ich dann ein zweites Mal auf die aufgeklappte Art klickte, sprang die Anzeige nach oben zu Abies alba.

Ich hoffe, du kannst den Fehler mit dieser Beschreibung nachvollziehen. Mir scheint, als gäbe es einen Unterschied zwischen Aufklappen per Mausklick auf die Pfeile und per Mausklick auf den Datensatz selber, so dass der Datensatz/Teil des Strukturbaumes rot wird. 
![Bildschirmfoto 2021-02-03 um 14 09 03](https://user-images.githubusercontent.com/42208152/106751762-f11f8880-6629-11eb-887a-64cd37ad15cd.png)

**Comment by barbalex** [comment]
> Mir scheint, als gäbe es einen Unterschied zwischen Aufklappen per Mausklick auf die Pfeile und per Mausklick auf den Datensatz selber, so dass der Datensatz/Teil des Strukturbaumes rot wird

Richtig, den gibt es: Der entsprechende Datensatz wird aktiv gesetzt und somit auch im Formular angezeigt (oder die entsprechende Liste, wenn es sich um einen Ordner handelt).

Das löst aus, dass der Baum neu gezeichnet wird. Was wiederum Springen erklären könnte.

Ich kann jetzt gerade nicht aber werde bei Gelegenheit nachgehen. Danke für die gute Schilderung.

**Comment by barbalex** [comment]
Ich kann es jetzt nachvollziehen. Und finde auch, dass es besser sein müsste. Noch habe ich keine Ahnung, wie ich das verhindern kann. Aber ich werde es versuchen.

**Comment by barbalex** [comment]
In Version 1.1.8 sollte das nicht mehr passieren.

Dem Navigationsbaum wurde jeweils ein Knoten übergeben. Damit der Baum sicherstellen kann, dass er im sichtbaren Bereich liegt. Ist z.B. wichtig, wenn man das Projekt via einen Link in einem bestimmten Datensatz öffnen will. Liegt der gewünschte Knoten nicht im sichtbaren Bereich, springt der Baum so weit, bis er (am unteren Rand) sichtbar wird.

Der Fehler war: Übergeben wurde der Knoten des sogenannt "aktiven" Datensatzes. Also desjenigen, dessen Formular gerade angezeigt wird. Und der deshalb im Navigationsbaum rot hervorgehoben ist. Es sollte aber der Knoten des zuletzt geklickten Knotens sein. 

Und das Problem ist: Wenn du auf den Pfeil klickst wird der geklickte Datensatz nicht aktiv (er wird nicht rot und sein Formular wird nicht angezeigt - es wird lediglich der Knoten geöffnet). Der Baum wird aber neu aufgebaut und springt zum aktiven Datensatz, falls der nicht im sichtbaren Bereich liegt. Anstatt zum zuletzt geklickten (zu dem er gar nicht springen muss, weil er im sichtbaren Bereich liegt).

Ich habe daher die Programmierung so geändert, dass der Baum wenn er springen muss zum zuletzt geklickten springt.

Danke für den wertvollen Hinweis. Wie du auch bemerkt hast gibt es den genau gleichen Fehler in apflora. Somit werde ich es dort auch noch korrigieren.

**Comment by barbalex** [comment]
Ist in Version 1.62.12 von apflora auch behoben
