### ISSUE TITLE
Algenart Nitella hyalina in Datenbank integrieren

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/vermehrung#86]
Hoi Alex

Diese Erweiterung muss nicht gleich angegangen werden. Ich deponiere einmal ein Issue, damit wir es nicht vergessen.

Bisher ist die Datenbank auf die Erfassung von Pflanzen ausgelegt. Algenarten, wie z.B. die Aktionsplanart Nitella hyalina, können noch nicht erfasst werden. Der Artverantwortliche von Nitella hyalina, Arno Schwarzer, hätte jedoch Interesse, dass die Zwischenvermehrung von Nitella in der Datenbank dokumentiert wird. Wir müssten uns bei Gelegenheit überlegen, wie die Integration von Algenarten möglich wird.

**Comment by barbalex** [comment]
Wie wir mittlerweile wissen, setzt das voraus, dass die FNS das verlangt. Denn ohne spürbaren Aufwand wird das nicht gehen

**Comment by jmenzi** [comment]
Lieber Alex
Kannst du den spürbaren Aufwand bitte quantifizieren? Wie viel kostet die Integration von Nitella hyalina?
Besten Dank. Grüsse, Jasmin

**Comment by barbalex** [comment]
Das Problem lag bei arteigenschaften.ch. Eine Voraussetzung, dass vermehrung.ch auf die dort schon existierende Art zugreifen kann, war nicht gegeben. Glücklicherweise bin ich für arteigenschaften.ch zuständig. Die Anpassung hat jetzt 1.5 Stunden gekostet. Was ich nun gratis gemacht habe, da ich dafür keinen Auftrag habe. Gemacht habe ich es, weil die Zeit um herauszufinden, wie es funktionieren würde, nur ca. 15 Minuten weniger lange gewesen wäre, als es gleich zu machen.
