### ISSUE TITLE
Strukturbaum - Struktur anpassen

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#88]
Der Strukturbaum ist grundsätzlich gut, jedoch fehlt eine gewisse Übersicht beim Ausklappen der Äste. Hier erscheinen lange Listen mit viel Information. Diese Informationen müssten irgendwie gebündelt und übersichtlicher dargestellt werden können. Wir erarbeiten aktuell gerade einen Vorschlag, welchen wir dir bald unterbreiten werden. Dazu noch eine Rückfrage, wie einfach ist es neue Unteräste einzufügen? Beispielsweise eine Gruppierung gewisser Daten nach Jahreszahl, Gemeinde oder Art?

**Comment by barbalex** [comment]
Also grundsätzlich: sehr schwierig. Das Problem ist, dass der Strukturbaum von der URL abhängig ist und umgekehrt. Die URL ist ein zentrales Element der App. Da hängt vieles zusammen. 

Bei apflora haben wir an einem einzigen Ort etwas Ähnliches: wo die Ziele pro Jahr zusammengefasst werden. Das hat geschätzt:
- 15 mal mehr Arbeit für die Erst-Implementation gegeben, als "normale" Strukturen
- Haufenweise Probleme, die später (oft nur von mir) entdeckt und behoben wurden
- Wenn ich raten müsste, wo am ehesten noch unbemerkte/nicht gemeldete Probleme liegen: ich würde auf diesen Knoten tippen
- Ich hatte schon mehrmals Ideen, wie der Aufbau des Baums modularisiert werden könnte. Das wäre die Methode, um die Menge benötigten Codes drastisch zu reduzieren. Und das Hinzufügen neuer Äste zu vereinfachen. Aber das ist nur machbar, wenn der Baum natürliche Strukturen innerhalb der Daten abbildet. Die von dir jetzt erwähnten sind das nicht. Im Fall von apflora scheiterte das an dem erwähnten Knoten
- Ich kann dir nicht sagen, wie oft ich es bereut habe, dass wir das so implementiert haben

Ein Beispiel, dass durch die Gruppierung von Listen nach dem Inhalt einzelner Felder VIEL schwieriger (und damit auch leistungshungriger) wird: Filtern.
Wenn ihr einen Filter setzt, ist es sehr aufwändig, die gruppierte Liste zu filtern. Wenn ihr z.B. nach Jahr gruppiert. Und dann nach etwas anderem filtert: Dann muss zunächst mal herausgefunden werden, welche Jahre im gefilterten Satz von Listen-Elementen existieren. Bevor der Navigationsbaum aufgebaut werden kann. Ist der Baum nach logischen Einheiten der Datenstruktur aufgebaut, kann man hingegen einfach den Filter übernehmen, der auf dieser Tabelle gesetzt wurde. Womit sich die ganze Filtrierung modularisieren lässt, was sie heute auch ist. Und sonst nicht möglich wäre.

Grundsätzlich ist der Navigationsbaum ein RIESENDING:
- Der Code, der seinen Aufbau steuert, ist [hier](https://github.com/barbalex/vermehrung/blob/master/src/components/Tree/nodes/index.js) enthalten. Schau mal, wie viele Zeilen das sind: 2'192!
- Dazu kommt Code für jeden Knoten im Baum, also so viele Dateien, wie es Knoten gibt. Dieser Code ist oft nur 15 bis 30 Zeilen lang. Aber das läppert sich zusammen. Da es offenbar 91 Knoten gibt, dürfte das noch mehr Code sein, als oben erwähnt
- Zusätzlich gibt es Code, der den Zustand des Baums verwaltet (welche Knoten sind sichtbar, welche sind aktiv, welche sind im aktiven Strang)

Nicht zu vergessen: Jede zusätzliche Stufe bedingt auch zusätzliche Listenformulare, weil man mobil auch ohne den Navigationsbaum navigieren können soll.

Plus: zusätzliche Stufen heissen auch: Mehr Klicken (statt Scrollen oder Filtern), um zum Ziel zu kommen. Bzw. in der Mobilansicht: mehr Formulare, durch die man sich bewegen muss.

Änderungen wollen daher gut überlegt sein. Und finanziert. Machbar ist hingegen vermutlich fast alles. Zumindest kannst du sagen, was ihr ideal fändet. Und ich kann überlegen, ob es einen vernünftigen Weg gibt, das zu implementieren.

Wir sollten offen sein, auch andere Lösungen zu finden. Daher ist es wichtig, dass ihr klar ausdrückt, was aktuell mühsam ist. Dazu ist es wichtig zu wissen, wie ihr arbeitet. Und wir offen überlegen, wie das verbessert werden kann. Und ich darum auch mitdenken kann. Denn mir fällt vielleicht etwas ein, an das ihr nicht denkt.

Spontan habe ich den Eindruck: Am Einfachsten wäre es, wenn die Filterung dafür optimiert werden könnte. Aber ich greife schon vor, was gefährlich ist.

**Comment by jmenzi** [comment]
Trotz Filterfunktion braucht es noch eine Anpassung der Struktur auf Artniveau und Herkunftsniveau um die App besser intuitiv navigierbar zu machen. Hier unser Vorschlag dazu:

>   Arten
>> Abies alba
>>> Sammlungen
* Herkunft: Höri, Reben; ZHHK1021.53
** 2020.01.02; Regula Dickenmann
** 2019.05.23; Jasmin Menzi
*** Auslieferungen
****2019.05.23; Jasmin Menzi
****2018.08.02; Karin Marti
* Unterterzen, Bahnstation; ZHHK1302.25
***2016.02.23; Evelyn Terzer
***2015.03.06; Karin Marti
>>> Kulturen
*Höri, Reben; ZHHK1021.53
** Jasmins Garten
*** Zählungen
*** Anlieferungen
*** Auslieferungen
*** Events
*** Bedarf (siehe auch Issue 83, bitte separat diskutieren)
** Evelyns Garten
>>> Bedarf (siehe auch Issue 83, bitte separat diskutieren)
* 2021
* * Höri; Reben --> Gesamtbedarf
* * * Jasmins Garten --> Bedarf pro Garten  - optional, da nicht für alle nötig, wenn z.B. nur Samen gebraucht werden, dann überall Samen)
* * * Evelyns Garten ---> Bedarf pro Garten
* 2020
* 2019

> Herkünfte (auch über Filter lösbar - nice to have, in jedem Fall aber Herkünfte mit Namen anschreiben)
>> Gemeindename: Höri
*Höri, Äustler; ZHHK1321.23
** Sammlungen
***1.2.2020; Jasmin   Menzi
** Höri, Reben; ZHHK1231.23
 
> Sammlungen (so belassen für Filterfunktion)
 
> Gärten
Struktur ok, bei Kulturname bitte auch Herkunftsname angeben, falls zu lange eher Nummer weglassen, Herkunft für  Gärtner verbergen kann abgeschalten werden.
Bedarf kommt auch hier hinein (siehe  Issue 83 und Issue 63)
 
> Kulturen (so belassen für Filterfunktion)
 
> Teilkulturen (Sortierung gemäss effektiver räumlicher Reihenfolge - hier Achtung 1 kommt vor 10 und 10 kommt nach 9)
 
> Zählungen  (so belassen für Filterfunktion)
 
> Lieferungen (so belassen für Filterfunktion)
 
> Events (so belassen für Filterfunktion)
 
> Personen (ok)

**Comment by barbalex** [comment]
Sorry, ich habe keine Ahnung, was du willst. Kannst du bitte versuchen, es anders zu erklären?

**Comment by barbalex** [comment]
Falls du Mühe hast, in markdown (dem Format, mit dem Issues geschrieben werden) etwas grafisch darzustellen: Du kannst es in Word oder Excel machen, dann als Bild kopieren und hier einfügen.

**Comment by jmenzi** [comment]
Beim Strukturbaum unter Arten möchte ich gerne bei den Sammlungen eine Gruppierung nach Herkünften
[Uploading Wunschliste_ZV_DB_20210208.pdf…]()
.

**Comment by barbalex** [comment]
Ich bin nicht sicher, was der Link zu Issue 88 soll, der mit "Uploading Wunschliste_ZV_DB_20210208.pdf…" beschriftet ist. Da hat wohl etwas nicht geklappt.

> Beim Strukturbaum unter Arten möchte ich gerne bei den Sammlungen eine Gruppierung nach Herkünften

Ansonsten ist das genau https://github.com/barbalex/vermehrung/issues/50. Oder habe ich da etwas falsch verstanden?

**Comment by jmenzi** [comment]
Dokument folgt per Mail - pdfs mag GitHub offenbar nicht.

**Comment by barbalex** [comment]
Ich habe jetzt nochmals ziemlich lange versucht, deine Darstellung eines besseren Navigationsbaums zu verstehen. Noch verstehe ich nicht alles. Aber ich habe den Eindruck, dass es aufschlussreich sein könnte, das zusammen zu besprechen, Ast für Ast. Und dabei nochmals hoffentlich für beide verständlich zu beschreiben.

Denn ich glaube, die Art, wie du es gerne darstellen möchtest, sagt viel darüber aus, wie ihr arbeitet. Beziehungsweise: Wer wie arbeitet (AV, Gärtner...).

Es könnte uns auch helfen, die Bedarfsplanung besser zu verstehen. Es könnte daher nützlich sein, die von dir gewünschte Darstellung der Bedarfsplanung im Navigationsbaum für https://github.com/barbalex/vermehrung/issues/83 zu besprechen.

Ich habe mich oben stark gewehrt dagegen, Daten nach Feldinhalten zu gruppieren. So was habe ich aber in deinem Beispiel gar nicht gefunden. Scheint also nicht ein grosses Problem zu sein. Es scheint eher darum zu gehen, den Baum so zu strukturieren, wie gearbeitet wird.

Ich glaube daher, es wäre sehr nützlich, gemeinsam eine Stunde zu reservieren, um den idealen Navigationsbaum zu diskutieren.

**Comment by barbalex** [comment]
Ich habe nun versucht, deinen Navigationsbaum mit den korrekten Einzügen darzustellen:
```js
Arten
  Abies alba
    Sammlungen
      Herkunft: Höri, Reben; ZHHK1021.53
        2020.01.02; Regula Dickenmann
        2019.05.23; Jasmin Menzi
          Auslieferungen
            2019.05.23; Jasmin Menzi
            2018.08.02; Karin Marti
      Unterterzen, Bahnstation; ZHHK1302.25
        2016.02.23; Evelyn Terzer
        2015.03.06; Karin Marti
    Kulturen
      Höri, Reben; ZHHK1021.53
        Jasmins Garten
          Zählungen
          Anlieferungen
          Auslieferungen
          Events
          Bedarf // siehe auch Issue 83, bitte separat diskutieren
        Evelyns Garten
    Bedarf // siehe auch Issue 83, bitte separat diskutieren
      2021
        Höri; Reben // Gesamtbedarf
          Jasmins Garten // Bedarf pro Garten - optional, da nicht für alle nötig, wenn z.B. nur Samen gebraucht werden, dann überall Samen)
          Evelyns Garten // Bedarf pro Garten
      2020
      2019

Herkünfte // auch über Filter lösbar - nice to have, in jedem Fall aber Herkünfte mit Namen anschreiben
  Gemeindename: Höri
    Höri, Äustler; ZHHK1321.23
      Sammlungen
        1.2.2020; Jasmin Menzi
    Höri, Reben; ZHHK1231.23
 
Sammlungen // so belassen für Filterfunktion
 
Gärten
// Struktur ok, bei Kulturname bitte auch Herkunftsname angeben
// falls zu lange eher Nummer weglassen, Herkunft für Gärtner verbergen kann abgeschalten werden.
// Bedarf kommt auch hier hinein (siehe Issue 83 und Issue 63)
 
Kulturen // so belassen für Filterfunktion
 
Teilkulturen // Sortierung gemäss effektiver räumlicher Reihenfolge - hier Achtung 1 kommt vor 10 und 10 kommt nach 9
 
Zählungen  // so belassen für Filterfunktion
 
Lieferungen // so belassen für Filterfunktion
 
Events // so belassen für Filterfunktion
 
Personen // ok
```
(Dafür habe ich ihn in einen Code-Block gesetzt. Und als Javascript bezeichnet, damit Kommentare grau erscheinen. Als Nebenwirkung gibt es weitere Farben, die man halt ignorieren muss)

Entspricht das der Struktur, die du dir vorgestellt hast?

**Comment by jmenzi** [comment]
Ja, genau das wärs. So wäre an Benutzerfreundlichkeit bereits Einiges gewonnen. Es generiert zwar mehr Klicks, jedoch sind die Zeilen im Strukturbaum sonst zu lange. Einfügen des Bedarfs wie erwähnt noch zu diskutieren an anderer Stelle.

**Comment by barbalex** [comment]
O.k.

Zu diesem Ausschnitt:

```js
Arten
  Abies alba
    Sammlungen
      Herkunft: Höri, Reben; ZHHK1021.53
        2020.01.02; Regula Dickenmann
        2019.05.23; Jasmin Menzi
      Unterterzen, Bahnstation; ZHHK1302.25
        2016.02.23; Evelyn Terzer
        2015.03.06; Karin Marti
```
Hier schaffst du einen Ast "Sammlungen". Der dann die Sammlungen pro Herkunft auflistet.
Wäre es nicht logischer, in einem Ast "Herkünfte" die "Sammlungen" aufzulisten?


```js
Arten
  Abies alba
    Herkünfte
      Höri, Reben; ZHHK1021.53
        Sammlungen
          2020.01.02; Regula Dickenmann
          2019.05.23; Jasmin Menzi
      Unterterzen, Bahnstation; ZHHK1302.25
        Sammlungen
          2016.02.23; Evelyn Terzer
          2015.03.06; Karin Marti
```
Jedenfalls wäre das eine mögliche Implementation (denn sie entspricht den Beziehungen zwischen den Daten).

**Comment by barbalex** [comment]
Entsprechend könnte man dasselbe machen für die Kulturen.

Statt:
```js
Arten
  Abies alba
    Kulturen
      Höri, Reben; ZHHK1021.53
        Jasmins Garten
        Evelyns Garten
```

Das:
```js
Arten
  Abies alba
    Herkünfte
      Höri, Reben; ZHHK1021.53
        Kulturen
          Jasmins Garten
          Evelyns Garten
```

Kombiniert mit den Sammlungen gäbe das:
```js
Arten
  Abies alba
    Herkünfte
      Höri, Reben; ZHHK1021.53
        Sammlungen
          2020.01.02; Regula Dickenmann
          2019.05.23; Jasmin Menzi
        Kulturen
          Jasmins Garten
          Evelyns Garten
```

**Comment by barbalex** [comment]
Und kombiniert mit dem Bedarf:

```js
Arten
  Abies alba
    Herkünfte
      Höri, Reben; ZHHK1021.53
        Sammlungen
          2020.01.02; Regula Dickenmann
          2019.05.23; Jasmin Menzi
        Kulturen
          Jasmins Garten
          Evelyns Garten
        Bedarf // siehe auch Issue 83, bitte separat diskutieren
          2021
            Gesamt
            Jasmins Garten // Bedarf pro Garten - optional, da nicht für alle nötig, wenn z.B. nur Samen gebraucht werden, dann überall Samen
            Evelyns Garten
          2020
          2019
      Unterterzen, Bahnstation; ZHHK1302.25
        Sammlungen
        Kulturen
        Bedarf
```

**Comment by jmenzi** [comment]
I get your point - macht es einfacher und vermeidet Doppelspurigkeiten. Jedoch möchte ich kurz mit Rebecca als AV Rücksprache halten, da ich mir nicht sicher bin, ob sie gerne alle Kulturen der gleichen Art in einer Liste haben möchte.

**Comment by barbalex** [comment]
```js
Herkünfte // auch über Filter lösbar - nice to have, in jedem Fall aber Herkünfte mit Namen anschreiben
  Gemeindename: Höri
    Höri, Äustler; ZHHK1321.23
    Höri, Reben; ZHHK1231.23
```

Das wäre nun doch noch eine Gruppierung nach einem Feld innerhalb der Herkünfte. Wie gesagt möchte ich das vermeiden.

Im Namen der Herkünfte ist die Gemeinde vorangestellt. Die Liste mag zwar lang sein. Sie ist aber nach der Gemeinde sortiert, das heisst mit ganz kurzem Scrollen findet man problemlos die gesuchte Gemeinde. Daher würde ich Anderes priorisieren (wie du selber sagst).

> in jedem Fall aber Herkünfte mit Namen anschreiben

Das ist kein Problem.

**Comment by barbalex** [comment]
> in jedem Fall aber Herkünfte mit Namen anschreiben

Der Name ist ja schon drin. 

Hast du etwa eher gemeint, dass die Nummer nicht mehr erscheinen sollte? 

Oder meintest du, dass in _anderen_ Ästen des Strukturbaums Herkünfte ohne Ort und Lokalname erscheinen und dass sie dort auch erscheinen sollten?

Zwei Bemerkungen dazu:
- In anderen Ästen ist die Herkunft nur ein Teil dessen was angezeigt wird. Ort und Lokalname ergänzen heisst auch, dass die Bezeichnung viel länger (und damit weniger übersichtlich) wird
- Soviel ich wiess wollt ihr, dass Ort und Lokalname den Gärtnern nicht angezeigt werden 
  Ich wollte das umsetzen, bin aber auf technische Probleme in einem wesentlichen Werkzeug gestossen. Die Entwickler dieses Werkzeugs arbeiten daran, diese Fähigkeit zu ergänzen. Ich kann daher nicht sagen, wie bald es möglich sein wird. Aber vermutlich innert weniger Wochen/Monate

**Comment by jmenzi** [comment]
Zur  Herkunftsfrage allgemein habe ich ein neues Issue eröffnet. Ich sehe das Problem für diese Einteilung. Wenn die Herkünfte nicht genau bekannt sind, ist auch keine Anpassung des Strukturbaumes entsprechend der Herkünfte möglich. Wir müssen dies nochmals besprechen.

**Comment by jmenzi** [comment]
> Wäre es nicht logischer, in einem Ast "Herkünfte" die "Sammlungen" aufzulisten?
> 
> ```js
> Arten
>   Abies alba
>     Herkünfte
>       Höri, Reben; ZHHK1021.53
>         Sammlungen
>           2020.01.02; Regula Dickenmann
>           2019.05.23; Jasmin Menzi
>       Unterterzen, Bahnstation; ZHHK1302.25
>         Sammlungen
>           2016.02.23; Evelyn Terzer
>           2015.03.06; Karin Marti
> ```
> 
> Jedenfalls wäre das eine mögliche Implementation (denn sie entspricht den Beziehungen zwischen den Daten).

Ja, dies wäre so sicher sehr hilfreich. Neu sind ja die Herkünfte bei den Arten bereits aufgeführt. Dies hat aber bereits zu Verwirrungen geführt, weil man dort die Sammlungen nicht sehen kann. Ich denke diese Umsetzung wäre deshalb sehr sinnvoll.

**Comment by jmenzi** [comment]
> I get your point - macht es einfacher und vermeidet Doppelspurigkeiten. Jedoch möchte ich kurz mit Rebecca als AV Rücksprache halten, da ich mir nicht sicher bin, ob sie gerne alle Kulturen der gleichen Art in einer Liste haben möchte.

Rebecca als AV wäre mit dieser Variante auch einverstanden.

**Comment by jmenzi** [comment]
> ```js
> ```js
> Herkünfte // auch über Filter lösbar - nice to have, in jedem Fall aber Herkünfte mit Namen anschreiben
>   Gemeindename: Höri
>     Höri, Äustler; ZHHK1321.23
>     Höri, Reben; ZHHK1231.23
> ```
> 
> 
> Das wäre nun doch noch eine Gruppierung nach einem Feld innerhalb der Herkünfte. Wie gesagt möchte ich das vermeiden.
> Im Namen der Herkünfte ist die Gemeinde vorangestellt. Die Liste mag zwar lang sein. Sie ist aber nach der Gemeinde sortiert, das heisst mit ganz kurzem Scrollen findet man problemlos die gesuchte Gemeinde. Daher würde ich Anderes priorisieren (wie du selber sagst).
> ```

Wenn eine solche Gruppierung schwierig umzusetzen ist, können wir im Moment auch darauf verzichten. Hilfreich ist, dass mit dem neuen Aufbau die Herkunftsbezeichnungen in den Kulturen und den Sammlungen nicht mehr nötig sind, da diese ja durch den Ast Herkünfte abgedeckt sind und nicht nochmals wiederholt werden müssen. Dadurch wird der einzelne Ast übersichtlicher.

**Comment by jmenzi** [comment]
> Zur Herkunftsfrage allgemein habe ich ein neues Issue eröffnet. Ich sehe das Problem für diese Einteilung. Wenn die Herkünfte nicht genau bekannt sind, ist auch keine Anpassung des Strukturbaumes entsprechend der Herkünfte möglich. Wir müssen dies nochmals besprechen.

Entsprechend wäre im Strukturbaum für Gärtner jeweils nur der Ort sichtbar, für AV und Manager aber die Bezeichnung Ort und Lokalname.

**Comment by barbalex** [comment]
Entscheid Herkünfte, Sitzung vom 13.4.2021: Gärtner sollen Gemeinde und Nr. sehen

**Comment by Seraina1** [comment]
> Entscheid Herkünfte, Sitzung vom 13.4.2021: Gärtner sollen Gemeinde und Nr. sehen

Entspricht Issue #97 
Demnach bereits erledigt?

**Comment by barbalex** [comment]
> Entspricht Issue https://github.com/barbalex/vermehrung/issues/97
> Demnach bereits erledigt?

Nein, siehe meine Bemerkung dort

**Comment by Seraina1** [comment]
> 






> Und kombiniert mit dem Bedarf:
> 
> ```js
> Arten
>   Abies alba
>     Herkünfte
>       Höri, Reben; ZHHK1021.53
>         Sammlungen
>           2020.01.02; Regula Dickenmann
>           2019.05.23; Jasmin Menzi
>         Kulturen
>           Jasmins Garten
>           Evelyns Garten
>         Bedarf // siehe auch Issue 83, bitte separat diskutieren
>           2021
>             Gesamt
>             Jasmins Garten // Bedarf pro Garten - optional, da nicht für alle nötig, wenn z.B. nur Samen gebraucht werden, dann überall Samen
>             Evelyns Garten
>           2020
>           2019
>       Unterterzen, Bahnstation; ZHHK1302.25
>         Sammlungen
>         Kulturen
>         Bedarf
> ```

Den Vorschlag würde ich im 2023 gerne weiterverfolgen. Allerdings ohne den Ast "Bedarf". Issue #83 wurde ja bereits beendet/geschlossen und auch zukünftig stelle ich mir die Bedarfsplanung mit der Datenbank sehr schwierig vor.



> > ```js
> > ```js
> > Herkünfte // auch über Filter lösbar - nice to have, in jedem Fall aber Herkünfte mit Namen anschreiben
> >   Gemeindename: Höri
> >     Höri, Äustler; ZHHK1321.23
> >     Höri, Reben; ZHHK1231.23
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Das wäre nun doch noch eine Gruppierung nach einem Feld innerhalb der Herkünfte. Wie gesagt möchte ich das vermeiden.
> > Im Namen der Herkünfte ist die Gemeinde vorangestellt. Die Liste mag zwar lang sein. Sie ist aber nach der Gemeinde sortiert, das heisst mit ganz kurzem Scrollen findet man problemlos die gesuchte Gemeinde. Daher würde ich Anderes priorisieren (wie du selber sagst).
> 
> Wenn eine solche Gruppierung schwierig umzusetzen ist, können wir im Moment auch darauf verzichten. Hilfreich ist, dass mit dem neuen Aufbau die Herkunftsbezeichnungen in den Kulturen und den Sammlungen nicht mehr nötig sind, da diese ja durch den Ast Herkünfte abgedeckt sind und nicht nochmals wiederholt werden müssen. Dadurch wird der einzelne Ast übersichtlicher.

Eine solche (zusätzliche) Gruppierung sehe ich aktuell nicht als nötig und würde ich daher auch erst einmal lassen.

**Comment by barbalex** [comment]
o.k., scheint klar und ist mit vernünftigem Aufwand umsetzbar

**Comment by barbalex** [comment]
In Version 1.5.0 implementiert
