### ISSUE TITLE
Mutterpflanzen standartmässig einblenden

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#90]
Bei Zählungen und Teilzählungen ist es nicht nötig die Mutterpflanzen ausblenden zu können. Es ist erwünscht, dass diese explizit erfasst werden. Dies hatten wir nicht so besprochen, oder?

**Comment by barbalex** [comment]
Du willst also, dass ich die Option, Mutterpflanzen auszublenden, entferne. Richtig?

**Comment by jmenzi** [comment]
Ja

**Comment by barbalex** [comment]
O.k., verstehe ich. Wird gemacht.

**Comment by barbalex** [comment]
Ist in Version 1.1.9 umgesetzt
