### ISSUE TITLE
Arten klassifizieren nach AP-Art und Setzugehörigkeit

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#91]
Bei der Art ein neues Feld mit Häckchen AP-Art (für Exporte wichtig) einfügen sowie einige Möglichkeit implementieren die Setzugehörigkeit bei einem Export anzeigen zu lassen.

**Comment by barbalex** [comment]
Was ist "Setzugehörigkeit"? Das haben wir (noch) nicht einmal in apflora, wenn es das ist, was ich vermute.

**Comment by barbalex** [comment]
Wozu würde die AP-Art-Eigenschaft genau benutzt? Falls danach gefiltert werden können soll, wäre das aufwändig, weil es keine interne Eigenschaft in vermehrung ist.

**Comment by jmenzi** [comment]
AP-Art-Eigenschaft wird für den Export gebraucht. Es ist aufwendig, wenn ich alle nicht AP-Arten jedes Mal beim Export herauslöschen muss. In der Ansicht ist dies eigentlich nicht nötig, da ja jede/r AV nur seine Arten sehen kann - aus Übersichtsgründen. 

Setzugehörigkeit erleichtert das Arbeiten mit Exporten, da ich häufig die Tabellen nach Set sortieren muss. Set ist eine Lebensraumgruppierung der AP-Arten basierend auf den Vertragsvergaben. Eine Liste liegt uns vor - ich schicke sie dir per Mail.

**Comment by barbalex** [comment]
> AP-Art-Eigenschaft wird für den Export gebraucht

Das geht mit ca. 2 Stunden Aufwand.

> Setzugehörigkeit erleichtert das Arbeiten mit Exporten, da ich häufig die Tabellen nach Set sortieren muss. Set ist eine Lebensraumgruppierung der AP-Arten basierend auf den Vertragsvergaben

Das müsste in apflora ergänzt werden, denn es ist klar in dessen Zuständigkeits-Bereich. 

Wenn von Seite apflora keine neuen Anforderungen dazu bestehen, könnte ich die Eigenschaft "set" dort als Feld in der AP ergänzen. 

Haupt-Aspekte: 
- Vermutlich gibt es in apflora früher oder später Anforderungen bezüglich Sets. Dann wird das geplant. Wonach sich die Implementation danach ausrichtet. Und sehr wahrscheinlich kommt es dann anders als ich es jetzt mit diesen begrenzten Informationen einrichte. Womit vieles was wir jetzt machen wieder umgebaut werden muss. Besonders aufwändig wäre, wenn die verwendeten ID's dannzumal anders sein sollten. Dann müssten wir die in vermehrung erfassten Daten alle anpassen
- Die Sets definieren soviel ich weiss, welcher Auftragnehmer welche AP's bearbeitet. Das wiederum ist mit den AV's verknüpft. In vermehrung haben wir bisher keine Verknüpfung zwischen Adressen (und damit wer was gemacht hat) und AV's. Das wurde jetzt von dir auch noch nicht angesprochen. Aber ich gehe davon aus, dass es möglich ist, dass irgendwann entsprechende Anforderungen entstehen werden. 

Mit anderen Worten: _Es kann sein_, dass wir jetzt einen kleinen Ausschnitt von etwas einführen, das später sowohl auf Seite apflora wie auch in vermehrung mit übergeordneten Zielen völlig neu definiert werden wird. Und daher die aktuelle Implementation umgebaut werden muss.

Neben-Aspekte: 
- Sets sind in dieser Liste mit Nummern und Namen enthalten. Sie brauchen, wenn sie in einer Datenbank benutzt werden, eine ID. Die Nummer funktioniert. Nicht aber Nummern gemischt mit Namen. Das müsste in der Liste korrigiert werden
- Die Arten sind in der Liste nur mit Namen enthalten. Es fehlt die arteigenschaften-id oder sisf-nr, um sie eindeutig zuordnen zu können. Das braucht daher Handarbeit von euch oder von mir

Ich schätze den Aufwand (ohne Anforderungen auf Seite apflora) auf ca. 4 Stunden.

Es gibt übrigens eine andere Möglichkeit: Du kannst einen Export, in dem die Art enthalten ist, in Excel mit Sets verknüpfen. Dafür benötigt man verknüpfbare Daten (also die arteigenschaften-id in der Liste mit den Sets und im Export). Und die Formel `sverweis`.  Dann geht das sehr schnell, vor allem wenn man es einfach vom letzten Mal wieder reinkopieren kann.

Wenn es einen dafür benötigten Export gibt, in dem die arteigenschaften-id nicht vorkommt, kann ich das relativ schnell ergänzen.

**Comment by jmenzi** [comment]
Bisher haben wir die Verknüpfung mit den Sets so geregelt, dass alle AV eines Sets alle Arten aus dem Set sehen können. Dies haben wir manuell so eingerichtet und sollte auch weiterhin manuell kein Problem sein. Hier ist also keine automatische Implementierung notwendig - es geht hier vor allem um den Export. Seitens Bedürfnisse AP-Flora kann ich keine Aussage machen. Leite die Anfrage an Rebecca weiter.

**Comment by barbalex** [comment]
> es geht hier vor allem um den Export

Wenn ihr das gemacht habt:

> dass alle AV eines Sets alle Arten aus dem Set sehen können

dann sollte das beim Export in den meisten Fällen automatisch funktionieren, weil die AV's nur exportieren können, was sie auch sehen dürfen.

Zur Präzisierung: AV's sehen alle Daten aller Arten, die bei ihrer Person unter "Mitarbeitend bei X Arten" aufgelistet sind.

Wir sollten das aber nochmals testen. Es gibt nämlich vermutlich Exporte, die auf Views basieren (in apflora sind das die meisten). Bei denen respektiert die Datenbank die Rechte _nicht_ . Das ist eine leider wenig bekannte "Eigenschaft", die ich auch zu spät entdeckt habe 😢. Vermutlich muss ich daraus Functions machen, damit es so funktioniert wie gewollt.

Die Regel ist:
- Funktioniert ein Export auch offline, basiert er sicher nicht auf einem view. Und respektiert garantiert die Rechte (vermehrung lädt nur Daten für die Offline-Nutzung, die der Benutzer sehen darf)
- Funktioniert ein Export nur online, kann er entweder auf einem view oder einer function basieren. Dann müssen wir testen bzw. ich muss nachschauen

Ob ein Export offline funktioniert siehst du auf dem Handy, wenn du vermehrung lädst und danach den Flugmodus einschaltest. Siehst du das Menü für den betreffenden Export noch? Und funktioniert er? 

Alternativ kann man auch in Chrome in den developer tools (https://stackoverflow.com/a/29326005/712005) offline stellen (F12 drücken um die dev tools zu öffnen bzw. auf macOS glaube ich Command & Shift & I). 

Ich habe jetzt auch noch nachgeschaut:
- Die Exporte für Gärten und Kulturen basieren nicht auf views
- Die zwei Exporte im Menü ganz oben rechts (Lieferungen eines Jahres, aktueller Stand Kulturen) basieren nicht auf views

Gibt es Exporte, die ich vergessen habe? Ich glaube nicht, aber ich könnte schon etwas vergessen haben. Also gibt es in vermehrung offenbar keine für Exporte benutzten Views. Womit die AV's nur bekommen, was sie sehen dürfen.

**Comment by jmenzi** [comment]
Wir werden momentan mit einem S-Verweis arbeiten. Eine Umsetzung ist deshalb nicht nötig.
