### ISSUE TITLE
Herkünfte bezeichnen und verbergen

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#92]
Bitte im gesamten Strukturbaum die Herkünfte als Namen führen und nicht als Nummern.

Die Herkünfte müssen zudem nicht mehr vor den Gärtnern versteckt werden - diese Blockade kann aufgehoben werden - da dies nicht für alle Gärtner gleich gilt. Z.B. GAW-Gärtner müssten die Herkünfte sehen, Private nicht --> zu kompliziert.

**Comment by barbalex** [comment]
> Z.B. GAW-Gärtner müssten die Herkünfte sehen, Private nicht

Was heisst das genau?
- sollen sie die Herkünfte ihrer Kulturen sehen?
- oder alle?

**Comment by jmenzi** [comment]
Soweit ich informiert bin, sollte es Zugangsbeschränkungen bei der Sichtbarkeit der Herkünfte geben. Dies hatten wir mal so besprochen und war bisher so üblich. Ich bin mir nicht sicher, ob dies bereits implementiert wurde. Falls nicht - gut! Denn wir brauchen für die Herkünfte momentan keine Zugangsbeschränkungen. Was hingegen weiter wichtig bleibt, ist der Schutz der Personendaten zu den Personen (Adressen, Telefonnummern, ect.)

**Comment by jmenzi** [comment]
Herkünfte können deshalb überall mit dem Namen angeschrieben werden, da die Nummer nicht aussagekräftig ist für den "Normalbenutzer", die kann man sich ja nicht merken.

**Comment by jmenzi** [comment]
Da die Verbergung der Herkünfte nicht mehr so wichtig zu sein scheint, muss man sich zudem fragen, was diese Laufnummer ZHHK noch bringt für neue Herkünfte - generell dient sie mehr zur Nachvollziehbarkeit alter Herkünfte.

**Comment by jmenzi** [comment]
Nochmals auf Anfang. Offenbar gab es da heute Missverständnisse. Wir müssen das nochmals intern besprechen. Ich lösche das Issue deshalb.

**Comment by barbalex** [comment]
> Ich bin mir nicht sicher, ob dies bereits implementiert wurde

Es ist implementiert.
