### ISSUE TITLE
Aktiv/Inaktiv Personen - Gärten - Kulturen führen zu Problemen mit Datenstruktur

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#93]
Gemäss deinen Angaben führen die Kategorien Aktiv und Inaktiv zu Problemen bei den Daten und du hast uns gebeten zu prüfen, ob diese Kategorien durch "gelöscht" ersetzt werden können. Anbei unsere Antwort:

Sofern bei gelöschten Gärten und Personen der Garten und die Person bei den Datensätzen, wo diese ausgewählt wurden weiterhin lesbar bleibt, kann die Einteilung von aktiv und inaktiv aus der Datenbank entfernt werden und alle inaktiven Gärten und Personen können gelöscht werden (Antwort aus Issue 84). Dies aber bitte nur, wenn es für dich wichtig ist um zukünftige Fehler zu vermeiden. Von unserer Seite aus, kann gerne alles bleiben wie es ist. 

Kulturen: Für Kulturen ist dies nicht möglich, da wir hier sicher sein müssen, dass es sich um eine echte Kultur handelt und nicht um einen Fehler, welcher gelöscht wurde. Gelöschte Kulturen können ehemalige Kulturen oder falsche Einträge sein, welche gelöscht wurden. Diese Unterscheidung ist zwingend notwendig und kann leider nicht abgeschafft werden.

**Comment by barbalex** [comment]
Dann lassen wir doch einfach alles wie es ist.
