### ISSUE TITLE
Optimierungswünsche für die Gartenanlage in Wangen

### ISSUE THREAD

**Issue by jmenzi** [barbalex/vermehrung#95]
An der heutigen Sitzung haben wir uns intensiv mit der Gartenanlage in Wangen (GAW) auseinandergesetzt. Ziel war es zu besprechen, wie wir die Eingaben und Erfassungen in die DB für die GAW in der Datenbank optimieren können (unabhängig von deinem Vorschlag in Issue 63):

- Mit einem Filter auf Ebene Teilkulturen könnten jeweils diejenigen Teilkulturen eines bestimmten Gartens ausgewählt werden. Heute ist diese Filterung noch nicht möglich. 

- Diese Teilkulturen sollten dann nach Ort 1/ Ort 2 / Ort 3 sortiert werden damit eine Abfolge der Beete entsteht. Dabei ist darauf zu achten, dass die richtige Reihenfolge erfolgt z.B. 1, 2, 3. ... 9, 10, 11, 12 nicht 1, 10, 11, 12, .... 2, 20, 21..... Sortiert werden soll nicht nach Name, sondern nach Ort. 

- Der Name der Teilkultur kann dazu verwendet werden, die Teilkultur zu beschreiben z.B. "Grosse Töpfe, allenfalls wäre es hilfreich diese Bezeichnung hinten an den Ort zu hängen z.B. 1 / 2 /3 ; Grosse Töpfe

- Teilkulturen, die es nicht mehr gibt, werden gelöscht bei der Eingabe. 

- Neue Teilkulturen können ja bereits hier erstellt werden, was super ist. Hier wäre es allenfalls hilfreich, wenn man bei der Erstellung den Garten oder die Art zuerst auswählen könnte und dann die noch  möglichen Kulturen angezeigt werden. Ansonsten muss ich in einer riesigen Liste die entsprechende Kultur suchen. 

- Dann: Man kann dann dem Beet entlang gehen und schauen, ob sich die Position der Pflanzen geändert hat, wenn z.B. bei 1, 1, 1 nicht mehr die aufgeführte Art ist, kann man den Ort ändern und die Teilkultur springt zum neuen Ort. 

- Auf Ebene der Teilkulturen müssten dann die Teil-Zählungen, Events und der Bedarf erfasst werden können, der Bedarf jeweils pro Jahr: 
--> Wenn eine Teilzählung erfasst wird, entsteht automatisch auch eine neue Zählung. 

- Zum Schluss noch ein Detail: Bei den Events müsste es noch ein Feld mit "Ausführungsmonat" (kann nummerisch erfasst werden 1, 2, 3, 4....) geben, dieses braucht der Gärtner der GAW für seine Jahresplanung. 

Gerne können wir diesen Wunsch zusammen mit Issue 63, dass ich noch nicht komplett verstehe am Telefon besprechen. Ich denke dies führt zu einer schnelleren Klärung, als grosse Texte hier.

**Comment by jmenzi** [comment]
Es handelt sich dabei übrigens nicht direkt um eine Erweiterung, da das Ziel der Integration der GAW von Anfang an definiert war. Ich habe hier deshalb bewusst dieses Label nicht gesetzt.

**Comment by barbalex** [comment]
Kurze Rückmeldung vor der Besprechung:

Danke, ich habe es gut verstanden.

Ich habe den Eindruck, dieser Vorschlag und https://github.com/barbalex/vermehrung/issues/63 lassen sich sehr gut vereinen. 

Es gibt ein paar hoffentlich Details die wir besprechen müssen.

Der Hauptunterschied: Es werden sehr viel mehr Fähigkeiten verlangt (neue Teilkulturen erfassen, Teilkultur löschen, Teilkultur bearbeiten, Events und Bedarf erfassen). Ich verstehe wieso das nützlich oder gar nötig ist. Fragt sich nur, was (kurzfristig) umsetzbar ist.

**Comment by barbalex** [comment]
Schliesse als Duplikat von https://github.com/barbalex/vermehrung/issues/63
