### ISSUE TITLE
Gelöschte Sammlungen, die nicht gelöscht sein sollten

### ISSUE THREAD

**Issue by eveterzer** [barbalex/vermehrung#96]
Hoi Alex

Uns ist per Zufall aufgefallen, dass Sammlungen gelöscht waren, die eigentlich nicht gelöscht sein sollten. Könntest du einen Auszug aller Sammlungen machen, damit wir sehen, welche Sammlungen gelöscht sind? So können wir, falls nötig, gelöschte Sammlungen wieder ungelöscht machen. 

Herzlichen Dank!

**Comment by barbalex** [comment]
Das kann man übrigens bequem in der App selbst machen:

1. Im Menü oben rechts "Gelöschte Datensätze verbergen" deaktivieren (nun werden auch gelöschte angezeigt und im Filter kann man nun nach den gelöschten filtern)
2. Sammlungen-Ordner öffnen
3. Filter setzen auf: gelöscht "ja"
<img width="1182" alt="2021-09-10_10h23_40" src="https://user-images.githubusercontent.com/669783/132824020-35f6c7c5-d6bf-4aab-ba28-1e2da0908904.png">

**Comment by barbalex** [comment]
Schliesse, da in der App selber machbar
